const en = {
  title: "Data readiness",
  back: "Back to data readiness",
  sourceRevision: "Source revision {{revision}}",
  contextitems: "Items · line {{number}}",
  contextinputs: "Inputs · line {{number}}",
  contextoutputs: "Outputs · line {{number}}",
  sourceMismatch:
    "The source context no longer matches this revision or line. Retry or return to data readiness.",
  intro: "Evidence gaps in current finalized records for the selected scope.",
  genericBanner:
    "General lot traceability only; FTR applicability is not assessed in this profile.",
  manualReview: "Product coverage status remains a manual review.",
  scope: "Scope",
  defaultScope: "Last 24 months",
  from: "Event date from",
  to: "Event date to",
  productId: "Product ID",
  lotId: "Lot ID",
  lot: "Lot",
  searchProducts: "Search products",
  searchLots: "Search lots",
  allRecords: "All records",
  noChoices: "No matching records",
  lookupError: "Records could not be loaded. Try searching again.",
  apply: "Check scope",
  reset: "Reset scope",
  retry: "Try again",
  loading: "Checking records in the selected scope…",
  refreshing: "Refreshing…",
  previousResult: "Previous scope result while refreshing",
  previousScope: "Previous successful scope",
  error: "Readiness could not be loaded. Try again.",
  unavailable: "Readiness is temporarily unavailable. Try again.",
  sessionLost: "Your session has ended. Sign in again.",
  bothDates: "Both event dates are required together.",
  dateOrder: "The end date must be on or after the start date.",
  dateWindow: "Select no more than 24 months.",
  invalidScope: "Check the date range and IDs, then try again.",
  tooLarge: "Narrow the selected scope and try again.",
  notFound: "The selected product or lot could not be found.",
  forbidden: "You do not have access to readiness for this organization.",
  empty: "Nothing to check yet",
  zero: "No findings in the displayed scope.",
  events: "Events checked",
  lots: "Lots checked",
  errors: "Errors",
  warnings: "Warnings",
  infos: "Infos",
  dependencies: "{{count}} older origins checked as dependencies",
  groupBy: "Group by",
  cte: "CTE",
  product: "Product",
  severity: "Severity",
  noCte: "Lot only",
  noProduct: "No product",
  receiving: "Receiving",
  transformation: "Transformation",
  shipping: "Shipping",
  errorSeverity: "Error",
  warningSeverity: "Warning",
  infoSeverity: "Info",
  groups: "Finding groups",
  groupsShown: "Groups {{from}}–{{to}} of {{total}}",
  previousGroups: "Previous groups",
  nextGroups: "Next groups",
  findings: "Findings",
  field: "Field",
  message: "Finding",
  source: "Source record",
  openLot: "Open lot",
  relatedOrigin: "Origin event {{number}} · rev {{revision}}",
  event: "Event {{number}} · rev {{revision}}",
  lineItems: "item {{number}}",
  lineInputs: "input {{number}}",
  lineOutputs: "output {{number}}",
  shown: "Findings {{from}}–{{to}} of {{total}}",
  previous: "Previous",
  next: "Next",
  drafts: "Draft work",
  draftsIntro: "Drafts are separate from assessed findings.",
  draftsShown: "{{shown}} of {{total}} shown",
  viewEvents: "View events",
  reviewSource: "Review source record",
  rules: {
    required_kde: "Required data is missing",
    invalid_kde: "Data has an invalid value",
    invalid_date: "Date is invalid",
    required_reference: "Required reference is missing",
    source_unresolved: "Source is unresolved",
    invalid_quantity: "Quantity is invalid",
    invalid_uom: "Unit is invalid",
    event_lot_mismatch: "Event and lot disagree",
    tlc_source_mismatch: "TLC and source disagree",
    origin_gap: "Current origin is missing",
    coverage_unresolved: "Product coverage needs review",
    exemption_review_required: "Exemption needs review",
  },
} as const;

const es = {
  title: "Preparación de datos",
  back: "Volver a preparación de datos",
  sourceRevision: "Revisión de origen {{revision}}",
  contextitems: "Artículos · línea {{number}}",
  contextinputs: "Entradas · línea {{number}}",
  contextoutputs: "Salidas · línea {{number}}",
  sourceMismatch:
    "El contexto de origen ya no coincide con esta revisión o línea. Inténtelo de nuevo o vuelva a preparación de datos.",
  intro: "Faltantes de evidencia en los registros finalizados actuales del alcance seleccionado.",
  genericBanner:
    "Solo trazabilidad general de lotes; la aplicabilidad de FTR no se evalúa en este perfil.",
  manualReview: "El estado de cobertura del producto requiere revisión manual.",
  scope: "Alcance",
  defaultScope: "Últimos 24 meses",
  from: "Fecha de evento desde",
  to: "Fecha de evento hasta",
  productId: "ID de producto",
  lotId: "ID de lote",
  lot: "Lote",
  searchProducts: "Buscar productos",
  searchLots: "Buscar lotes",
  allRecords: "Todos los registros",
  noChoices: "No hay registros coincidentes",
  lookupError: "No se pudieron cargar los registros. Repita la búsqueda.",
  apply: "Revisar alcance",
  reset: "Restablecer alcance",
  retry: "Intentar de nuevo",
  loading: "Revisando registros en el alcance seleccionado…",
  refreshing: "Actualizando…",
  previousResult: "Resultado del alcance anterior durante la actualización",
  previousScope: "Alcance anterior completado",
  error: "No se pudo cargar la preparación. Inténtelo de nuevo.",
  unavailable: "La revisión no está disponible temporalmente. Inténtelo de nuevo.",
  sessionLost: "La sesión ha terminado. Inicie sesión de nuevo.",
  bothDates: "Se requieren ambas fechas de evento.",
  dateOrder: "La fecha final debe ser igual o posterior a la inicial.",
  dateWindow: "Seleccione un máximo de 24 meses.",
  invalidScope: "Revise el intervalo de fechas y los ID e inténtelo de nuevo.",
  tooLarge: "Reduzca el alcance seleccionado e inténtelo de nuevo.",
  notFound: "No se encontró el producto o lote seleccionado.",
  forbidden: "No tiene acceso a la preparación de esta organización.",
  empty: "Aún no hay nada que revisar",
  zero: "No se encontraron faltantes en el alcance mostrado.",
  events: "Eventos revisados",
  lots: "Lotes revisados",
  errors: "Errores",
  warnings: "Advertencias",
  infos: "Informativos",
  dependencies: "{{count}} orígenes anteriores revisados como dependencias",
  groupBy: "Agrupar por",
  cte: "CTE",
  product: "Producto",
  severity: "Gravedad",
  noCte: "Solo lote",
  noProduct: "Sin producto",
  receiving: "Recepción",
  transformation: "Transformación",
  shipping: "Envío",
  errorSeverity: "Error",
  warningSeverity: "Advertencia",
  infoSeverity: "Información",
  groups: "Grupos de hallazgos",
  groupsShown: "Grupos {{from}}–{{to}} de {{total}}",
  previousGroups: "Grupos anteriores",
  nextGroups: "Grupos siguientes",
  findings: "Hallazgos",
  field: "Campo",
  message: "Hallazgo",
  source: "Registro de origen",
  openLot: "Abrir lote",
  relatedOrigin: "Evento de origen {{number}} · revisión {{revision}}",
  event: "Evento {{number}} · rev {{revision}}",
  lineItems: "artículo {{number}}",
  lineInputs: "entrada {{number}}",
  lineOutputs: "salida {{number}}",
  shown: "Hallazgos {{from}}–{{to}} de {{total}}",
  previous: "Anterior",
  next: "Siguiente",
  drafts: "Trabajo en borrador",
  draftsIntro: "Los borradores son independientes de los hallazgos evaluados.",
  draftsShown: "{{shown}} de {{total}} mostrados",
  viewEvents: "Ver eventos",
  reviewSource: "Revise el registro de origen",
  rules: {
    required_kde: "Falta un dato obligatorio",
    invalid_kde: "Un dato tiene un valor inválido",
    invalid_date: "La fecha no es válida",
    required_reference: "Falta una referencia obligatoria",
    source_unresolved: "El origen no está resuelto",
    invalid_quantity: "La cantidad no es válida",
    invalid_uom: "La unidad no es válida",
    event_lot_mismatch: "El evento y el lote no coinciden",
    tlc_source_mismatch: "El TLC y el origen no coinciden",
    origin_gap: "Falta el origen actual",
    coverage_unresolved: "La cobertura del producto requiere revisión",
    exemption_review_required: "La exención requiere revisión",
  },
} as const;

export const usReadinessCopy = { "en-US": en, "es-US": es };
