export const catalogCopy = {
  "en-US": {
    products: "Products",
    intro: "Product identities for your lot records.",
    search: "Search products by name or GTIN",
    empty: "No products match these filters.",
    loading: "Loading products…",
    refreshing: "Refreshing products…",
    loadError: "Products could not be loaded. Try again.",
    detailsLoading: "Loading product details…",
    detailsError: "Product details could not be loaded. Close this panel and try again.",
    add: "Add product",
    edit: "Edit product",
    save: "Save product",
    archive: "Archive product",
    restore: "Restore product",
    closeDetails: "Close product details",
    name: "Product name",
    gtin: "GTIN (optional)",
    gtinColumn: "GTIN",
    noGtin: "No GTIN",
    activeStatus: "Active",
    archivedStatus: "Archived",
    activeFilter: "Active",
    archivedFilter: "Archived",
    allFilter: "All",
    gtinHint: "GTIN is not required for the office workflow. Station support is outside this MVP.",
    identity: "Product ID",
    archiveConfirm: "Archive this product? Its identity and historical records will be retained.",
    restoreConfirm: "Restore this product to the active catalog?",
    saved: "Product saved.",
    archived: "Product archived.",
    restored: "Product restored.",
    invalid: "Check the highlighted fields.",
    required: "Enter a product name.",
    nameFormat: "Use no more than 200 characters.",
    gtinFormat: "Enter a valid 8, 12, 13 or 14-digit GTIN, or leave this field empty.",
    product_gtin_taken:
      "This GTIN is already used by an active product. Use another GTIN or leave it empty.",
    product_gtin_locked:
      "This product is already used in operational records. Its GTIN cannot be changed. You can still edit its name.",
    failed:
      "The product could not be saved. Your changes remain in this form. Check the saved record before retrying if the connection was lost.",
    forbidden: "Your permissions changed. Editing is no longer available.",
    archiveFailed:
      "The product status could not be changed. Close and reopen the card to check its current state before retrying.",
  },
  "es-US": {
    products: "Productos",
    intro: "Identidades de productos para sus registros de lotes.",
    search: "Buscar productos por nombre o GTIN",
    empty: "Ningún producto coincide con estos filtros.",
    loading: "Cargando productos…",
    refreshing: "Actualizando productos…",
    loadError: "No se pudieron cargar los productos. Inténtelo de nuevo.",
    detailsLoading: "Cargando los datos del producto…",
    detailsError:
      "No se pudieron cargar los datos del producto. Cierre este panel e inténtelo de nuevo.",
    add: "Añadir producto",
    edit: "Editar producto",
    save: "Guardar producto",
    archive: "Archivar producto",
    restore: "Restaurar producto",
    closeDetails: "Cerrar detalles del producto",
    name: "Nombre del producto",
    gtin: "GTIN (opcional)",
    gtinColumn: "GTIN",
    noGtin: "Sin GTIN",
    activeStatus: "Activo",
    archivedStatus: "Archivado",
    activeFilter: "Activos",
    archivedFilter: "Archivados",
    allFilter: "Todos",
    gtinHint:
      "El GTIN no es obligatorio para el flujo de oficina. Station está fuera del alcance de este MVP.",
    identity: "ID del producto",
    archiveConfirm:
      "¿Archivar este producto? Se conservarán su identidad y sus registros históricos.",
    restoreConfirm: "¿Restaurar este producto en el catálogo activo?",
    saved: "Producto guardado.",
    archived: "Producto archivado.",
    restored: "Producto restaurado.",
    invalid: "Revise los campos indicados.",
    required: "Introduzca un nombre de producto.",
    nameFormat: "Utilice un máximo de 200 caracteres.",
    gtinFormat: "Introduzca un GTIN válido de 8, 12, 13 o 14 dígitos, o deje este campo vacío.",
    product_gtin_taken:
      "Un producto activo ya utiliza este GTIN. Utilice otro GTIN o deje el campo vacío.",
    product_gtin_locked:
      "Este producto ya se utiliza en registros operativos. No se puede cambiar su GTIN. Todavía puede editar su nombre.",
    failed:
      "No se pudo guardar el producto. Sus cambios permanecen en este formulario. Si se perdió la conexión, compruebe el registro guardado antes de reintentar.",
    forbidden: "Sus permisos han cambiado. La edición ya no está disponible.",
    archiveFailed:
      "No se pudo cambiar el estado del producto. Cierre y vuelva a abrir la ficha para comprobar su estado antes de reintentar.",
  },
} as const;
