export const productProfileCopy = {
  "en-US": {
    open: "Traceability profile",
    back: "Back to products",
    intro: "Product description and documented coverage review.",
    description: "Product description",
    packaging: "Packaging",
    review: "Coverage review",
    productName: "Product name",
    brandName: "Brand",
    commodity: "Commodity",
    variety: "Variety",
    packagingSizeValue: "Pack size",
    packagingSizeUom: "Pack size unit",
    packagingStyle: "Packaging style",
    defaultQuantityUom: "Default quantity unit",
    coverageStatus: "Coverage",
    coverageRationale: "Review rationale",
    ftlCategory: "FTL category",
    ftlSourceUrl: "Source URL",
    ftlSourceVersion: "Source version",
    sizeHint:
      "Positive amount, up to 3 decimal places. Use a decimal point; units are not converted.",
    sourceHint: "Record the source and its version. Saving does not verify or fetch this URL.",
    empty: "Not specified",
    save: "Save profile",
    saved: "Profile saved.",
    loading: "Loading traceability profile…",
    loadError: "The profile could not be loaded. Any open draft has been kept.",
    failed:
      "The profile could not be saved. Your input was kept. An identical retry is safe if the connection was lost.",
    conflict:
      "This profile changed since you opened it. Your draft was kept. Load the latest profile before saving again.",
    latest: "Load latest profile",
    invalid: "Check the highlighted fields.",
    required: "This field is required.",
    format: "Check the format and length of this value.",
    sizeFormat: "Use a positive decimal, up to 999999999.999, without commas or rounding.",
    qaOnly:
      "Only QA / Traceability Manager or an admin can record coverage. Other editors can update the description.",
    qaChanged:
      "Coverage editing is no longer available. Discard coverage changes to keep editing the description.",
    discardCoverage: "Discard coverage changes",
    discardCoverageConfirm:
      "Discard only your unsaved coverage changes? Description and packaging edits will be kept.",
    readOnly: "Your current role can inspect this profile but cannot edit it.",
    generic: "FTR applicability is not assessed in this profile; general lot traceability only.",
    blocked:
      "Coverage review remains unresolved. A documented decision is required for finalization and request-package preparation.",
    reviewed:
      "Coverage review recorded. This is not a compliance verdict or confirmation that a request package is ready.",
    unsaved: "Not saved yet",
    revision: "Saved revision {{revision}}",
    draft: "Unsaved changes",
    reviewedBy: "Recorded by (user ID)",
    reviewedAt: "Recorded at",
    noReview: "No coverage decision recorded.",
    history: "Historical records stay unchanged",
    historyHint:
      "Updating this profile does not rewrite descriptions already copied into historical records.",
    statuses: {
      unknown: "Unknown",
      covered: "Covered",
      contains_ftl_same_form: "Contains FTL food in the same form",
      not_covered: "Not covered",
      exemption_review_required: "Exemption review required",
    },
    units: {
      lb: "lb · Pound",
      oz: "oz · Ounce",
      kg: "kg · Kilogram",
      g: "g · Gram",
      each: "each · Each",
      case: "case · Case",
      bag: "bag · Bag",
      cup: "cup · Cup",
      gal: "gal · Gallon",
      l: "l · Liter",
    },
  },
  "es-US": {
    open: "Perfil de trazabilidad",
    back: "Volver a productos",
    intro: "Descripción del producto y revisión documentada de cobertura.",
    description: "Descripción del producto",
    packaging: "Envasado",
    review: "Revisión de cobertura",
    productName: "Nombre del producto",
    brandName: "Marca",
    commodity: "Tipo de alimento",
    variety: "Variedad",
    packagingSizeValue: "Tamaño del envase",
    packagingSizeUom: "Unidad del envase",
    packagingStyle: "Tipo de envase",
    defaultQuantityUom: "Unidad de cantidad predeterminada",
    coverageStatus: "Cobertura",
    coverageRationale: "Justificación de la revisión",
    ftlCategory: "Categoría FTL",
    ftlSourceUrl: "URL de la fuente",
    ftlSourceVersion: "Versión de la fuente",
    sizeHint:
      "Cantidad positiva, hasta 3 decimales. Use un punto decimal; no se convierten las unidades.",
    sourceHint:
      "Registre la fuente y su versión. Al guardar no se verifica ni se consulta esta URL.",
    empty: "Sin especificar",
    save: "Guardar perfil",
    saved: "Perfil guardado.",
    loading: "Cargando el perfil de trazabilidad…",
    loadError: "No se pudo cargar el perfil. Se ha conservado el borrador abierto.",
    failed:
      "No se pudo guardar el perfil. Se conservaron sus datos. Si se perdió la conexión, es seguro repetir el mismo envío.",
    conflict:
      "Este perfil cambió desde que lo abrió. Se conservó su borrador. Cargue la última versión antes de volver a guardar.",
    latest: "Cargar el último perfil",
    invalid: "Revise los campos indicados.",
    required: "Este campo es obligatorio.",
    format: "Compruebe el formato y la longitud de este valor.",
    sizeFormat: "Use un decimal positivo de hasta 999999999.999, sin comas ni redondeo.",
    qaOnly:
      "Solo el responsable de QA / trazabilidad o un administrador puede registrar la cobertura. Otros editores pueden actualizar la descripción.",
    qaChanged:
      "Ya no puede editar la cobertura. Descarte los cambios de cobertura para seguir editando la descripción.",
    discardCoverage: "Descartar cambios de cobertura",
    discardCoverageConfirm:
      "¿Descartar solo los cambios de cobertura sin guardar? Se conservarán los cambios de descripción y envasado.",
    readOnly: "Su rol actual permite consultar este perfil, pero no editarlo.",
    generic:
      "La aplicabilidad de FTR no se evalúa en este perfil; solo trazabilidad general de lotes.",
    blocked:
      "La revisión de cobertura sigue sin resolverse. Se requiere una decisión documentada para finalizar y preparar paquetes de solicitud.",
    reviewed:
      "Revisión de cobertura registrada. No es un dictamen de cumplimiento ni confirma que un paquete de solicitud esté listo.",
    unsaved: "Aún sin guardar",
    revision: "Revisión guardada {{revision}}",
    draft: "Cambios sin guardar",
    reviewedBy: "Registrado por (ID de usuario)",
    reviewedAt: "Fecha de registro",
    noReview: "No se ha registrado una decisión de cobertura.",
    history: "Los registros históricos no cambian",
    historyHint:
      "Actualizar este perfil no modifica las descripciones ya copiadas en registros históricos.",
    statuses: {
      unknown: "Desconocida",
      covered: "Cubierto",
      contains_ftl_same_form: "Contiene un alimento FTL en la misma forma",
      not_covered: "No cubierto",
      exemption_review_required: "Requiere revisión de exención",
    },
    units: {
      lb: "lb · Libra",
      oz: "oz · Onza",
      kg: "kg · Kilogramo",
      g: "g · Gramo",
      each: "each · Unidad",
      case: "case · Caja",
      bag: "bag · Bolsa",
      cup: "cup · Vaso",
      gal: "gal · Galón",
      l: "l · Litro",
    },
  },
} as const;
