export const transformationCopy = {
  "en-US": {
    detail: {
      title: "Transformation detail",
      revision: "revision",
      current: "Current revision",
      pending: "Pending draft",
      finalizedBy: "Finalized by",
      noSnapshot: "Saved draft. No final snapshot or output lots were created.",
      provenance: "Revision and audit",
      root: "Root event",
      predecessor: "Previous revision",
      amendmentReason: "Amendment reason",
      successor: "Superseded by revision",
      voidReason: "Void reason",
      voidedBy: "Voided by",
      voidedAt: "Voided at",
      excluded:
        "Excluded from current origin. Existing output lots and case links are not automatically archived.",
    },
    history: {
      title: "Revision history",
      failed: "Revision history could not be loaded. The displayed record is unchanged.",
      readFailed: "That revision could not be opened. The displayed record is unchanged.",
      selected: "Selected",
      current: "Current revision",
      pending: "Pending draft",
    },
    cases: {
      title: "Cases",
      chooseOutput: "Choose output lot evidence",
      outputLot: "Current case links for output lot {{tlc}}",
      separate:
        "Case links are separate from event quantity and do not attest closure, scans, printing, or regulatory readiness.",
      loading: "Loading case links…",
      loadFailed: "Case links could not be loaded. Retry this read.",
      count_one: "{{count}} linked case",
      count_other: "{{count}} linked cases",
      originGap: "No current Transformation origin",
      showHistory: "Show case history",
      showActive: "Show active cases",
      noActive: "No active case links.",
      noHistory: "No case links on this page.",
      sscc: "Case SSCC",
      invalidSscc: "Enter a valid case SSCC with its check digit.",
      link: "Link cases",
      unlink: "Unlink {{sscc}}",
      unlinkTarget: "Unlink target: {{sscc}} · link {{linkId}}",
      reason: "Unlink reason",
      confirmUnlink: "Confirm unlink",
      linkedBy: "Linked by {{actor}} · {{at}}",
      unlinkedBy: "Unlinked by {{actor}} · {{at}} · {{reason}}",
      synthetic_demo: "Synthetic demo",
      existing_record: "Existing record",
      manual: "Manual link",
      demo_seed: "Demo seed link",
      inconsistent: "SSCC differs from the current case record.",
      conflict: "Case link changed. Reload case links before another action.",
      uncertain: "Case command outcome is unknown. Retry the same operation or reload case links.",
      readFailed: "The case command was accepted, but refreshed links could not be loaded.",
      reload: "Reload cases",
    },
    genealogy: {
      title: "Genealogy evidence",
      hint: "Server-selected lot and revision evidence. Completeness is limited to this bounded query.",
      current: "Current revisions",
      pinned: "Pinned revision",
      revisionMode: "Revision selection",
      directionMode: "Genealogy direction",
      showUpstream: "Show upstream",
      showDownstream: "Show downstream",
      pinnedEvidence: "Pinned revision evidence",
      upstream: "Upstream",
      downstream: "Downstream",
      reload: "Reload genealogy",
      loading: "Loading genealogy…",
      failed: "Genealogy could not be loaded.",
      complete: "Complete",
      incomplete: "Incomplete",
      counts: "{{lots}} lot · {{events}} events · {{links}} links",
      diagnostics: "Genealogy diagnostics",
      cycle: "Cycle",
      limit: "Limit reached",
      origin_gap: "Origin gap",
      inconsistent_evidence: "Inconsistent evidence",
      balance:
        "Input {{input}} {{unit}} · output {{output}} {{unit}} · difference {{delta}} {{unit}}",
      notComparable: "Not comparable",
      quantities: "Separate quantities",
      input: "Input",
      output: "Output",
      lots: "{{count}} lots",
      events: "{{count}} events",
      links: "{{count}} links",
      textGraph: "Text graph",
      selected: "Server-selected revision IDs",
      lotList: "Genealogy lots",
      eventList: "Genealogy events",
      linkList: "Genealogy links",
      originCurrent: "Current origin",
      originMissing: "No current origin",
    },
    new: "New transformation",
    title: "Transformation draft",
    completionDate: "Completion date",
    processor: "Transformation location",
    source: "Output TLC source: transformation location",
    reason: "Transformation reason",
    reasonNote: "Reason details",
    notes: "Notes",
    choose: "Choose…",
    commingling_and_repacking: "Commingling and repacking",
    repacking: "Repacking",
    relabeling: "Relabeling",
    processing: "Processing",
    other: "Other",
    inputs: "Inputs",
    outputs: "Outputs",
    documents: "Documents",
    readiness: "Readiness",
    addFtl: "Add existing FTL lot",
    addNonFtl: "Add documented non-FTL input",
    addOutput: "Add output",
    ftl: "Existing FTL lot",
    nonFtl: "Documented non-FTL input",
    input: "Input {{number}}",
    output: "Output {{number}}",
    lot: "Existing lot",
    product: "Product",
    sourceLocation: "Source location",
    reference: "Source document or reference",
    tlc: "Traceability lot code (TLC)",
    quantity: "Quantity",
    unit: "Unit",
    remove: "Remove line",
    addDocument: "Attach document",
    document: "Reference document",
    detach: "Detach",
    save: "Save draft",
    saving: "Saving…",
    saved: "Draft saved.",
    saveFailed: "Draft could not be saved. Your input was kept.",
    uncertain: "Save outcome is unknown. Retry the same operation or reload the current record.",
    retrySame: "Retry same operation",
    reload: "Reload current record",
    reloadConfirm: "Reload and discard local edits?",
    abandonConfirm:
      "Abandon retry recovery and reload the current record? The operation may still complete.",
    leaveUncertain: "This operation may have succeeded. Leave and abandon local recovery?",
    stale: "The saved version changed. Reload before another command; local edits are retained.",
    operationConflict: "This operation key has a different command. Reload before continuing.",
    notFound:
      "This transformation is no longer available. Reload the current record before continuing.",
    referenceNotFound:
      "A referenced record is unavailable. Review the references before continuing.",
    notDraft: "This revision is no longer a draft. Reload the current record before continuing.",
    genealogyCycle:
      "The command would create a genealogy cycle. Reload and review the input lots before continuing.",
    pendingAmendment:
      "An amendment already exists. Reload the current record to review its pending revision.",
    downstreamBlocked:
      "Downstream events block this command. Review the listed records and reload before continuing.",
    downstreamTitle: "Downstream blockers",
    downstreamItem: "Lot {{lotId}} · Event {{eventId}} · Root {{rootId}} · Revision {{revision}}",
    downstreamMore: "More downstream blockers exist; this list is limited.",
    readFailed:
      "The command was accepted, but the current record could not be loaded. Retry the current read.",
    check: "Check readiness",
    checkFailed: "Readiness could not be checked.",
    nonFtlCoverage: "This product is reviewed as FTL. Choose an existing FTL lot instead.",
    profileFailed: "Product coverage could not be checked. Retry the selection.",
    saveFirst: "Save the draft before checking readiness.",
    saveChanges: "Save local changes before checking readiness.",
    complete: "Complete",
    incomplete: "Incomplete",
    issue: "{{field}}: {{code}}",
    finalize: "Finalize transformation",
    finalizing: "Finalizing…",
    finalizeConfirm:
      "Finalize this saved transformation? {{inputs}} inputs, {{outputs}} outputs, {{documents}} documents. Output lots will be created by the server.",
    finalizeAmendmentConfirm:
      "Finalize this amendment? {{inputs}} inputs, {{outputs}} outputs, {{documents}} documents. Existing output lot identities remain fixed.",
    qaOnly: "QA authorization is required for this action.",
    amendment: "Start amendment",
    void: "Void transformation",
    actionReason: "QA reason",
    reasonRequired: "A reason is required.",
    amendmentHint:
      "A new QA draft will be based on this revision. Output lot identity, product, TLC and processor source remain fixed.",
    voidDraftHint: "Void this incomplete original draft? No output lots were created.",
    voidFinalHint:
      "Void this finalized revision? Output lots and existing case links remain, but have no current origin.",
    confirm: "Confirm",
    cancel: "Cancel",
    current: "Current record",
    previous: "Previous revision",
    outputIdentity: "Output lot identity is assigned by the server and cannot be edited.",
    noCases: "Finalization creates output lots; it does not link Cases.",
    noCasesAmendment: "Finalization updates the current revision; it does not link Cases.",
    invalid: "Check the highlighted draft fields.",
    loadError: "Current Transformation could not be loaded.",
  },
  "es-US": {
    detail: {
      title: "Detalle de transformación",
      revision: "revisión",
      current: "Revisión vigente",
      pending: "Borrador pendiente",
      finalizedBy: "Finalizada por",
      noSnapshot: "Borrador guardado. No se creó una instantánea final ni lotes de salida.",
      provenance: "Revisión y auditoría",
      root: "Evento raíz",
      predecessor: "Revisión anterior",
      amendmentReason: "Motivo de modificación",
      successor: "Sustituida por la revisión",
      voidReason: "Motivo de anulación",
      voidedBy: "Anulada por",
      voidedAt: "Anulada el",
      excluded:
        "Excluida como origen vigente. Los lotes de salida y vínculos de cajas existentes no se archivan automáticamente.",
    },
    history: {
      title: "Historial de revisiones",
      failed: "No se pudo cargar el historial de revisiones. El registro mostrado no cambió.",
      readFailed: "No se pudo abrir esa revisión. El registro mostrado no cambió.",
      selected: "Seleccionada",
      current: "Revisión vigente",
      pending: "Borrador pendiente",
    },
    cases: {
      title: "Cajas",
      chooseOutput: "Elegir evidencia del lote de salida",
      outputLot: "Vínculos actuales de cajas para el lote de salida {{tlc}}",
      separate:
        "Los vínculos de cajas son independientes de la cantidad del evento y no acreditan cierre, escaneo, impresión ni preparación reglamentaria.",
      loading: "Cargando vínculos de cajas…",
      loadFailed: "No se pudieron cargar los vínculos de cajas. Reintente la consulta.",
      count_one: "{{count}} caja vinculada",
      count_other: "{{count}} cajas vinculadas",
      originGap: "Sin origen vigente de transformación",
      showHistory: "Mostrar historial de cajas",
      showActive: "Mostrar cajas activas",
      noActive: "No hay vínculos de cajas activos.",
      noHistory: "No hay vínculos de cajas en esta página.",
      sscc: "SSCC de la caja",
      invalidSscc: "Introduzca un SSCC de caja válido con su dígito de control.",
      link: "Vincular cajas",
      unlink: "Desvincular {{sscc}}",
      unlinkTarget: "Objetivo de desvinculación: {{sscc}} · vínculo {{linkId}}",
      reason: "Motivo de desvinculación",
      confirmUnlink: "Confirmar desvinculación",
      linkedBy: "Vinculada por {{actor}} · {{at}}",
      unlinkedBy: "Desvinculada por {{actor}} · {{at}} · {{reason}}",
      synthetic_demo: "Demostración sintética",
      existing_record: "Registro existente",
      manual: "Vínculo manual",
      demo_seed: "Vínculo de datos de demostración",
      inconsistent: "El SSCC difiere del registro actual de la caja.",
      conflict: "El vínculo de caja cambió. Vuelva a cargar los vínculos antes de otra acción.",
      uncertain:
        "Se desconoce el resultado del comando de cajas. Reintente la misma operación o vuelva a cargar los vínculos.",
      readFailed:
        "Se aceptó el comando de cajas, pero no se pudieron cargar los vínculos actualizados.",
      reload: "Volver a cargar cajas",
    },
    genealogy: {
      title: "Evidencia genealógica",
      hint: "Evidencia de lotes y revisiones seleccionada por el servidor. La exhaustividad se limita a esta consulta acotada.",
      current: "Revisiones vigentes",
      pinned: "Revisión fijada",
      revisionMode: "Selección de revisiones",
      directionMode: "Dirección de genealogía",
      showUpstream: "Mostrar aguas arriba",
      showDownstream: "Mostrar aguas abajo",
      pinnedEvidence: "Evidencia de la revisión fijada",
      upstream: "Aguas arriba",
      downstream: "Aguas abajo",
      reload: "Volver a cargar genealogía",
      loading: "Cargando genealogía…",
      failed: "No se pudo cargar la genealogía.",
      complete: "Completa",
      incomplete: "Incompleta",
      counts: "{{lots}} lotes · {{events}} eventos · {{links}} vínculos",
      diagnostics: "Diagnósticos de genealogía",
      cycle: "Ciclo",
      limit: "Límite alcanzado",
      origin_gap: "Falta de origen",
      inconsistent_evidence: "Evidencia inconsistente",
      balance:
        "Entrada {{input}} {{unit}} · salida {{output}} {{unit}} · diferencia {{delta}} {{unit}}",
      notComparable: "No comparable",
      quantities: "Cantidades separadas",
      input: "Entrada",
      output: "Salida",
      lots: "{{count}} lotes",
      events: "{{count}} eventos",
      links: "{{count}} vínculos",
      textGraph: "Grafo en texto",
      selected: "ID de revisiones seleccionadas por el servidor",
      lotList: "Lotes de genealogía",
      eventList: "Eventos de genealogía",
      linkList: "Vínculos de genealogía",
      originCurrent: "Origen vigente",
      originMissing: "Sin origen vigente",
    },
    new: "Nueva transformación",
    title: "Borrador de transformación",
    completionDate: "Fecha de finalización",
    processor: "Ubicación de transformación",
    source: "Origen del TLC de salida: ubicación de transformación",
    reason: "Motivo de transformación",
    reasonNote: "Detalles del motivo",
    notes: "Notas",
    choose: "Elegir…",
    commingling_and_repacking: "Mezcla y reenvasado",
    repacking: "Reenvasado",
    relabeling: "Reetiquetado",
    processing: "Procesamiento",
    other: "Otro",
    inputs: "Entradas",
    outputs: "Salidas",
    documents: "Documentos",
    readiness: "Preparación",
    addFtl: "Añadir lote FTL existente",
    addNonFtl: "Añadir entrada no FTL documentada",
    addOutput: "Añadir salida",
    ftl: "Lote FTL existente",
    nonFtl: "Entrada no FTL documentada",
    input: "Entrada {{number}}",
    output: "Salida {{number}}",
    lot: "Lote existente",
    product: "Producto",
    sourceLocation: "Ubicación de origen",
    reference: "Documento o referencia de origen",
    tlc: "Código de lote de trazabilidad (TLC)",
    quantity: "Cantidad",
    unit: "Unidad",
    remove: "Quitar línea",
    addDocument: "Adjuntar documento",
    document: "Documento de referencia",
    detach: "Desvincular",
    save: "Guardar borrador",
    saving: "Guardando…",
    saved: "Borrador guardado.",
    saveFailed: "No se pudo guardar el borrador. Se conservó su entrada.",
    uncertain:
      "Se desconoce el resultado del guardado. Reintente la misma operación o vuelva a cargar el registro actual.",
    retrySame: "Reintentar la misma operación",
    reload: "Volver a cargar el registro actual",
    reloadConfirm: "¿Volver a cargar y descartar los cambios locales?",
    abandonConfirm:
      "¿Abandonar la recuperación por reintento y volver a cargar el registro actual? La operación aún podría completarse.",
    leaveUncertain:
      "Es posible que la operación se haya completado. ¿Salir y abandonar la recuperación local?",
    stale:
      "La versión guardada cambió. Vuelva a cargar antes de otra operación; se conservan los cambios locales.",
    operationConflict:
      "Esta clave de operación corresponde a otro comando. Vuelva a cargar antes de continuar.",
    notFound:
      "Esta transformación ya no está disponible. Vuelva a cargar el registro actual antes de continuar.",
    referenceNotFound:
      "Un registro de referencia no está disponible. Revise las referencias antes de continuar.",
    notDraft:
      "Esta revisión ya no es un borrador. Vuelva a cargar el registro actual antes de continuar.",
    genealogyCycle:
      "El comando crearía un ciclo de genealogía. Vuelva a cargar y revise los lotes de entrada antes de continuar.",
    pendingAmendment:
      "Ya existe una modificación. Vuelva a cargar el registro actual para revisar su revisión pendiente.",
    downstreamBlocked:
      "Los eventos posteriores bloquean este comando. Revise los registros indicados y vuelva a cargar antes de continuar.",
    downstreamTitle: "Bloqueos posteriores",
    downstreamItem: "Lote {{lotId}} · Evento {{eventId}} · Raíz {{rootId}} · Revisión {{revision}}",
    downstreamMore: "Existen más bloqueos posteriores; esta lista es limitada.",
    readFailed:
      "Se aceptó el comando, pero no se pudo cargar el registro actual. Reintente la lectura.",
    check: "Comprobar preparación",
    checkFailed: "No se pudo comprobar la preparación.",
    nonFtlCoverage: "Este producto está revisado como FTL. Elija un lote FTL existente.",
    profileFailed: "No se pudo comprobar la cobertura del producto. Reintente la selección.",
    saveFirst: "Guarde el borrador antes de comprobar la preparación.",
    saveChanges: "Guarde los cambios locales antes de comprobar la preparación.",
    complete: "Completo",
    incomplete: "Incompleto",
    issue: "{{field}}: {{code}}",
    finalize: "Finalizar transformación",
    finalizing: "Finalizando…",
    finalizeConfirm:
      "¿Finalizar esta transformación guardada? {{inputs}} entradas, {{outputs}} salidas, {{documents}} documentos. El servidor creará los lotes de salida.",
    finalizeAmendmentConfirm:
      "¿Finalizar esta modificación? {{inputs}} entradas, {{outputs}} salidas, {{documents}} documentos. Se conservan las identidades de los lotes de salida existentes.",
    qaOnly: "Se requiere autorización de control de calidad para esta acción.",
    amendment: "Iniciar modificación",
    void: "Anular transformación",
    actionReason: "Motivo de calidad",
    reasonRequired: "Se requiere un motivo.",
    amendmentHint:
      "Se creará un nuevo borrador de calidad basado en esta revisión. La identidad, producto, TLC y origen del procesador de los lotes de salida permanecen fijos.",
    voidDraftHint: "¿Anular este borrador original incompleto? No se crearon lotes de salida.",
    voidFinalHint:
      "¿Anular esta revisión finalizada? Los lotes de salida y vínculos de cajas permanecen, pero sin origen vigente.",
    confirm: "Confirmar",
    cancel: "Cancelar",
    current: "Registro actual",
    previous: "Revisión anterior",
    outputIdentity: "El servidor asigna la identidad del lote de salida y no puede editarse.",
    noCases: "La finalización crea lotes de salida; no vincula cajas.",
    noCasesAmendment: "La finalización actualiza la revisión vigente; no vincula cajas.",
    invalid: "Revise los campos señalados del borrador.",
    loadError: "No se pudo cargar la transformación actual.",
  },
} as const;
