export { createDb } from "./client.js";
export type { Db } from "./client.js";
export * as schema from "./schema.js";
export { buildAuth } from "./auth-config.js";
export type { Auth, SessionWithActiveOrg } from "./auth-config.js";
export { PLATFORM_ROLES } from "./schema/platform-auth.js";
export type { PlatformRole } from "./schema/platform-auth.js";
export { buildPlatformAuth } from "./platform-auth-config.js";
export type { BuildPlatformAuthOptions, PlatformAuth } from "./platform-auth-config.js";
export { ensurePartitions, partitionName } from "./partitions.js";
export * as sqliteSchema from "./sqlite/schema.js";
export { STATION_MIGRATIONS } from "./sqlite/migrations.js";
export type { OperatorMirrorRecord } from "./sqlite/schema.js";
