export const masterDataCopy = {
  "en-US": {
    md: {
      profile: "Profile",
      referenceData: "Reference data",
      parties: "Parties",
      locations: "Locations",
      profileBadge: "US · FSMA 204",
      genericBadge: "US · Lot traceability",
      partiesIntro: "Who supplies, processes, and receives the food.",
      locationsIntro: "Where food moves and where lot codes are assigned.",
      accessLoading: "Checking reference-data access…",
      readDenied: "Your current organization access does not include reference data.",
      accessError: "Reference-data access could not be loaded.",
      retry: "Try again",
      searchParties: "Search parties",
      searchLocations: "Search locations",
      searchParents: "Search parent parties",
      search: "Search",
      status: "Status",
      active: "Active",
      archived: "Archived",
      all: "All",
      addParty: "Add party",
      editParty: "Edit party",
      saveParty: "Save party",
      archiveParty: "Archive party",
      restoreParty: "Restore party",
      addLocation: "Add location",
      editLocation: "Edit location",
      saveLocation: "Save location",
      archiveLocation: "Archive location",
      restoreLocation: "Restore location",
      cancel: "Cancel",
      close: "Close",
      closePartyDetails: "Close party details",
      closeLocationDetails: "Close location details",
      name: "Name",
      legalName: "Legal name",
      contactName: "Contact name",
      contactPhone: "Contact phone",
      contactEmail: "Contact email",
      notes: "Notes",
      contact: "Contact",
      actions: "Actions",
      party: "Party",
      businessName: "Business name",
      internalName: "Internal name",
      phoneNumber: "Phone",
      addressKind: "Address kind",
      street: "Street address",
      coordinates: "Coordinates",
      streetAddress: "Street address",
      latitude: "Latitude",
      longitude: "Longitude",
      city: "City",
      stateOrRegion: "State or region",
      zipOrPostalCode: "ZIP or postal code",
      countryCode: "Country code",
      countryHint: "Two-letter ISO code, for example US or CA.",
      roles: "Roles",
      readiness: "Readiness",
      complete: "Complete",
      incomplete: "Incomplete",
      missingDescription: "Description is incomplete. Missing:",
      emptyParties: "No parties match these filters.",
      emptyLocations: "No locations match these filters.",
      loadError: "This list could not be loaded.",
      stale: "Refreshing after a filter change…",
      previousPage: "Previous page",
      nextPage: "Next page",
      page: "Page {{page}}",
      parentSearchEmpty: "No active parent parties match this search.",
      parentArchived: "This location belongs to an archived parent. Only archive is available.",
      archivedParentEdit: "Restore the parent party before editing or restoring this location.",
      parentArchivedSaveChoose:
        "This party was archived while you were editing. Choose another active party before saving.",
      parentArchivedSaveRestore:
        "This party was archived while you were editing. Close this form, restore the parent party, then try again.",
      partyDetails: "Party details",
      partyLocations: "Party locations",
      locationDetails: "Location details",
      noPartyLocations: "This party has no matching locations.",
      requiredError: "This field is required.",
      formatError: "Check the format of this value.",
      nameConflict: "An active party already uses this name.",
      saveFailed: "The record could not be saved. Your input was kept.",
      writeChanged: "Your write access changed. The record was not saved.",
      savedParty: "Party saved.",
      savedLocation: "Location saved.",
      archivedPartyNotice: "Party archived. Its locations were not archived.",
      restoredPartyNotice: "Party restored.",
      archivedLocationNotice: "Location archived.",
      restoredLocationNotice: "Location restored.",
      archivePartyConfirm:
        "Archive this party? Its locations will not be archived, and copied historical descriptions will remain unchanged.",
      restorePartyConfirm: "Restore this party so it can be selected for new locations?",
      archiveLocationConfirm:
        "Archive this location? Copied historical descriptions will remain unchanged.",
      restoreLocationConfirm: "Restore this location?",
      discardConfirm: "Discard unsaved changes?",
      roleSupplier: "Supplier",
      roleProcessor: "Processor",
      roleShipFrom: "Ship-from",
      roleReceiveAt: "Receive-at",
      roleRecipient: "Recipient",
      roleTlcSource: "TLC source",
      fieldBusinessName: "business name",
      fieldPhoneNumber: "phone",
      fieldStreetAddress: "street address",
      fieldLatitude: "latitude",
      fieldLongitude: "longitude",
      fieldCity: "city",
      fieldStateOrRegion: "state or region",
      fieldZipOrPostalCode: "ZIP or postal code",
      fieldCountryCode: "country code",
    },
  },
  "es-US": {
    md: {
      profile: "Perfil",
      referenceData: "Datos de referencia",
      parties: "Partes",
      locations: "Ubicaciones",
      profileBadge: "EE. UU. · FSMA 204",
      genericBadge: "EE. UU. · Trazabilidad de lotes",
      partiesIntro: "Quién suministra, procesa y recibe los alimentos.",
      locationsIntro: "Dónde se mueven los alimentos y se asignan los códigos de lote.",
      accessLoading: "Comprobando el acceso a datos de referencia…",
      readDenied: "Su acceso actual a la organización no incluye datos de referencia.",
      accessError: "No se pudo cargar el acceso a datos de referencia.",
      retry: "Intentar de nuevo",
      searchParties: "Buscar partes",
      searchLocations: "Buscar ubicaciones",
      searchParents: "Buscar partes principales",
      search: "Buscar",
      status: "Estado",
      active: "Activas",
      archived: "Archivadas",
      all: "Todas",
      addParty: "Agregar parte",
      editParty: "Editar parte",
      saveParty: "Guardar parte",
      archiveParty: "Archivar parte",
      restoreParty: "Restaurar parte",
      addLocation: "Agregar ubicación",
      editLocation: "Editar ubicación",
      saveLocation: "Guardar ubicación",
      archiveLocation: "Archivar ubicación",
      restoreLocation: "Restaurar ubicación",
      cancel: "Cancelar",
      close: "Cerrar",
      closePartyDetails: "Cerrar detalles de la parte",
      closeLocationDetails: "Cerrar detalles de la ubicación",
      name: "Nombre",
      legalName: "Razón social",
      contactName: "Nombre del contacto",
      contactPhone: "Teléfono del contacto",
      contactEmail: "Correo del contacto",
      notes: "Notas",
      contact: "Contacto",
      actions: "Acciones",
      party: "Parte",
      businessName: "Nombre comercial",
      internalName: "Nombre interno",
      phoneNumber: "Teléfono",
      addressKind: "Tipo de dirección",
      street: "Dirección postal",
      coordinates: "Coordenadas",
      streetAddress: "Dirección postal",
      latitude: "Latitud",
      longitude: "Longitud",
      city: "Ciudad",
      stateOrRegion: "Estado o región",
      zipOrPostalCode: "Código postal",
      countryCode: "Código de país",
      countryHint: "Código ISO de dos letras, por ejemplo US o CA.",
      roles: "Roles",
      readiness: "Preparación",
      complete: "Completa",
      incomplete: "Incompleta",
      missingDescription: "La descripción está incompleta. Falta:",
      emptyParties: "Ninguna parte coincide con estos filtros.",
      emptyLocations: "Ninguna ubicación coincide con estos filtros.",
      loadError: "No se pudo cargar esta lista.",
      stale: "Actualizando después de cambiar el filtro…",
      previousPage: "Página anterior",
      nextPage: "Página siguiente",
      page: "Página {{page}}",
      parentSearchEmpty: "Ninguna parte principal activa coincide con esta búsqueda.",
      parentArchived: "Esta ubicación pertenece a una parte archivada. Solo se puede archivar.",
      archivedParentEdit: "Restaure la parte principal antes de editar o restaurar esta ubicación.",
      parentArchivedSaveChoose:
        "Esta parte se archivó mientras editaba. Elija otra parte activa antes de guardar.",
      parentArchivedSaveRestore:
        "Esta parte se archivó mientras editaba. Cierre este formulario, restaure la parte principal e inténtelo de nuevo.",
      partyDetails: "Detalles de la parte",
      partyLocations: "Ubicaciones de la parte",
      locationDetails: "Detalles de la ubicación",
      noPartyLocations: "Esta parte no tiene ubicaciones coincidentes.",
      requiredError: "Este campo es obligatorio.",
      formatError: "Revise el formato de este valor.",
      nameConflict: "Una parte activa ya usa este nombre.",
      saveFailed: "No se pudo guardar el registro. Se conservaron sus datos.",
      writeChanged: "Su acceso de escritura cambió. El registro no se guardó.",
      savedParty: "Parte guardada.",
      savedLocation: "Ubicación guardada.",
      archivedPartyNotice: "Parte archivada. Sus ubicaciones no se archivaron.",
      restoredPartyNotice: "Parte restaurada.",
      archivedLocationNotice: "Ubicación archivada.",
      restoredLocationNotice: "Ubicación restaurada.",
      archivePartyConfirm:
        "¿Archivar esta parte? Sus ubicaciones no se archivarán y las descripciones históricas copiadas no cambiarán.",
      restorePartyConfirm: "¿Restaurar esta parte para seleccionarla en ubicaciones nuevas?",
      archiveLocationConfirm:
        "¿Archivar esta ubicación? Las descripciones históricas copiadas no cambiarán.",
      restoreLocationConfirm: "¿Restaurar esta ubicación?",
      discardConfirm: "¿Descartar los cambios sin guardar?",
      roleSupplier: "Proveedor",
      roleProcessor: "Procesador",
      roleShipFrom: "Origen de envío",
      roleReceiveAt: "Punto de recepción",
      roleRecipient: "Destinatario",
      roleTlcSource: "Fuente de TLC",
      fieldBusinessName: "nombre comercial",
      fieldPhoneNumber: "teléfono",
      fieldStreetAddress: "dirección postal",
      fieldLatitude: "latitud",
      fieldLongitude: "longitud",
      fieldCity: "ciudad",
      fieldStateOrRegion: "estado o región",
      fieldZipOrPostalCode: "código postal",
      fieldCountryCode: "código de país",
    },
  },
} as const;
