export const tracePresentationCopy = {
  "en-US": {
    nodes: "nodes",
    edges: "edges",
    current: "Current trace",
    table: "Current trace lines",
    lots: "Lots in this trace",
    openLot: "Open lot",
    empty: "No current chain yet.",
    eventActions: "Open an exact event line",
    from: "From node",
    to: "To node",
    kind: "CTE / line",
    quantity: "Quantity / UOM",
    event: "Event",
    date: "Event date",
    edge: "Edge ID",
    revision: "revision",
    line: "line",
    receiving: "Receiving",
    shipping: "Shipping",
    transformation_input: "Transformation input",
    transformation_output: "Transformation output",
    lot: "Lot",
    location: "Location",
    transformation: "Transformation",
    material: "Non-FTL material",
  },
  "es-US": {
    nodes: "nodos",
    edges: "conexiones",
    current: "Trazabilidad actual",
    table: "Líneas de trazabilidad actual",
    lots: "Lotes en esta trazabilidad",
    openLot: "Abrir lote",
    empty: "Aún no hay cadena actual.",
    eventActions: "Abrir una línea exacta de evento",
    from: "Nodo de origen",
    to: "Nodo de destino",
    kind: "CTE / línea",
    quantity: "Cantidad / unidad",
    event: "Evento",
    date: "Fecha del evento",
    edge: "ID de conexión",
    revision: "revisión",
    line: "línea",
    receiving: "Recepción",
    shipping: "Envío",
    transformation_input: "Entrada de transformación",
    transformation_output: "Salida de transformación",
    lot: "Lote",
    location: "Ubicación",
    transformation: "Transformación",
    material: "Material no FTL",
  },
} as const;

export function presentationCopy(language: string) {
  return tracePresentationCopy[language.startsWith("es") ? "es-US" : "en-US"];
}
