import type { Locale } from "./pages";

const RU = {
  common: {
    breadcrumbsLabel: "Хлебные крошки",
    discussTask: "Обсудить задачу",
    homeLabel: "Маркиро, на главную страницу",
    menuClose: "Закрыть меню",
    menuOpen: "Открыть меню",
    nav: {
      articles: "Статьи",
      faq: "Вопросы",
      howItWorks: "Как работает",
      instructions: "Инструкции",
      product: "Продукт",
    },
    navigationLabel: "Основная навигация",
    faqKicker: "Вопросы по теме",
    relatedArticlesHeading: "Статьи по теме",
    relatedArticlesKicker: "Разобрано подробнее",
    reviewedLabel: "Проверено",
    summaryHeading: "Коротко о главном",
    summaryKicker: "Коротко",
    relatedHeading: "Связанные производственные сценарии",
    relatedKicker: "Следующий шаг",
    requestDemo: "Запросить демонстрацию",
    requestDemoShort: "Запросить демо",
    seoCtaHeading: "Проверим сценарий на данных вашей линии.",
    seoCtaKicker: "Демонстрация на вашем процессе",
    skipLink: "Перейти к содержанию",
  },
  home: {
    demo: {
      company: "Компания",
      contactNote: "Контактный телефон появится после подключения публичной линии.",
      email: "Email",
      heading: "Покажем Markiro на вашей линии.",
      kicker: "08 / ДЕМО НА ВАШЕЙ ЛИНИИ",
      lead: "Разберём ваш процесс, сверим правила вашей товарной группы и покажем сценарий на вашем продукте.",
      legal: {
        consent: "согласия",
        prefix: "Даю согласие на обработку персональных данных на условиях",
        privacy: "политикой обработки персональных данных",
        separator: "и подтверждаю, что ознакомился с",
      },
      name: "Как к вам обращаться",
      phone: "Телефон для связи (необязательно)",
      unavailable: "Онлайн-отправка временно недоступна.",
      unavailableContact: "Напишите нам на",
    },
    mapHero: {
      filmLink: "Посмотреть, как это работает",
      heading: ["Маркировка и агрегация.", "Линия идёт."],
      hint: "Наведите на точку, чтобы увидеть экран на этом участке",
      imageAlt:
        "Макет завода: цех с линией, упаковкой и складом, киоск у входа, офис и склад готовой продукции",
      kicker: "МАРКИРОВКА · АГРЕГАЦИЯ · ПРОСЛЕЖИВАЕМОСТЬ",
      lead: "Проверяем коды, собираем короба и паллеты, печатаем этикетки для соков, косметики, пива и молочной продукции. Когда пропадает сеть, станция продолжает работать.",
      spots: [
        {
          id: "line",
          label: "Линия",
          line: "Станция проверяет каждый код до короба.",
          screenAlt: "Экран станции: сборка короба, принятые коды в журнале смены",
          target: "#product-line",
        },
        {
          id: "packing",
          label: "Упаковка",
          line: "Когда короб заполнен, станция печатает этикетку с SSCC.",
          screenAlt: "Экран станции: короб и паллета в работе",
          target: "#product-line",
        },
        {
          id: "warehouse",
          label: "Склад",
          line: "ТСД собирает паллеты и ведёт инвентаризацию.",
          screenAlt: "Экран ТСД: сборка короба на терминале",
          target: "#product-handheld",
        },
        {
          id: "kiosk",
          label: "Киоск",
          line: "Покупки сотрудников, образцы и бой оформляют на киоске.",
          screenAlt: "Экран киоска выбытия",
          target: "#product-kiosk",
        },
        {
          id: "office",
          label: "Офис",
          line: "В кабинете все смены, обмен с 1С и выгрузки в Честный знак.",
          screenAlt: "Кабинет: сводка производства за день",
          target: "#product-office",
        },
      ],
      stripLabel: "Участки производства",
    },
    productSection: {
      cards: [
        {
          caption: "КИОСК",
          id: "kiosk",
          kicker: "ВЫБЫТИЕ · КИОСК",
          link: "Киоск самовыдачи",
          screenAlt: "Экран киоска выбытия",
          text: "Когда продукция уходит не через отгрузку (покупка сотрудником, образцы, бой), сотрудник сканирует на киоске бейдж и коды, а заявка приходит в кабинет.",
          title: "Выбытие оформляют на киоске.",
        },
        {
          caption: "КАБИНЕТ · СВЯЗЬ С ЧЕСТНЫМ ЗНАКОМ",
          id: "integrations",
          kicker: "ИНТЕГРАЦИИ",
          link: "Интеграция с 1С",
          screenAlt: "Кабинет: каталог продукции со статусами в Честном знаке",
          text: "Кабинет связан с Честным знаком, а с 1С обменивается заданиями и статусами. Данные не переносят вручную.",
          title: "Честный знак, 1С и API.",
        },
      ],
      heading: "Экраны, с которыми работают на смене.",
      kicker: "01 / ПРОДУКТ",
      rows: [
        {
          bullets: [
            "Повторные коды и чужой GTIN",
            "Несколько терминалов на одной линии",
            "Печать в ZPL и TSPL",
          ],
          caption: "СТАНЦИЯ · КОРОБ И ПАЛЛЕТА",
          id: "line",
          kicker: "ЛИНИЯ · СТАНЦИЯ",
          link: "Маркировка и агрегация",
          screenAlt: "Экран станции: короб, паллета и журнал смены",
          text: "Станция не пустит в короб повторный код, код чужого товара или код с ошибкой. Оператор видит причину на экране, а заполненный короб сразу получает этикетку с SSCC.",
          title: "Каждый код проверяем до короба.",
        },
        {
          bullets: [
            "Сборка и разборка паллет",
            "Инвентаризация у стеллажа",
            "Печать этикеток с терминала",
          ],
          caption: "ТСД НА ANDROID",
          id: "handheld",
          kicker: "СКЛАД · ТСД НА ANDROID",
          link: "Как это выглядит на складе",
          screenAlt: "Экран ТСД: сборка короба на терминале",
          text: "Кладовщик с терминалом на Android собирает паллеты, снимает с них коробы и проводит инвентаризацию у стеллажа. Операции уходят в тот же журнал, что и со станции.",
          title: "Паллеты собираем на ТСД.",
        },
        {
          bullets: [
            "Сводка смен и сигналы",
            "Выгрузки в Честный знак",
            "Товары из Национального каталога",
          ],
          caption: "КАБИНЕТ · СВОДКА СМЕН",
          id: "office",
          kicker: "ОФИС · КАБИНЕТ",
          link: "Инструкции для кабинета",
          screenAlt: "Кабинет: сводка производства за день",
          text: "Сюда приходят операции со станций, ТСД и киосков. Отсюда идёт обмен с 1С и выгрузка документов для Честного знака.",
          title: "В кабинете видно каждую смену.",
        },
      ],
    },
    offline: {
      caption: "СТАНЦИЯ БЕЗ СЕТИ",
      heading: ["Сеть может исчезнуть.", "Производство не должно."],
      kicker: "02 / БЕЗ СЕТИ",
      lead: "Станция пишет операции в свой журнал и отправляет их на сервер, когда связь вернётся. Если записи с разных станций не сошлись, это видно в разделе «Конфликты».",
      points: [
        ["Проверка на месте", "Коды проверяются на станции без ожидания сервера."],
        ["Операции сохраняются", "Каждое действие лежит в локальном журнале до отправки."],
        [
          "Линия продолжает работу",
          "Оператор видит, что происходит, и продолжает смену после сбоя.",
        ],
      ],
      screenAlt:
        "Станция без связи с сервером: «Сервер: нет связи», «Синх. 7», счётчик смены и журнал с принятыми кодами",
    },
    traceability: {
      caption: "СТАНЦИЯ · КОНФЛИКТЫ",
      heading: "У каждой ошибки есть история и следующий шаг.",
      kicker: "03 / ПРОСЛЕЖИВАЕМОСТЬ",
      lead: "Каждое действие остаётся в истории. Проблемную операцию можно понять, повторить или передать ответственному.",
      screenAlt: "Экран станции: список конфликтов",
    },
    filmBlock: {
      button: "Посмотреть, как это работает",
      heading: "Посмотрите, как код проходит через производство.",
      imageAlt: "Страница «Как работает»: глава про склад на макете завода",
      kicker: "04 / КАК ЭТО РАБОТАЕТ",
      lead: "Прокрутите страницу, и камера пройдёт по макету завода: линия, упаковка, склад, киоск и офис.",
    },
    rollout: {
      heading: "Для любой маркируемой продукции.",
      kicker: "05 / ВНЕДРЕНИЕ",
      labels: [
        {
          alt: "Этикетка короба для сока: товар, даты, GTIN и штрихкод SSCC",
          caption: "ЭТИКЕТКА КОРОБА · СОКИ",
          id: "juices",
        },
        {
          alt: "Этикетка короба для косметики: товар, даты, GTIN и штрихкод SSCC",
          caption: "ЭТИКЕТКА КОРОБА · КОСМЕТИКА",
          id: "cosmetics",
        },
      ],
      lead: "Коды, короба и паллеты устроены одинаково для соков и воды, молочной продукции, пива и косметики. Особенности вашей товарной группы сверяем до запуска.",
      steps: [
        [
          "Сверяем правила вашей товарной группы",
          "Фиксируем товарную группу, форм-фактор упаковки и правила учёта.",
        ],
        ["Разбираем линию", "Сопоставляем оборудование, роли и текущий маршрут кодов."],
        ["Запускаем один сценарий", "Настраиваем станцию под конкретный продукт и короб."],
        ["Проверяем на смене", "Работаем с оператором и проверяем восстановление после ошибок."],
      ],
    },
    documents: {
      allInstructions: "Все инструкции",
      covers: [
        {
          alt: "Первая страница инструкции MKR-INS-01",
          caption: "MKR-INS-01 · СТАНЦИЯ: ВХОД ОПЕРАТОРА И СТАРТ СМЕНЫ",
          code: "mkr-ins-01",
        },
        {
          alt: "Первая страница инструкции MKR-INS-02",
          caption: "MKR-INS-02 · СТАНЦИЯ: РАБОЧИЙ ЦИКЛ",
          code: "mkr-ins-02",
        },
        {
          alt: "Первая страница инструкции MKR-INS-09",
          caption: "MKR-INS-09 · КАБИНЕТ: ЗАКРЫТИЕ И ОТЧЁТЫ СМЕНЫ",
          code: "mkr-ins-09",
        },
      ],
      heading: "Всё описано до покупки.",
      kicker: "06 / ОТКРЫТЫЕ ДОКУМЕНТЫ",
      lead: "Инструкции для станции и кабинета, договор и регламенты опубликованы на сайте. Их можно прочитать до разговора с нами.",
      legal: "Договор и регламенты",
    },
    materials: {
      allArticles: "Все статьи",
      heading: "Разборы задач с линии.",
      kicker: "07 / СТАТЬИ",
    },
  },
  hub: {
    articlesHeading: "Все статьи",
    articlesKicker: "01 / Практика",
    instructionsKicker: "Инструкции",
    minutes: "мин чтения",
    otherGroup: "Другие инструкции",
    registryLink: "публичном реестре документов",
    registryNote: "Коды, редакции, даты и PDF/A всех инструкций также опубликованы в",
  },
} as const;

const EN = {
  common: {
    breadcrumbsLabel: "Breadcrumbs",
    discussTask: "Discuss your workflow",
    homeLabel: "Markiro home page",
    menuClose: "Close menu",
    menuOpen: "Open menu",
    nav: {
      articles: "Articles",
      faq: "Questions",
      howItWorks: "How it works",
      instructions: "Instructions",
      product: "Product",
    },
    navigationLabel: "Primary navigation",
    faqKicker: "Questions on this topic",
    relatedArticlesHeading: "Related articles",
    relatedArticlesKicker: "Covered in depth",
    reviewedLabel: "Reviewed",
    summaryHeading: "In short",
    summaryKicker: "Summary",
    relatedHeading: "Related production workflows",
    relatedKicker: "Next step",
    requestDemo: "Request a demonstration",
    requestDemoShort: "Request a demo",
    seoCtaHeading: "Test the workflow with data from your line.",
    seoCtaKicker: "A demonstration using your process",
    skipLink: "Skip to content",
  },
  home: {
    demo: {
      company: "Company",
      contactNote: "A contact number will appear when the public phone line is connected.",
      email: "Email",
      heading: "We will show Markiro on your line.",
      kicker: "08 / DEMO ON YOUR LINE",
      lead: "We will walk through your process, check the rules of your product group and show the scenario on your product.",
      legal: {
        consent: "personal-data consent",
        prefix: "I consent to the processing of my personal data under the",
        privacy: "personal-data processing policy",
        separator: "and confirm that I have read the",
      },
      name: "Your name",
      phone: "Contact phone (optional)",
      unavailable: "Online submission is temporarily unavailable.",
      unavailableContact: "Email us at",
    },
    mapHero: {
      filmLink: "See how it works",
      heading: ["Serialization and aggregation.", "Keep the line moving."],
      hint: "Hover a dot to see the screen used in that area",
      imageAlt:
        "Scale model of a plant: the hall with the line, packing and warehouse, the kiosk at the entrance, the office and the finished-goods store",
      kicker: "SERIALIZATION · AGGREGATION · TRACEABILITY",
      lead: "We verify codes, assemble cases and pallets, and print labels for juice, cosmetics, beer and dairy. When the network drops, the station keeps working.",
      spots: [
        {
          id: "line",
          label: "Line",
          line: "The station checks every code before it goes into a case.",
          screenAlt: "Station screen: case assembly and accepted codes in the shift log",
          target: "#product-line",
        },
        {
          id: "packing",
          label: "Packing",
          line: "When a case is full, the station prints an SSCC label.",
          screenAlt: "Station screen: a case and a pallet in progress",
          target: "#product-line",
        },
        {
          id: "warehouse",
          label: "Warehouse",
          line: "The handheld builds pallets and runs inventory.",
          screenAlt: "Handheld screen: case assembly on the terminal",
          target: "#product-handheld",
        },
        {
          id: "kiosk",
          label: "Kiosk",
          line: "Employee purchases, samples and breakage go through the kiosk.",
          screenAlt: "Disposal kiosk screen",
          target: "#product-kiosk",
        },
        {
          id: "office",
          label: "Office",
          line: "The admin panel holds every shift, the 1C exchange and Chestny ZNAK exports.",
          screenAlt: "Admin panel: today's production summary",
          target: "#product-office",
        },
      ],
      stripLabel: "Production areas",
    },
    productSection: {
      cards: [
        {
          caption: "KIOSK",
          id: "kiosk",
          kicker: "DISPOSAL · KIOSK",
          link: "Self-service kiosk",
          screenAlt: "Disposal kiosk screen",
          text: "When products leave other than by shipment (employee purchases, samples, breakage), the employee scans a badge and the codes at the kiosk, and the request arrives in the admin panel.",
          title: "Disposal goes through the kiosk.",
        },
        {
          caption: "ADMIN PANEL · CHESTNY ZNAK LINK",
          id: "integrations",
          kicker: "INTEGRATIONS",
          link: "1C integration",
          screenAlt: "Admin panel: the product catalog with Chestny ZNAK statuses",
          text: "The admin panel is linked to Chestny ZNAK and exchanges tasks and statuses with 1C, so nobody retypes data.",
          title: "Chestny ZNAK, 1C and an API.",
        },
      ],
      heading: "The screens people work with on shift.",
      kicker: "01 / PRODUCT",
      rows: [
        {
          bullets: [
            "Repeated codes and foreign GTINs",
            "Several terminals on one line",
            "Printing in ZPL and TSPL",
          ],
          caption: "STATION · CASE AND PALLET",
          id: "line",
          kicker: "LINE · STATION",
          link: "Serialization and aggregation",
          screenAlt: "Station screen: a case, a pallet and the shift log",
          text: "The station keeps repeated codes, codes of another product and malformed codes out of the case. The operator sees the reason on screen, and a full case gets its SSCC label at once.",
          title: "We check every code before it goes into a case.",
        },
        {
          bullets: [
            "Building and breaking pallets",
            "Inventory at the rack",
            "Label printing from the terminal",
          ],
          caption: "ANDROID HANDHELD",
          id: "handheld",
          kicker: "WAREHOUSE · ANDROID HANDHELD",
          link: "See it in the warehouse",
          screenAlt: "Handheld screen: case assembly on the terminal",
          text: "A warehouse worker with an Android handheld builds pallets, removes cases from them and runs inventory at the rack. Operations go into the same log as the station's.",
          title: "Pallets are built on the handheld.",
        },
        {
          bullets: [
            "Shift summary and alerts",
            "Exports to Chestny ZNAK",
            "Products from the National Catalogue",
          ],
          caption: "ADMIN PANEL · SHIFT SUMMARY",
          id: "office",
          kicker: "OFFICE · ADMIN PANEL",
          link: "Admin panel instructions",
          screenAlt: "Admin panel: today's production summary",
          text: "Operations from stations, handhelds and kiosks arrive here. From here you exchange data with 1C and export documents for Chestny ZNAK.",
          title: "Every shift is visible in the admin panel.",
        },
      ],
    },
    offline: {
      caption: "STATION WITHOUT A NETWORK",
      heading: ["The network may disappear.", "Production must not."],
      kicker: "02 / WITHOUT A NETWORK",
      lead: "The station writes operations to its own journal and sends them to the server when the connection returns. If records from different stations disagree, they show up under Conflicts.",
      points: [
        ["Checks on the spot", "Codes are verified on the station without waiting for the server."],
        ["Operations are kept", "Every action stays in the local journal until it is sent."],
        [
          "The line keeps running",
          "The operator sees what is happening and carries on after a failure.",
        ],
      ],
      screenAlt:
        "Station without a server connection: Server No connection, Sync 7, the shift counter and the journal of accepted codes",
    },
    traceability: {
      caption: "STATION · CONFLICTS",
      heading: "Every error has a history and a next step.",
      kicker: "03 / TRACEABILITY",
      lead: "Every action stays in the history. A failed operation can be understood, retried or handed to the right person.",
      screenAlt: "Station screen: the list of conflicts",
    },
    filmBlock: {
      button: "See how it works",
      heading: "See how a code travels through production.",
      imageAlt: "The How it works page: the warehouse chapter over the scale model",
      kicker: "04 / HOW IT WORKS",
      lead: "Scroll the page and the camera moves through a scale model of the plant: the line, packing, the warehouse, the kiosk and the office.",
    },
    rollout: {
      heading: "For any marked goods.",
      kicker: "05 / ROLLOUT",
      labels: [
        {
          alt: "Juice case label: product, dates, GTIN and SSCC barcode",
          caption: "CASE LABEL · JUICE",
          id: "juices",
        },
        {
          alt: "Cosmetics case label: product, dates, GTIN and SSCC barcode",
          caption: "CASE LABEL · COSMETICS",
          id: "cosmetics",
        },
      ],
      lead: "Codes, cases and pallets work the same way for juice and water, dairy, beer and cosmetics. We check the rules of your product group before launch.",
      steps: [
        [
          "We check the rules of your product group",
          "We record the product group, the packaging format and the accounting rules.",
        ],
        ["We walk the line", "We map the equipment, the roles and the current route of codes."],
        ["We launch one scenario", "We set up the station for a specific product and case."],
        ["We test it on shift", "We work with the operator and test recovery after errors."],
      ],
    },
    documents: {
      allInstructions: "All instructions",
      covers: [
        {
          alt: "First page of instruction MKR-INS-01",
          caption: "MKR-INS-01 · STATION: OPERATOR SIGN-IN AND SHIFT START",
          code: "mkr-ins-01",
        },
        {
          alt: "First page of instruction MKR-INS-02",
          caption: "MKR-INS-02 · STATION: THE WORK CYCLE",
          code: "mkr-ins-02",
        },
        {
          alt: "First page of instruction MKR-INS-09",
          caption: "MKR-INS-09 · ADMIN PANEL: CLOSING AND SHIFT REPORTS",
          code: "mkr-ins-09",
        },
      ],
      heading: "Everything is documented before you buy.",
      kicker: "06 / OPEN DOCUMENTS",
      lead: "Station and admin panel instructions, the agreement and the regulations are published on the site. You can read them before you talk to us.",
      legal: "Agreement and regulations",
    },
    materials: {
      allArticles: "All articles",
      heading: "Field notes from the line.",
      kicker: "07 / ARTICLES",
    },
  },
  hub: {
    articlesHeading: "All articles",
    articlesKicker: "01 / Practice",
    instructionsKicker: "Instructions",
    minutes: "min read",
    otherGroup: "Other instructions",
    registryLink: "public document registry",
    registryNote:
      "Codes, revisions, dates and PDF/A files of every instruction are also published in the",
  },
} as const;

export function getUiCopy(locale: Locale): typeof RU | typeof EN {
  return locale === "ru" ? RU : EN;
}
