import type { Locale } from "./pages";

const RU = {
  common: {
    breadcrumbsLabel: "Хлебные крошки",
    discussTask: "Обсудить задачу",
    footerLabel: "Ссылки в подвале",
    homeLabel: "Маркиро, на главную страницу",
    menuClose: "Закрыть меню",
    menuOpen: "Открыть меню",
    nav: {
      articles: "Статьи",
      faq: "Вопросы",
      howItWorks: "Как работает",
      instructions: "Инструкции",
      product: "Продукт",
    },
    navigationLabel: "Основная навигация",
    faqKicker: "Вопросы по теме",
    relatedArticlesHeading: "Статьи по теме",
    relatedArticlesKicker: "Разобрано подробнее",
    reviewedLabel: "Проверено",
    summaryHeading: "Коротко о главном",
    summaryKicker: "Коротко",
    relatedHeading: "Связанные производственные сценарии",
    relatedKicker: "Следующий шаг",
    requestDemo: "Запросить демонстрацию",
    requestDemoShort: "Запросить демо",
    seoCtaHeading: "Проверим сценарий на данных вашей линии.",
    seoCtaKicker: "Демонстрация на вашем процессе",
    skipLink: "Перейти к содержанию",
  },
  home: {
    continuity: {
      heading: ["Сеть может исчезнуть.", "Производство не должно."],
      kicker: "01 / НЕПРЕРЫВНОСТЬ",
      lead: "Станция работает локально и синхронизирует операции, когда соединение возвращается.",
      points: [
        ["Проверка на месте", "Коды проходят проверку на станции без ожидания ответа сервера."],
        [
          "Операции сохраняются",
          "Каждое действие остаётся в локальном журнале до уверенной отправки.",
        ],
        ["Линия продолжает работу", "Оператор видит состояние и может восстановиться после сбоя."],
      ],
    },
    cycle: {
      heading: ["КОД ПРОШЁЛ.", "КОРОБ СОБРАН."],
      kicker: "02 / ПРОИЗВОДСТВЕННЫЙ ЦИКЛ",
      lead: "Оператор последовательно проверяет код на бутылке или банке, собирает короб и печатает этикетку с SSCC.",
      stages: [
        ["Проверка кода", "Система сверяет код и не пропускает проблемный."],
        ["Сборка короба", "Товар собирается в короб с сохранением связи каждого кода с SSCC."],
        ["Этикетка и печать", "Макет строится из тех же данных, которые прошли проверку."],
      ],
    },
    demo: {
      company: "Компания",
      contactNote: "Контактный телефон появится после подключения публичной линии.",
      email: "Email",
      heading: "Покажем Markiro на вашей линии.",
      kicker: "08 / ДЕМО НА ВАШЕЙ ЛИНИИ",
      lead: "Разберём ваш процесс и покажем рабочий сценарий без абстрактной презентации.",
      legal: {
        consent: "согласия",
        prefix: "Даю согласие на обработку персональных данных на условиях",
        privacy: "политикой обработки персональных данных",
        separator: "и подтверждаю, что ознакомился с",
      },
      name: "Как к вам обращаться",
      phone: "Телефон для связи (необязательно)",
      unavailable: "Онлайн-отправка временно недоступна.",
      unavailableContact: "Напишите нам на",
    },
    mapHero: {
      filmLink: "Посмотреть, как это работает",
      heading: ["Маркировка и агрегация.", "Линия идёт."],
      hint: "Наведите на точку, чтобы увидеть экран на этом участке",
      imageAlt:
        "Макет завода: цех с линией, упаковкой и складом, киоск у входа, офис и склад готовой продукции",
      kicker: "МАРКИРОВКА · АГРЕГАЦИЯ · ПРОСЛЕЖИВАЕМОСТЬ",
      lead: "Проверяем коды, собираем короба и паллеты, печатаем этикетки для соков, косметики, пива и молочной продукции. Когда пропадает сеть, станция продолжает работать.",
      spots: [
        {
          id: "line",
          label: "Линия",
          line: "Станция проверяет каждый код до короба.",
          screenAlt: "Экран станции: сборка короба, принятые коды в журнале смены",
          target: "#product-line",
        },
        {
          id: "packing",
          label: "Упаковка",
          line: "Когда короб заполнен, станция печатает этикетку с SSCC.",
          screenAlt: "Экран станции: короб и паллета в работе",
          target: "#product-line",
        },
        {
          id: "warehouse",
          label: "Склад",
          line: "ТСД собирает паллеты и ведёт инвентаризацию.",
          screenAlt: "Экран ТСД: сборка короба на терминале",
          target: "#product-handheld",
        },
        {
          id: "kiosk",
          label: "Киоск",
          line: "Покупки сотрудников, образцы и бой оформляют на киоске.",
          screenAlt: "Экран киоска выбытия",
          target: "#product-kiosk",
        },
        {
          id: "office",
          label: "Офис",
          line: "В кабинете все смены, обмен с 1С и выгрузки в Честный знак.",
          screenAlt: "Кабинет: сводка производства за день",
          target: "#product-office",
        },
      ],
      stripLabel: "Участки производства",
    },
    productSection: {
      cards: [
        {
          caption: "КИОСК",
          id: "kiosk",
          kicker: "ВЫБЫТИЕ · КИОСК",
          link: "Киоск самовыдачи",
          screenAlt: "Экран киоска выбытия",
          text: "Когда продукция уходит не через отгрузку (покупка сотрудником, образцы, бой), сотрудник сканирует на киоске бейдж и коды, а заявка приходит в кабинет.",
          title: "Выбытие оформляют на киоске.",
        },
        {
          caption: "КАБИНЕТ · СВЯЗЬ С ЧЕСТНЫМ ЗНАКОМ",
          id: "integrations",
          kicker: "ИНТЕГРАЦИИ",
          link: "Интеграция с 1С",
          screenAlt: "Кабинет: товар из Национального каталога и связь с Честным знаком",
          text: "Кабинет связан с Честным знаком, а с 1С обменивается заданиями и статусами. Данные не переносят вручную.",
          title: "Честный знак, 1С и API.",
        },
      ],
      heading: "Экраны, с которыми работают на смене.",
      kicker: "01 / ПРОДУКТ",
      rows: [
        {
          bullets: [
            "Повторные коды и чужой GTIN",
            "Несколько терминалов на одной линии",
            "Печать в ZPL и TSPL",
          ],
          caption: "СТАНЦИЯ · КОРОБ И ПАЛЛЕТА",
          id: "line",
          kicker: "ЛИНИЯ · СТАНЦИЯ",
          link: "Маркировка и агрегация",
          screenAlt: "Экран станции: короб, паллета и журнал смены",
          text: "Станция не пустит в короб повторный код, код чужого товара или код с ошибкой. Оператор видит причину на экране, а заполненный короб сразу получает этикетку с SSCC.",
          title: "Каждый код проверяем до короба.",
        },
        {
          bullets: [
            "Сборка и разборка паллет",
            "Инвентаризация у стеллажа",
            "Печать этикеток с терминала",
          ],
          caption: "ТСД НА ANDROID",
          id: "handheld",
          kicker: "СКЛАД · ТСД НА ANDROID",
          link: "Как это выглядит на складе",
          screenAlt: "Экран ТСД: сборка короба на терминале",
          text: "Кладовщик с терминалом на Android собирает паллеты, снимает с них коробы и проводит инвентаризацию у стеллажа. Операции уходят в тот же журнал, что и со станции.",
          title: "Паллеты собираем на ТСД.",
        },
        {
          bullets: [
            "Сводка смен и сигналы",
            "Выгрузки в Честный знак",
            "Товары из Национального каталога",
          ],
          caption: "КАБИНЕТ · СВОДКА СМЕН",
          id: "office",
          kicker: "ОФИС · КАБИНЕТ",
          link: "Инструкции для кабинета",
          screenAlt: "Кабинет: сводка производства за день",
          text: "Сюда приходят операции со станций, ТСД и киосков. Отсюда идёт обмен с 1С и выгрузка документов для Честного знака.",
          title: "В кабинете видно каждую смену.",
        },
      ],
    },
    offline: {
      caption: "СТАНЦИЯ БЕЗ СЕТИ",
      heading: ["Сеть может исчезнуть.", "Производство не должно."],
      imageAlt: "Макет завода на закате",
      kicker: "02 / БЕЗ СЕТИ",
      lead: "Станция пишет операции в свой журнал и отправляет их на сервер, когда связь вернётся. Если записи с разных станций не сошлись, это видно в разделе «Конфликты».",
      points: [
        ["Проверка на месте", "Коды проверяются на станции без ожидания сервера."],
        ["Операции сохраняются", "Каждое действие лежит в локальном журнале до отправки."],
        [
          "Линия продолжает работу",
          "Оператор видит, что происходит, и продолжает смену после сбоя.",
        ],
      ],
      screenAlt: "Экран станции без связи с сервером",
    },
    traceability: {
      caption: "СТАНЦИЯ · КОНФЛИКТЫ",
      heading: "У каждой ошибки есть история и следующий шаг.",
      kicker: "03 / ПРОСЛЕЖИВАЕМОСТЬ",
      lead: "Каждое действие остаётся в истории. Проблемную операцию можно понять, повторить или передать ответственному.",
      screenAlt: "Экран станции: список конфликтов",
    },
    filmBlock: {
      button: "Посмотреть, как это работает",
      heading: "Посмотрите, как код проходит через производство.",
      imageAlt: "Страница «Как работает»: глава про склад на макете завода",
      kicker: "04 / КАК ЭТО РАБОТАЕТ",
      lead: "Прокрутите страницу, и камера пройдёт по макету завода: линия, упаковка, склад, киоск и офис.",
    },
    rollout: {
      heading: "Для любой маркируемой продукции.",
      kicker: "05 / ВНЕДРЕНИЕ",
      labels: [
        {
          alt: "Этикетка короба для сока: товар, даты, GTIN и штрихкод SSCC",
          caption: "ЭТИКЕТКА КОРОБА · СОКИ",
          id: "juices",
        },
        {
          alt: "Этикетка короба для косметики: товар, даты, GTIN и штрихкод SSCC",
          caption: "ЭТИКЕТКА КОРОБА · КОСМЕТИКА",
          id: "cosmetics",
        },
      ],
      lead: "Коды, короба и паллеты устроены одинаково для соков и воды, молочной продукции, пива и косметики. Особенности вашей товарной группы сверяем до запуска.",
      steps: [
        [
          "Сверяем правила вашей товарной группы",
          "Фиксируем товарную группу, форм-фактор упаковки и правила учёта.",
        ],
        ["Разбираем линию", "Сопоставляем оборудование, роли и текущий маршрут кодов."],
        ["Запускаем один сценарий", "Настраиваем станцию под конкретный продукт и короб."],
        ["Проверяем на смене", "Работаем с оператором и проверяем восстановление после ошибок."],
      ],
    },
    documents: {
      allInstructions: "Все инструкции",
      covers: [
        {
          alt: "Первая страница инструкции MKR-INS-01",
          caption: "MKR-INS-01 · СТАНЦИЯ: ВХОД И СМЕНА",
          code: "mkr-ins-01",
        },
        {
          alt: "Первая страница инструкции MKR-INS-02",
          caption: "MKR-INS-02 · СТАНЦИЯ: РАБОТА НА ЛИНИИ",
          code: "mkr-ins-02",
        },
        {
          alt: "Первая страница инструкции MKR-INS-09",
          caption: "MKR-INS-09 · КАБИНЕТ: СВОДКА И ВЫГРУЗКИ",
          code: "mkr-ins-09",
        },
      ],
      heading: "Всё описано до покупки.",
      kicker: "06 / ОТКРЫТЫЕ ДОКУМЕНТЫ",
      lead: "Инструкции для станции и кабинета, договор и регламенты опубликованы на сайте. Их можно прочитать до разговора с нами.",
      legal: "Договор и регламенты",
    },
    hero: {
      filmLink: "Посмотреть, как это работает",
      heading: ["Маркировка и агрегация.", "Линия идёт."],
      imageAlt: "Оператор у конвейера линии розлива: бутылки с напитком движутся по ленте",
      kicker: "МАРКИРОВКА / АГРЕГАЦИЯ / ПРОСЛЕЖИВАЕМОСТЬ",
      lead: "Производственная система для пива, сидра и слабоалкогольных напитков: проверяем коды, собираем короба, печатаем этикетки и сохраняем операции при нестабильной сети.",
      note: "ДЛЯ ПРОИЗВОДСТВЕННЫХ ЛИНИЙ, КОТОРЫЕ НЕЛЬЗЯ ОСТАНАВЛИВАТЬ",
    },
    implementation: {
      heading: "Сейчас — пиво, сидр и слабоалкогольные напитки.",
      kicker: "06 / ТЕКУЩАЯ СПЕЦИАЛИЗАЦИЯ",
      lead: "Markiro сейчас ориентирован на производителей пива, сидра и другой продукции товарной группы «Пиво, напитки, изготавливаемые на основе пива, слабоалкогольные напитки». Принадлежность конкретного товара проверяется по ТН ВЭД ЕАЭС и ОКПД 2. Новые товарные группы добавляются поэтапно.",
      link: "Обсудить первую линию",
      steps: [
        [
          "Проверяем продукцию",
          "Фиксируем товарную группу, форм-фактор упаковки и действующие правила учёта.",
        ],
        ["Разбираем линию", "Сопоставляем оборудование, роли и текущий маршрут кодов."],
        ["Запускаем один сценарий", "Настраиваем рабочую станцию под конкретный продукт и короб."],
        [
          "Проверяем на смене",
          "Работаем вместе с оператором и проверяем восстановление после ошибок.",
        ],
      ],
    },
    materials: {
      allArticles: "Все статьи",
      allInstructions: "Инструкции для станции и кабинета",
      heading: ["Разборы с линии.", "Без общих обещаний."],
      kicker: "07 / МАТЕРИАЛЫ",
      lead: "Статьи о реальных задачах маркировки пива и печатные инструкции для операторов, наладчиков и менеджеров.",
    },
    lineConsole: {
      accepted: "Код принят",
      assembly: "СБОРКА",
      caseAssembly: "Сборка короба",
      codes: "КОДОВ МАРКИРОВКИ",
      illustrativeNote: "Иллюстрация интерфейса станции, значения условные.",
      lineActive: "ЛИНИЯ АКТИВНА",
      station: "СТАНЦИЯ 03 / АГРЕГАЦИЯ",
      shiftAccepted: "ПРИНЯТО ЗА СМЕНУ",
      timeValue: "52,40",
      timeUnit: "сек",
    },
    platform: {
      heading: ["Одна линия сегодня.", "Платформа завтра."],
      kicker: "05 / ПЛАТФОРМА",
      lead: "Подключайте новые контуры по готовности, не заменяя уже работающий процесс.",
      modules: [
        [
          "Кабинет производства",
          "Задания, шаблоны этикеток, история операций и управление площадкой.",
        ],
        ["Киоск выбытия", "Самообслуживание со сканером и восстановлением после разрыва связи."],
        ["1С и API", "Обмен заданиями и статусами без ручного переноса данных."],
      ],
    },
    product: {
      codeAccepted: "КОД ПРИНЯТ",
      codeCheck: "ПРОВЕРКА КОДА",
      firstDescription: "Оператор видит, прошёл продукт проверку или требует отдельного решения.",
      firstHeading: "Код проверяется сразу после сканирования",
      heading: ["Не очередной кабинет.", "Инструмент для линии."],
      kicker: "03 / ДВА РЕЖИМА",
      labelsReady: ["ЭТИКЕТКИ", "ГОТОВЫ"],
      lead: "Каждый экран отвечает на один вопрос оператора и не прячет состояние за таблицами.",
      productFound: "Продукт найден",
      productName: "Сидр яблочный 0,45 л",
      productNumber: "ПРОДУКТ 404123",
      secondDescription:
        "Предпросмотр и печать используют один макет. Оператор не сверяет поля на глаз.",
      secondHeading: "Этикетка строится из проверенных данных",
      verified: "ПРОВЕРЕНО",
    },
    trace: {
      benefits: ["Точное место сбоя", "История действий", "Понятный следующий шаг"],
      events: [
        ["14:21:03", "Код принят", "Марка связана с товаром", "ok"],
        ["14:21:08", "Короб закрыт", "24 единицы в группе", "ok"],
        ["14:21:12", "Этикетка отправлена на печать", "Принтер линии 02", "ok"],
        ["14:21:18", "Печать не подтвердилась", "Нужно действие оператора", "problem"],
      ],
      heading: ["Ошибка не исчезает.", "Она получает понятный маршрут."],
      kicker: "04 / ПРОСЛЕЖИВАЕМОСТЬ",
      lead: "Каждое действие остаётся в истории. Проблемную операцию можно понять, повторить или передать ответственному.",
      panelLabel: "Пример журнала событий",
      station: "СТАНЦИЯ 03",
      toolbar: "ИСТОРИЯ КОРОБА 24",
    },
  },
  hub: {
    articlesHeading: "Все статьи",
    articlesKicker: "01 / Практика",
    instructionsKicker: "Инструкции",
    minutes: "мин чтения",
    otherGroup: "Другие инструкции",
    registryLink: "публичном реестре документов",
    registryNote: "Коды, редакции, даты и PDF/A всех инструкций также опубликованы в",
  },
} as const;

const EN = {
  common: {
    breadcrumbsLabel: "Breadcrumbs",
    discussTask: "Discuss your workflow",
    footerLabel: "Footer links",
    homeLabel: "Markiro home page",
    menuClose: "Close menu",
    menuOpen: "Open menu",
    nav: {
      articles: "Articles",
      faq: "Questions",
      howItWorks: "How it works",
      instructions: "Instructions",
      product: "Product",
    },
    navigationLabel: "Primary navigation",
    faqKicker: "Questions on this topic",
    relatedArticlesHeading: "Related articles",
    relatedArticlesKicker: "Covered in depth",
    reviewedLabel: "Reviewed",
    summaryHeading: "In short",
    summaryKicker: "Summary",
    relatedHeading: "Related production workflows",
    relatedKicker: "Next step",
    requestDemo: "Request a demonstration",
    requestDemoShort: "Request a demo",
    seoCtaHeading: "Test the workflow with data from your line.",
    seoCtaKicker: "A demonstration using your process",
    skipLink: "Skip to content",
  },
  home: {
    continuity: {
      heading: ["The network may disappear.", "Production must not."],
      kicker: "01 / CONTINUITY",
      lead: "The station operates locally and synchronizes its operations when connectivity returns.",
      points: [
        [
          "Validate on the spot",
          "Codes are validated at the station without waiting for a server response.",
        ],
        [
          "Keep every operation",
          "Each action remains in the local journal until delivery is confirmed.",
        ],
        [
          "Keep the line moving",
          "Operators see the current state and can recover after a failure.",
        ],
      ],
    },
    cycle: {
      heading: ["CODE VERIFIED.", "CASE COMPLETE."],
      kicker: "02 / PRODUCTION CYCLE",
      lead: "The operator verifies the code on a bottle or can, assembles the case, and prints its SSCC label.",
      stages: [
        [
          "Code verification",
          "The system validates the code and stops invalid data at the operation boundary.",
        ],
        [
          "Pack aggregation",
          "Products become cases while each serialized code remains linked to the case SSCC.",
        ],
        ["Label and print", "The layout uses the same data that passed validation."],
      ],
    },
    demo: {
      company: "Company",
      contactNote: "A contact number will appear when the public phone line is connected.",
      email: "Email",
      heading: "See Markiro on your production line.",
      kicker: "08 / DEMO ON YOUR LINE",
      lead: "We will examine your process and demonstrate a working scenario instead of an abstract presentation.",
      legal: {
        consent: "personal-data consent",
        prefix: "I consent to the processing of my personal data under the",
        privacy: "personal-data processing policy",
        separator: "and confirm that I have read the",
      },
      name: "Your name",
      phone: "Contact phone (optional)",
      unavailable: "Online submission is temporarily unavailable.",
      unavailableContact: "Email us at",
    },
    mapHero: {
      filmLink: "See how it works",
      heading: ["Serialization and aggregation.", "Keep the line moving."],
      hint: "Hover a dot to see the screen used in that area",
      imageAlt:
        "Scale model of a plant: the hall with the line, packing and warehouse, the kiosk at the entrance, the office and the finished-goods store",
      kicker: "SERIALIZATION · AGGREGATION · TRACEABILITY",
      lead: "We verify codes, assemble cases and pallets, and print labels for juice, cosmetics, beer and dairy. When the network drops, the station keeps working.",
      spots: [
        {
          id: "line",
          label: "Line",
          line: "The station checks every code before it goes into a case.",
          screenAlt: "Station screen: case assembly and accepted codes in the shift log",
          target: "#product-line",
        },
        {
          id: "packing",
          label: "Packing",
          line: "When a case is full, the station prints an SSCC label.",
          screenAlt: "Station screen: a case and a pallet in progress",
          target: "#product-line",
        },
        {
          id: "warehouse",
          label: "Warehouse",
          line: "The handheld builds pallets and runs inventory.",
          screenAlt: "Handheld screen: case assembly on the terminal",
          target: "#product-handheld",
        },
        {
          id: "kiosk",
          label: "Kiosk",
          line: "Employee purchases, samples and breakage go through the kiosk.",
          screenAlt: "Disposal kiosk screen",
          target: "#product-kiosk",
        },
        {
          id: "office",
          label: "Office",
          line: "The admin panel holds every shift, the 1C exchange and Chestny ZNAK exports.",
          screenAlt: "Admin panel: today's production summary",
          target: "#product-office",
        },
      ],
      stripLabel: "Production areas",
    },
    productSection: {
      cards: [
        {
          caption: "KIOSK",
          id: "kiosk",
          kicker: "DISPOSAL · KIOSK",
          link: "Self-service kiosk",
          screenAlt: "Disposal kiosk screen",
          text: "When products leave other than by shipment (employee purchases, samples, breakage), the employee scans a badge and the codes at the kiosk, and the request arrives in the admin panel.",
          title: "Disposal goes through the kiosk.",
        },
        {
          caption: "ADMIN PANEL · CHESTNY ZNAK LINK",
          id: "integrations",
          kicker: "INTEGRATIONS",
          link: "1C integration",
          screenAlt: "Admin panel: a product from the National Catalogue and the Chestny ZNAK link",
          text: "The admin panel is linked to Chestny ZNAK and exchanges tasks and statuses with 1C, so nobody retypes data.",
          title: "Chestny ZNAK, 1C and an API.",
        },
      ],
      heading: "The screens people work with on shift.",
      kicker: "01 / PRODUCT",
      rows: [
        {
          bullets: [
            "Repeated codes and foreign GTINs",
            "Several terminals on one line",
            "Printing in ZPL and TSPL",
          ],
          caption: "STATION · CASE AND PALLET",
          id: "line",
          kicker: "LINE · STATION",
          link: "Serialization and aggregation",
          screenAlt: "Station screen: a case, a pallet and the shift log",
          text: "The station keeps repeated codes, codes of another product and malformed codes out of the case. The operator sees the reason on screen, and a full case gets its SSCC label at once.",
          title: "We check every code before it goes into a case.",
        },
        {
          bullets: [
            "Building and breaking pallets",
            "Inventory at the rack",
            "Label printing from the terminal",
          ],
          caption: "ANDROID HANDHELD",
          id: "handheld",
          kicker: "WAREHOUSE · ANDROID HANDHELD",
          link: "See it in the warehouse",
          screenAlt: "Handheld screen: case assembly on the terminal",
          text: "A warehouse worker with an Android handheld builds pallets, removes cases from them and runs inventory at the rack. Operations go into the same log as the station's.",
          title: "Pallets are built on the handheld.",
        },
        {
          bullets: [
            "Shift summary and alerts",
            "Exports to Chestny ZNAK",
            "Products from the National Catalogue",
          ],
          caption: "ADMIN PANEL · SHIFT SUMMARY",
          id: "office",
          kicker: "OFFICE · ADMIN PANEL",
          link: "Admin panel instructions",
          screenAlt: "Admin panel: today's production summary",
          text: "Operations from stations, handhelds and kiosks arrive here. From here you exchange data with 1C and export documents for Chestny ZNAK.",
          title: "Every shift is visible in the admin panel.",
        },
      ],
    },
    offline: {
      caption: "STATION WITHOUT A NETWORK",
      heading: ["The network may disappear.", "Production must not."],
      imageAlt: "Scale model of a plant at sunset",
      kicker: "02 / WITHOUT A NETWORK",
      lead: "The station writes operations to its own journal and sends them to the server when the connection returns. If records from different stations disagree, they show up under Conflicts.",
      points: [
        ["Checks on the spot", "Codes are verified on the station without waiting for the server."],
        ["Operations are kept", "Every action stays in the local journal until it is sent."],
        [
          "The line keeps running",
          "The operator sees what is happening and carries on after a failure.",
        ],
      ],
      screenAlt: "Station screen without a server connection",
    },
    traceability: {
      caption: "STATION · CONFLICTS",
      heading: "Every error has a history and a next step.",
      kicker: "03 / TRACEABILITY",
      lead: "Every action stays in the history. A failed operation can be understood, retried or handed to the right person.",
      screenAlt: "Station screen: the list of conflicts",
    },
    filmBlock: {
      button: "See how it works",
      heading: "See how a code travels through production.",
      imageAlt: "The How it works page: the warehouse chapter over the scale model",
      kicker: "04 / HOW IT WORKS",
      lead: "Scroll the page and the camera moves through a scale model of the plant: the line, packing, the warehouse, the kiosk and the office.",
    },
    rollout: {
      heading: "For any marked goods.",
      kicker: "05 / ROLLOUT",
      labels: [
        {
          alt: "Juice case label: product, dates, GTIN and SSCC barcode",
          caption: "CASE LABEL · JUICE",
          id: "juices",
        },
        {
          alt: "Cosmetics case label: product, dates, GTIN and SSCC barcode",
          caption: "CASE LABEL · COSMETICS",
          id: "cosmetics",
        },
      ],
      lead: "Codes, cases and pallets work the same way for juice and water, dairy, beer and cosmetics. We check the rules of your product group before launch.",
      steps: [
        [
          "We check the rules of your product group",
          "We record the product group, the packaging format and the accounting rules.",
        ],
        ["We walk the line", "We map the equipment, the roles and the current route of codes."],
        ["We launch one scenario", "We set up the station for a specific product and case."],
        ["We test it on shift", "We work with the operator and test recovery after errors."],
      ],
    },
    documents: {
      allInstructions: "All instructions",
      covers: [
        {
          alt: "First page of instruction MKR-INS-01",
          caption: "MKR-INS-01 · STATION: SIGN-IN AND SHIFT",
          code: "mkr-ins-01",
        },
        {
          alt: "First page of instruction MKR-INS-02",
          caption: "MKR-INS-02 · STATION: WORK ON THE LINE",
          code: "mkr-ins-02",
        },
        {
          alt: "First page of instruction MKR-INS-09",
          caption: "MKR-INS-09 · ADMIN PANEL: SUMMARY AND EXPORTS",
          code: "mkr-ins-09",
        },
      ],
      heading: "Everything is documented before you buy.",
      kicker: "06 / OPEN DOCUMENTS",
      lead: "Station and admin panel instructions, the agreement and the regulations are published on the site. You can read them before you talk to us.",
      legal: "Agreement and regulations",
    },
    hero: {
      filmLink: "See how it works",
      heading: ["Serialization and aggregation.", "Keep the line moving."],
      imageAlt: "An operator at a bottling line watching bottles move along the conveyor",
      kicker: "SERIALIZATION / AGGREGATION / TRACEABILITY",
      lead: "A production system for beer, cider and low-alcohol beverages: verify codes, aggregate cases, print labels, and retain operations through unstable connectivity.",
      note: "FOR PRODUCTION LINES THAT CANNOT AFFORD TO STOP",
    },
    implementation: {
      heading: "Currently focused on beer, cider and low-alcohol beverages.",
      kicker: "06 / CURRENT PRODUCT FOCUS",
      lead: "Markiro currently focuses on producers of beer, cider, and other products in the Chestny ZNAK product group “Beer, beverages made from beer and low-alcohol beverages”. Applicability to a specific product is checked against its TN VED EAEU and OKPD 2 codes. Additional product categories are being added gradually.",
      link: "Discuss the first line",
      steps: [
        [
          "Confirm the product",
          "Document the product group, packaging format, and applicable traceability rules.",
        ],
        ["Understand the line", "Map the equipment, roles, and current route of serialized codes."],
        ["Launch one workflow", "Configure the workstation for the actual product and case."],
        ["Validate during a shift", "Work with an operator and test recovery from real errors."],
      ],
    },
    materials: {
      allArticles: "All articles",
      allInstructions: "Station and cabinet instructions",
      heading: ["Notes from the line.", "No vague promises."],
      kicker: "07 / MATERIALS",
      lead: "Articles on real beer-marking problems and printable instructions for operators, technicians, and managers.",
    },
    lineConsole: {
      accepted: "Code accepted",
      assembly: "PACKING",
      caseAssembly: "Case assembly",
      codes: "SERIALIZED CODES",
      illustrativeNote: "Station interface illustration, values are illustrative.",
      lineActive: "LINE ACTIVE",
      station: "STATION 03 / AGGREGATION",
      shiftAccepted: "ACCEPTED THIS SHIFT",
      timeValue: "52.40",
      timeUnit: "sec",
    },
    platform: {
      heading: ["One line today.", "A platform tomorrow."],
      kicker: "05 / PLATFORM",
      lead: "Connect new production areas when they are ready without replacing an already working process.",
      modules: [
        ["Production office", "Orders, label templates, operation history, and site management."],
        ["Disposal kiosk", "Scanner-led self-service with recovery after a lost connection."],
        ["1C and API", "Exchange orders and statuses without transferring data manually."],
      ],
    },
    product: {
      codeAccepted: "CODE ACCEPTED",
      codeCheck: "CODE VERIFICATION",
      firstDescription:
        "The operator immediately sees whether the product passed validation or needs a separate decision.",
      firstHeading: "Validate the code immediately after scanning",
      heading: ["Not another back office.", "A tool for the line."],
      kicker: "03 / TWO OPERATING MODES",
      labelsReady: ["LABELS", "READY"],
      lead: "Each screen answers one operator question and never hides the current state behind tables.",
      productFound: "Product found",
      productName: "Apple cider 0.45 L",
      productNumber: "PRODUCT 404123",
      secondDescription:
        "Preview and print use one layout. The operator never has to compare fields by eye.",
      secondHeading: "Build labels from verified data",
      verified: "VERIFIED",
    },
    trace: {
      benefits: ["Exact failure location", "Complete action history", "A clear next step"],
      events: [
        ["14:21:03", "Code accepted", "Serialized code linked to product", "ok"],
        ["14:21:08", "Case closed", "24 items in the group", "ok"],
        ["14:21:12", "Label sent to print", "Line printer 02", "ok"],
        ["14:21:18", "Print not confirmed", "Operator action required", "problem"],
      ],
      heading: ["An error does not disappear.", "It gets a clear recovery path."],
      kicker: "04 / TRACEABILITY",
      lead: "Every action stays in the history. A failed operation can be understood, retried safely, or assigned to the right person.",
      panelLabel: "Example event log",
      station: "STATION 03",
      toolbar: "CASE 24 HISTORY",
    },
  },
  hub: {
    articlesHeading: "All articles",
    articlesKicker: "01 / Practice",
    instructionsKicker: "Instructions",
    minutes: "min read",
    otherGroup: "Other instructions",
    registryLink: "public document registry",
    registryNote:
      "Codes, revisions, dates and PDF/A files of every instruction are also published in the",
  },
} as const;

export function getUiCopy(locale: Locale): typeof RU | typeof EN {
  return locale === "ru" ? RU : EN;
}
