-- Force-overwrites the spec of every label template carrying one of the five
-- stock seed names, in EVERY tenant.
--
-- Migration 0049 seeded these five templates as rows, so a later change to
-- `buildDefaultLabelTemplates()` in @markiro/domain reaches new tenants only —
-- the rows already in production keep whatever JSON 0049 inlined. The first
-- physical print of the 58×40 box label produced three corrections (dates as
-- дд.мм.гггг rather than ISO, the SSCC barcode centred/wider/taller, and a
-- third line for the product name), and the product owner chose, from the
-- options presented, to force-overwrite all five rather than seed the changes
-- to new tenants only.
--
-- THIS DISCARDS MANUAL EDITS made to any template with one of these names, in
-- any tenant. That is the accepted, explicitly chosen trade-off: a name match
-- is treated as "this is the stock template", which is the same idempotency
-- key 0049 used to decide not to seed a duplicate.
--
-- The JSON below is GENERATED, never hand-edited — see the plan's Task 4
-- Step 2 recipe. `packages/domain/test/labels-defaults.test.ts` parses this
-- file and deep-compares it against `buildDefaultLabelTemplates()`, so the two
-- cannot drift; 0049's own inlined JSON is historical and is deliberately NOT
-- kept in step.
UPDATE label_templates AS lt
SET spec = t.spec::jsonb,
    updated_at = now()
FROM (VALUES
  ('Коробка 58×40 (203 dpi)', '{"widthMm":58,"heightMm":40,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.name","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-date","xMm":2,"yMm":18.8,"text":"Дата производства:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-expiry","xMm":20,"yMm":18.8,"text":"Годен до:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-qty","xMm":38,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-date","xMm":2,"yMm":21.6,"field":"date","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-expiry","xMm":20,"yMm":21.6,"field":"expiry","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":38,"yMm":21.6,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"line","id":"sep2","xMm":2,"yMm":26.2,"x2Mm":56,"y2Mm":26.2,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":26.8,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":26.8,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":31.4,"x2Mm":56,"y2Mm":31.4,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.5,"yMm":32,"format":"code128","data":"sscc","sizeMm":4.8,"moduleWidthMm":0.2502},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"maxWidthMm":54}]}'),
  ('Коробка 58×40 (300 dpi)', '{"widthMm":58,"heightMm":40,"dpi":300,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.name","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-date","xMm":2,"yMm":18.8,"text":"Дата производства:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-expiry","xMm":20,"yMm":18.8,"text":"Годен до:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-qty","xMm":38,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-date","xMm":2,"yMm":21.6,"field":"date","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-expiry","xMm":20,"yMm":21.6,"field":"expiry","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":38,"yMm":21.6,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"line","id":"sep2","xMm":2,"yMm":26.2,"x2Mm":56,"y2Mm":26.2,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":26.8,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":26.8,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":31.4,"x2Mm":56,"y2Mm":31.4,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.2,"yMm":32,"format":"code128","data":"sscc","sizeMm":4.8,"moduleWidthMm":0.254},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"maxWidthMm":54}]}'),
  ('Коробка 75×120 (203 dpi)', '{"widthMm":75,"heightMm":120,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2.6,"yMm":2.6,"field":"product.name","fontSizePt":13,"bold":true,"maxWidthMm":69.8,"maxLines":3},{"kind":"line","id":"sep1","xMm":2.6,"yMm":23.7,"x2Mm":72.4,"y2Mm":23.7,"thicknessMm":0.4},{"kind":"text","id":"cap-date","xMm":2.6,"yMm":24.5,"text":"Дата производства:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"text","id":"cap-expiry","xMm":25.9,"yMm":24.5,"text":"Годен до:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"text","id":"cap-qty","xMm":49.2,"yMm":24.5,"text":"Кол-во в упаковке:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-date","xMm":2.6,"yMm":27.9,"field":"date","fontSizePt":10,"bold":true,"maxWidthMm":23.3},{"kind":"field","id":"val-expiry","xMm":25.9,"yMm":27.9,"field":"expiry","fontSizePt":10,"bold":true,"maxWidthMm":23.3},{"kind":"field","id":"val-qty","xMm":49.2,"yMm":27.9,"field":"qty","fontSizePt":10,"bold":true,"maxWidthMm":23.3},{"kind":"line","id":"sep2","xMm":2.6,"yMm":33.6,"x2Mm":72.4,"y2Mm":33.6,"thicknessMm":0.4},{"kind":"text","id":"cap-egais","xMm":2.6,"yMm":34.4,"text":"Код ЕГАИС:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-egais","xMm":25.9,"yMm":34.4,"field":"product.egais","fontSizePt":10,"bold":true,"maxWidthMm":46.5},{"kind":"line","id":"sep3","xMm":2.6,"yMm":40.1,"x2Mm":72.4,"y2Mm":40.1,"thicknessMm":0.4},{"kind":"barcode","id":"bc-sscc","xMm":8.2,"yMm":40.9,"format":"code128","data":"sscc","sizeMm":6.9,"moduleWidthMm":0.3754},{"kind":"field","id":"val-sscc","xMm":2.6,"yMm":48.1,"field":"sscc","fontSizePt":6,"maxWidthMm":69.8}]}'),
  ('Коробка 100×100 (203 dpi)', '{"widthMm":100,"heightMm":100,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.name","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-date","xMm":3.4,"yMm":32.1,"text":"Дата производства:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"text","id":"cap-expiry","xMm":34.5,"yMm":32.1,"text":"Годен до:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"text","id":"cap-qty","xMm":65.6,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"field","id":"val-date","xMm":3.4,"yMm":37.2,"field":"date","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-expiry","xMm":34.5,"yMm":37.2,"field":"expiry","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":65.6,"yMm":37.2,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":45.2,"x2Mm":96.6,"y2Mm":45.2,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":46.3,"text":"Код ЕГАИС:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":46.3,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":54.3,"x2Mm":96.6,"y2Mm":54.3,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":55.4,"format":"code128","data":"sscc","sizeMm":7.8,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":63.6,"field":"sscc","fontSizePt":9,"maxWidthMm":93.2}]}'),
  ('Коробка 100×150 (203 dpi)', '{"widthMm":100,"heightMm":150,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.name","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-date","xMm":3.4,"yMm":32.1,"text":"Дата производства:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"text","id":"cap-expiry","xMm":34.5,"yMm":32.1,"text":"Годен до:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"text","id":"cap-qty","xMm":65.6,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"field","id":"val-date","xMm":3.4,"yMm":37.2,"field":"date","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-expiry","xMm":34.5,"yMm":37.2,"field":"expiry","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":65.6,"yMm":37.2,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":45.2,"x2Mm":96.6,"y2Mm":45.2,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":46.3,"text":"Код ЕГАИС:","fontSizePt":9,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":46.3,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":54.3,"x2Mm":96.6,"y2Mm":54.3,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":55.4,"format":"code128","data":"sscc","sizeMm":7.8,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":63.6,"field":"sscc","fontSizePt":9,"maxWidthMm":93.2}]}')
) AS t(name, spec)
WHERE lt.name = t.name;
