-- Seeds the FIVE DATE-FREE stock box labels — «Коробка … без дат …» — for
-- every existing organization. They are the second stock family: the same
-- design at the same five sizes, minus «Дата производства» and «Годен до»,
-- with the vertical space those two columns used to occupy given to the SSCC
-- bars (7.6 mm instead of 4.8 mm on the 58×40).
--
-- INSERT-IF-ABSENT, keyed on (tenant_id, name) — the pattern of
-- 0049_default_label_templates.sql, deliberately NOT the force-overwrite of
-- 0050/0052. These five names have never existed in any database, so there is
-- nothing of a tenant's to overwrite: a row can only be missing, never stale.
-- The `WHERE NOT EXISTS` guard therefore does two jobs — it makes the
-- migration idempotent, and it means a tenant who has already created a
-- template under one of these names keeps theirs untouched.
--
-- NOTHING EXISTING IS MODIFIED. The dated five are not re-seeded, not
-- re-specced and not re-pointed; `org_profiles.default_box_label_template_id`
-- is not touched, so every tenant's default box label stays whatever it was.
--
-- The spec jsonb below is GENERATED from `buildDateFreeBoxLabelTemplates()`
-- in `packages/domain/src/labels/defaults.ts`, not hand-written; the drift
-- guard in `packages/domain/test/labels-defaults.test.ts` re-parses this file
-- and deep-compares it against that builder, so the two cannot diverge.

INSERT INTO label_templates (tenant_id, name, spec)
SELECT o.id, t.name, t.spec::jsonb
FROM organization o
CROSS JOIN (VALUES
  ('Коробка 58×40 без дат (203 dpi)', '{"widthMm":58,"heightMm":40,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.name","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-qty","xMm":2,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":20,"yMm":18.8,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep2","xMm":2,"yMm":23.4,"x2Mm":56,"y2Mm":23.4,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":24,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":24,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":28.6,"x2Mm":56,"y2Mm":28.6,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.5,"yMm":29.2,"format":"code128","data":"sscc","sizeMm":7.6,"moduleWidthMm":0.2502},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"align":"center","maxWidthMm":54}]}'),
  ('Коробка 58×40 без дат (300 dpi)', '{"widthMm":58,"heightMm":40,"dpi":300,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.name","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-qty","xMm":2,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":20,"yMm":18.8,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep2","xMm":2,"yMm":23.4,"x2Mm":56,"y2Mm":23.4,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":24,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":24,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":28.6,"x2Mm":56,"y2Mm":28.6,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.2,"yMm":29.2,"format":"code128","data":"sscc","sizeMm":7.6,"moduleWidthMm":0.254},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"align":"center","maxWidthMm":54}]}'),
  ('Коробка 75×120 без дат (203 dpi)', '{"widthMm":75,"heightMm":120,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2.6,"yMm":2.6,"field":"product.name","fontSizePt":13,"bold":true,"maxWidthMm":69.8,"maxLines":3},{"kind":"line","id":"sep1","xMm":2.6,"yMm":23.7,"x2Mm":72.4,"y2Mm":23.7,"thicknessMm":0.4},{"kind":"text","id":"cap-qty","xMm":2.6,"yMm":24.5,"text":"Кол-во в упаковке:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-qty","xMm":25.9,"yMm":24.5,"field":"qty","fontSizePt":10,"bold":true,"maxWidthMm":46.5},{"kind":"line","id":"sep2","xMm":2.6,"yMm":30.2,"x2Mm":72.4,"y2Mm":30.2,"thicknessMm":0.4},{"kind":"text","id":"cap-egais","xMm":2.6,"yMm":31,"text":"Код ЕГАИС:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-egais","xMm":25.9,"yMm":31,"field":"product.egais","fontSizePt":10,"bold":true,"maxWidthMm":46.5},{"kind":"line","id":"sep3","xMm":2.6,"yMm":36.7,"x2Mm":72.4,"y2Mm":36.7,"thicknessMm":0.4},{"kind":"barcode","id":"bc-sscc","xMm":8.2,"yMm":37.5,"format":"code128","data":"sscc","sizeMm":10.3,"moduleWidthMm":0.3754},{"kind":"field","id":"val-sscc","xMm":2.6,"yMm":48.1,"field":"sscc","fontSizePt":6,"align":"center","maxWidthMm":69.8}]}'),
  ('Коробка 100×100 без дат (203 dpi)', '{"widthMm":100,"heightMm":100,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.name","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-qty","xMm":3.4,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":34.5,"yMm":32.1,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":40.1,"x2Mm":96.6,"y2Mm":40.1,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":41.2,"text":"Код ЕГАИС:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":41.2,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":49.2,"x2Mm":96.6,"y2Mm":49.2,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":50.3,"format":"code128","data":"sscc","sizeMm":13.5,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":64.2,"field":"sscc","fontSizePt":8,"align":"center","maxWidthMm":93.2}]}'),
  ('Коробка 100×150 без дат (203 dpi)', '{"widthMm":100,"heightMm":150,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.name","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-qty","xMm":3.4,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":34.5,"yMm":32.1,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":40.1,"x2Mm":96.6,"y2Mm":40.1,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":41.2,"text":"Код ЕГАИС:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":41.2,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":49.2,"x2Mm":96.6,"y2Mm":49.2,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":50.3,"format":"code128","data":"sscc","sizeMm":13.5,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":64.2,"field":"sscc","fontSizePt":8,"align":"center","maxWidthMm":93.2}]}')
) AS t(name, spec)
WHERE NOT EXISTS (
  SELECT 1 FROM label_templates lt
  WHERE lt.tenant_id = o.id AND lt.name = t.name
);
