-- Seeds the TEN print-name stock box labels — «Коробка … [Назв. для печати]»
-- — for every existing organization: both families (dated and date-free) at
-- the same five sizes, with the headline bound to product.printName instead
-- of product.name. The station substitutes the full product name when a
-- product has no print name, so these templates never print a blank headline.
--
-- INSERT-IF-ABSENT, keyed on (tenant_id, name) — the pattern of
-- 0049/0053, deliberately NOT the force-overwrite of 0050/0052/0056. These
-- ten names have never existed in any database, so a row can only be
-- missing, never stale; the WHERE NOT EXISTS guard makes the migration
-- idempotent and keeps any same-named tenant-created template untouched.
--
-- The inlined jsonb is GENERATED from buildPrintNameBoxLabelTemplates() in
-- packages/domain/src/labels/defaults.ts and pinned by the drift guard in
-- packages/domain/test/labels-defaults.test.ts.
INSERT INTO label_templates (tenant_id, name, spec)
SELECT o.id, t.name, t.spec::jsonb
FROM organization o
CROSS JOIN (VALUES
  ('Коробка 58×40 (203 dpi) [Назв. для печати]', '{"widthMm":58,"heightMm":40,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.printName","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-date","xMm":2,"yMm":18.8,"text":"Дата производства:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-expiry","xMm":20,"yMm":18.8,"text":"Годен до:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-qty","xMm":38,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-date","xMm":2,"yMm":21.6,"field":"date","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-expiry","xMm":20,"yMm":21.6,"field":"expiry","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":38,"yMm":20.9,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"line","id":"sep2","xMm":2,"yMm":26.2,"x2Mm":56,"y2Mm":26.2,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":26.8,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":26.8,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":31.4,"x2Mm":56,"y2Mm":31.4,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.5,"yMm":32,"format":"code128","data":"sscc","sizeMm":4.8,"moduleWidthMm":0.2502},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"align":"center","maxWidthMm":54}]}'),
  ('Коробка 58×40 (300 dpi) [Назв. для печати]', '{"widthMm":58,"heightMm":40,"dpi":300,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.printName","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-date","xMm":2,"yMm":18.8,"text":"Дата производства:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-expiry","xMm":20,"yMm":18.8,"text":"Годен до:","fontSizePt":5,"maxWidthMm":18},{"kind":"text","id":"cap-qty","xMm":38,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-date","xMm":2,"yMm":21.6,"field":"date","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-expiry","xMm":20,"yMm":21.6,"field":"expiry","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":38,"yMm":20.9,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":18},{"kind":"line","id":"sep2","xMm":2,"yMm":26.2,"x2Mm":56,"y2Mm":26.2,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":26.8,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":26.8,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":31.4,"x2Mm":56,"y2Mm":31.4,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.2,"yMm":32,"format":"code128","data":"sscc","sizeMm":4.8,"moduleWidthMm":0.254},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"align":"center","maxWidthMm":54}]}'),
  ('Коробка 75×120 (203 dpi) [Назв. для печати]', '{"widthMm":75,"heightMm":120,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2.6,"yMm":2.6,"field":"product.printName","fontSizePt":13,"bold":true,"maxWidthMm":69.8,"maxLines":3},{"kind":"line","id":"sep1","xMm":2.6,"yMm":23.7,"x2Mm":72.4,"y2Mm":23.7,"thicknessMm":0.4},{"kind":"text","id":"cap-date","xMm":2.6,"yMm":24.5,"text":"Дата производства:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"text","id":"cap-expiry","xMm":25.9,"yMm":24.5,"text":"Годен до:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"text","id":"cap-qty","xMm":49.2,"yMm":24.5,"text":"Кол-во в упаковке:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-date","xMm":2.6,"yMm":27.9,"field":"date","fontSizePt":10,"bold":true,"maxWidthMm":23.3},{"kind":"field","id":"val-expiry","xMm":25.9,"yMm":27.9,"field":"expiry","fontSizePt":10,"bold":true,"maxWidthMm":23.3},{"kind":"field","id":"val-qty","xMm":49.2,"yMm":27,"field":"qty","fontSizePt":10,"bold":true,"maxWidthMm":23.3},{"kind":"line","id":"sep2","xMm":2.6,"yMm":33.6,"x2Mm":72.4,"y2Mm":33.6,"thicknessMm":0.4},{"kind":"text","id":"cap-egais","xMm":2.6,"yMm":34.4,"text":"Код ЕГАИС:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-egais","xMm":25.9,"yMm":34.4,"field":"product.egais","fontSizePt":10,"bold":true,"maxWidthMm":46.5},{"kind":"line","id":"sep3","xMm":2.6,"yMm":40.1,"x2Mm":72.4,"y2Mm":40.1,"thicknessMm":0.4},{"kind":"barcode","id":"bc-sscc","xMm":8.2,"yMm":40.9,"format":"code128","data":"sscc","sizeMm":6.9,"moduleWidthMm":0.3754},{"kind":"field","id":"val-sscc","xMm":2.6,"yMm":48.1,"field":"sscc","fontSizePt":6,"align":"center","maxWidthMm":69.8}]}'),
  ('Коробка 100×100 (203 dpi) [Назв. для печати]', '{"widthMm":100,"heightMm":100,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.printName","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-date","xMm":3.4,"yMm":32.1,"text":"Дата производства:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"text","id":"cap-expiry","xMm":34.5,"yMm":32.1,"text":"Годен до:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"text","id":"cap-qty","xMm":65.6,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-date","xMm":3.4,"yMm":36.6,"field":"date","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-expiry","xMm":34.5,"yMm":36.6,"field":"expiry","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":65.6,"yMm":35.4,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":44.6,"x2Mm":96.6,"y2Mm":44.6,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":45.7,"text":"Код ЕГАИС:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":45.7,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":53.7,"x2Mm":96.6,"y2Mm":53.7,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":54.8,"format":"code128","data":"sscc","sizeMm":9,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":64.2,"field":"sscc","fontSizePt":8,"align":"center","maxWidthMm":93.2}]}'),
  ('Коробка 100×150 (203 dpi) [Назв. для печати]', '{"widthMm":100,"heightMm":150,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.printName","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-date","xMm":3.4,"yMm":32.1,"text":"Дата производства:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"text","id":"cap-expiry","xMm":34.5,"yMm":32.1,"text":"Годен до:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"text","id":"cap-qty","xMm":65.6,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-date","xMm":3.4,"yMm":36.6,"field":"date","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-expiry","xMm":34.5,"yMm":36.6,"field":"expiry","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":65.6,"yMm":35.4,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":31.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":44.6,"x2Mm":96.6,"y2Mm":44.6,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":45.7,"text":"Код ЕГАИС:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":45.7,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":53.7,"x2Mm":96.6,"y2Mm":53.7,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":54.8,"format":"code128","data":"sscc","sizeMm":9,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":64.2,"field":"sscc","fontSizePt":8,"align":"center","maxWidthMm":93.2}]}'),
  ('Коробка 58×40 без дат (203 dpi) [Назв. для печати]', '{"widthMm":58,"heightMm":40,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.printName","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-qty","xMm":2,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":20,"yMm":18.8,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep2","xMm":2,"yMm":23.4,"x2Mm":56,"y2Mm":23.4,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":24,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":24,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":28.6,"x2Mm":56,"y2Mm":28.6,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.5,"yMm":29.2,"format":"code128","data":"sscc","sizeMm":7.6,"moduleWidthMm":0.2502},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"align":"center","maxWidthMm":54}]}'),
  ('Коробка 58×40 без дат (300 dpi) [Назв. для печати]', '{"widthMm":58,"heightMm":40,"dpi":300,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2,"yMm":2,"field":"product.printName","fontSizePt":10,"bold":true,"maxWidthMm":54,"maxLines":3},{"kind":"line","id":"sep1","xMm":2,"yMm":18.2,"x2Mm":56,"y2Mm":18.2,"thicknessMm":0.3},{"kind":"text","id":"cap-qty","xMm":2,"yMm":18.8,"text":"Кол-во в упаковке:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-qty","xMm":20,"yMm":18.8,"field":"qty","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep2","xMm":2,"yMm":23.4,"x2Mm":56,"y2Mm":23.4,"thicknessMm":0.3},{"kind":"text","id":"cap-egais","xMm":2,"yMm":24,"text":"Код ЕГАИС:","fontSizePt":5,"maxWidthMm":18},{"kind":"field","id":"val-egais","xMm":20,"yMm":24,"field":"product.egais","fontSizePt":8,"bold":true,"maxWidthMm":36},{"kind":"line","id":"sep3","xMm":2,"yMm":28.6,"x2Mm":56,"y2Mm":28.6,"thicknessMm":0.3},{"kind":"barcode","id":"bc-sscc","xMm":9.2,"yMm":29.2,"format":"code128","data":"sscc","sizeMm":7.6,"moduleWidthMm":0.254},{"kind":"field","id":"val-sscc","xMm":2,"yMm":37,"field":"sscc","fontSizePt":5,"align":"center","maxWidthMm":54}]}'),
  ('Коробка 75×120 без дат (203 dpi) [Назв. для печати]', '{"widthMm":75,"heightMm":120,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":2.6,"yMm":2.6,"field":"product.printName","fontSizePt":13,"bold":true,"maxWidthMm":69.8,"maxLines":3},{"kind":"line","id":"sep1","xMm":2.6,"yMm":23.7,"x2Mm":72.4,"y2Mm":23.7,"thicknessMm":0.4},{"kind":"text","id":"cap-qty","xMm":2.6,"yMm":24.5,"text":"Кол-во в упаковке:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-qty","xMm":25.9,"yMm":24.5,"field":"qty","fontSizePt":10,"bold":true,"maxWidthMm":46.5},{"kind":"line","id":"sep2","xMm":2.6,"yMm":30.2,"x2Mm":72.4,"y2Mm":30.2,"thicknessMm":0.4},{"kind":"text","id":"cap-egais","xMm":2.6,"yMm":31,"text":"Код ЕГАИС:","fontSizePt":6,"maxWidthMm":23.3},{"kind":"field","id":"val-egais","xMm":25.9,"yMm":31,"field":"product.egais","fontSizePt":10,"bold":true,"maxWidthMm":46.5},{"kind":"line","id":"sep3","xMm":2.6,"yMm":36.7,"x2Mm":72.4,"y2Mm":36.7,"thicknessMm":0.4},{"kind":"barcode","id":"bc-sscc","xMm":8.2,"yMm":37.5,"format":"code128","data":"sscc","sizeMm":10.3,"moduleWidthMm":0.3754},{"kind":"field","id":"val-sscc","xMm":2.6,"yMm":48.1,"field":"sscc","fontSizePt":6,"align":"center","maxWidthMm":69.8}]}'),
  ('Коробка 100×100 без дат (203 dpi) [Назв. для печати]', '{"widthMm":100,"heightMm":100,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.printName","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-qty","xMm":3.4,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":34.5,"yMm":32.1,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":40.1,"x2Mm":96.6,"y2Mm":40.1,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":41.2,"text":"Код ЕГАИС:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":41.2,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":49.2,"x2Mm":96.6,"y2Mm":49.2,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":50.3,"format":"code128","data":"sscc","sizeMm":13.5,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":64.2,"field":"sscc","fontSizePt":8,"align":"center","maxWidthMm":93.2}]}'),
  ('Коробка 100×150 без дат (203 dpi) [Назв. для печати]', '{"widthMm":100,"heightMm":150,"dpi":203,"language":"zpl","elements":[{"kind":"field","id":"name","xMm":3.4,"yMm":3.4,"field":"product.printName","fontSizePt":17,"bold":true,"maxWidthMm":93.2,"maxLines":3},{"kind":"line","id":"sep1","xMm":3.4,"yMm":31,"x2Mm":96.6,"y2Mm":31,"thicknessMm":0.5},{"kind":"text","id":"cap-qty","xMm":3.4,"yMm":32.1,"text":"Кол-во в упаковке:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-qty","xMm":34.5,"yMm":32.1,"field":"qty","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep2","xMm":3.4,"yMm":40.1,"x2Mm":96.6,"y2Mm":40.1,"thicknessMm":0.5},{"kind":"text","id":"cap-egais","xMm":3.4,"yMm":41.2,"text":"Код ЕГАИС:","fontSizePt":8,"maxWidthMm":31.1},{"kind":"field","id":"val-egais","xMm":34.5,"yMm":41.2,"field":"product.egais","fontSizePt":14,"bold":true,"maxWidthMm":62.1},{"kind":"line","id":"sep3","xMm":3.4,"yMm":49.2,"x2Mm":96.6,"y2Mm":49.2,"thicknessMm":0.5},{"kind":"barcode","id":"bc-sscc","xMm":11,"yMm":50.3,"format":"code128","data":"sscc","sizeMm":13.5,"moduleWidthMm":0.5005},{"kind":"field","id":"val-sscc","xMm":3.4,"yMm":64.2,"field":"sscc","fontSizePt":8,"align":"center","maxWidthMm":93.2}]}')
) AS t(name, spec)
WHERE NOT EXISTS (
  SELECT 1 FROM label_templates lt
  WHERE lt.tenant_id = o.id AND lt.name = t.name
);
