CREATE TABLE "chz_product_groups" (
	"code" integer PRIMARY KEY NOT NULL,
	"alias" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "chz_product_groups_alias_uq" UNIQUE("alias")
);
--> statement-breakpoint
INSERT INTO "chz_product_groups" ("code", "alias", "name") VALUES
  (1, 'lp', 'Лёгкая промышленность'),
  (2, 'shoes', 'Обувные товары'),
  (3, 'tobacco', 'Табачная продукция'),
  (4, 'perfumery', 'Духи и туалетная вода'),
  (5, 'tires', 'Шины и покрышки пневматические резиновые новые'),
  (6, 'electronics', 'Фотокамеры (кроме кинокамер), фотовспышки и лампы-вспышки'),
  (7, 'pharma', 'Лекарственные препараты для медицинского применения'),
  (8, 'milk', 'Молочная продукция'),
  (9, 'bicycle', 'Велосипеды и велосипедные рамы'),
  (10, 'wheelchairs', 'Медицинские изделия'),
  (11, 'alcohol', 'Алкоголь'),
  (12, 'otp', 'Альтернативная табачная продукция'),
  (13, 'water', 'Упакованная вода'),
  (14, 'furs', 'Товары из натурального меха'),
  (15, 'beer', 'Пиво, напитки, изготавливаемые на основе пива, слабоалкогольные напитки'),
  (16, 'ncp', 'Никотиносодержащая продукция'),
  (17, 'bio', 'Специализированная пищевая продукция и БАД к пище'),
  (19, 'antiseptic', 'Антисептики и дезинфицирующие средства'),
  (20, 'petfood', 'Корма для животных'),
  (21, 'seafood', 'Морепродукты'),
  (22, 'nabeer', 'Безалкогольное пиво'),
  (23, 'softdrinks', 'Соковая продукция и безалкогольные напитки'),
  (25, 'meat', 'Мясные изделия'),
  (26, 'vetpharma', 'Ветеринарные препараты'),
  (27, 'toys', 'Игры и игрушки для детей'),
  (28, 'radio', 'Радиоэлектронная продукция'),
  (31, 'titan', 'Титановая металлопродукция'),
  (32, 'conserve', 'Консервированная продукция'),
  (33, 'vegetableoil', 'Растительные масла'),
  (34, 'opticfiber', 'Оптоволокно и оптоволоконная продукция'),
  (35, 'chemistry', 'Косметика, бытовая химия и товары личной гигиены'),
  (36, 'books', 'Печатная продукция'),
  (37, 'grocery', 'Бакалейная продукция'),
  (38, 'pharmaraw', 'Фармацевтическое сырьё, лекарственные средства'),
  (39, 'construction', 'Строительные материалы'),
  (40, 'fire', 'Пожарная безопасность'),
  (41, 'heater', 'Отопительные приборы'),
  (42, 'cableraw', 'Кабельно-проводниковая продукция'),
  (43, 'autofluids', 'Моторные масла'),
  (44, 'polymer', 'Полимерные трубы'),
  (45, 'sweets', 'Сладости и кондитерские изделия'),
  (48, 'carparts', 'Автозапчасти и комплектующие транспортных средств'),
  (49, 'furslp', 'Натуральный мех'),
  (50, 'nicotindev', 'Радиоэлектронная продукция. Электронные системы доставки никотина'),
  (51, 'gadgets', 'Радиоэлектронная продукция. Ноутбуки и смартфоны'),
  (52, 'frozen', 'Полуфабрикаты и замороженные продукты'),
  (53, 'fertilizers', 'Удобрения в потребительской упаковке'),
  (54, 'homeware', 'Товары для дома и интерьера'),
  (55, 'vetbio', 'Кормовые добавки'),
  (57, 'industrial', 'Промышленное оборудование'),
  (59, 'pyrotechnics', 'Пиротехнические изделия')
ON CONFLICT ("code") DO NOTHING;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "chz_product_group_code" integer;--> statement-breakpoint
UPDATE "products" SET "status" = 'draft' WHERE "chz_product_group_code" IS NULL;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_chz_product_group_code_chz_product_groups_code_fk" FOREIGN KEY ("chz_product_group_code") REFERENCES "public"."chz_product_groups"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" DROP COLUMN "product_group";