CREATE TABLE "org_pallet_sheet_template_defaults" (
	"tenant_id" text NOT NULL,
	"chz_product_group_code" integer NOT NULL,
	"template_id" uuid NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "org_pallet_sheet_template_defaults_tenant_id_chz_product_group_code_pk" PRIMARY KEY("tenant_id","chz_product_group_code")
);
--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "pallet_sheet_template_id" uuid;--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "pallet_sheet_template_snapshot" jsonb;--> statement-breakpoint
ALTER TABLE "org_profiles" ADD COLUMN "default_pallet_sheet_template_id" uuid;--> statement-breakpoint
ALTER TABLE "label_templates" ADD COLUMN "format" text DEFAULT 'label_v1' NOT NULL;--> statement-breakpoint
ALTER TABLE "label_templates" ADD COLUMN "revision" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "label_templates" ADD COLUMN "seed_key" text;--> statement-breakpoint
ALTER TABLE "org_pallet_sheet_template_defaults" ADD CONSTRAINT "org_pallet_sheet_template_defaults_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "org_pallet_sheet_template_defaults" ADD CONSTRAINT "org_pallet_sheet_template_defaults_chz_product_group_code_chz_product_groups_code_fk" FOREIGN KEY ("chz_product_group_code") REFERENCES "public"."chz_product_groups"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "org_pallet_sheet_template_defaults" ADD CONSTRAINT "org_pallet_sheet_template_defaults_template_tenant_fk" FOREIGN KEY ("tenant_id","template_id") REFERENCES "public"."label_templates"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_tenant_pallet_sheet_template_fk" FOREIGN KEY ("tenant_id","pallet_sheet_template_id") REFERENCES "public"."label_templates"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "org_profiles" ADD CONSTRAINT "org_profiles_pallet_sheet_template_tenant_fk" FOREIGN KEY ("tenant_id","default_pallet_sheet_template_id") REFERENCES "public"."label_templates"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_tenant_seed_key_uq" UNIQUE("tenant_id","seed_key");--> statement-breakpoint
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_format_check" CHECK ("label_templates"."format" IN ('label_v1', 'pallet_sheet_v2'));--> statement-breakpoint
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_revision_check" CHECK ("label_templates"."revision" >= 1);--> statement-breakpoint
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_sheet_purpose_check" CHECK ("label_templates"."format" <> 'pallet_sheet_v2' OR ("label_templates"."purpose" = 'pallet' AND "label_templates"."spec"->>'schemaVersion' = '2' AND "label_templates"."spec"->>'kind' = 'pallet_sheet'));
--> statement-breakpoint
INSERT INTO label_templates(tenant_id,name,purpose,format,seed_key,spec)
SELECT o.id, p.name, 'pallet', 'pallet_sheet_v2', p.seed_key, p.spec
FROM organization o CROSS JOIN (VALUES
('pallet-a4-portrait','Палета А4 · вертикальная','{"schemaVersion":2,"kind":"pallet_sheet","dpi":300,"page":{"size":"A4","orientation":"portrait","copies":1,"cutLine":false,"marginsMm":{"top":10,"right":10,"bottom":10,"left":10}},"body":[{"id":"content","gapMm":3,"kind":"stack","children":[{"id":"header","gapMm":2,"kind":"row","children":[{"id":"logo","kind":"organization_logo","source":"organization","fallback":"markiro","maxHeightMm":16},{"id":"organization","gapMm":1,"kind":"stack","children":[{"id":"org-name","kind":"field","field":"organization.name","fontSizePt":16,"bold":true,"maxLines":2},{"id":"label-title","kind":"text","text":"ПАЛЕТА","fontSizePt":8}]}]},{"id":"separator","kind":"line","thicknessMm":0.3},{"id":"product","kind":"field","field":"product.printName","fontSizePt":22,"bold":true,"maxLines":5,"reservedLines":5},{"id":"quantities","gapMm":4,"kind":"row","children":[{"id":"boxes","kind":"field_row","label":"КОРОБОВ","field":"boxCount","fontSizePt":36,"labelFontSizePt":7,"gapMm":0.6},{"id":"units","kind":"field_row","label":"ЕДИНИЦ","field":"itemCount","fontSizePt":36,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"dates","gapMm":4,"kind":"row","children":[{"id":"production","when":{"field":"productionDate","op":"present"},"kind":"field_row","label":"ПРОИЗВЕДЕНО","field":"productionDate","fontSizePt":14,"labelFontSizePt":7,"gapMm":0.6},{"id":"expiry","when":{"field":"expiryDate","op":"present"},"kind":"field_row","label":"ГОДЕН ДО","field":"expiryDate","fontSizePt":14,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"identifiers","gapMm":4,"kind":"row","children":[{"id":"gtin","kind":"field_row","label":"GTIN","field":"product.gtin","fontSizePt":12,"labelFontSizePt":7,"gapMm":0.6},{"id":"shift","when":{"field":"shiftNumber","op":"present"},"kind":"field_row","label":"СМЕНА","field":"shiftNumber","fontSizePt":12,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"egais","when":{"field":"product.egais","op":"present"},"kind":"field_row","label":"КОД ЕГАИС","field":"product.egais","fontSizePt":12,"labelFontSizePt":7,"gapMm":0.6}]}],"footer":{"id":"sscc","kind":"sscc","source":"sscc","barHeightMm":45,"moduleDots":11,"align":"center"}}'::jsonb),
('pallet-a4-landscape','Палета А4 · горизонтальная','{"schemaVersion":2,"kind":"pallet_sheet","dpi":300,"page":{"size":"A4","orientation":"landscape","copies":1,"cutLine":false,"marginsMm":{"top":10,"right":10,"bottom":10,"left":10}},"body":[{"id":"content","gapMm":3,"kind":"stack","children":[{"id":"header","gapMm":2,"kind":"row","children":[{"id":"logo","kind":"organization_logo","source":"organization","fallback":"markiro","maxHeightMm":16},{"id":"organization","gapMm":1,"kind":"stack","children":[{"id":"org-name","kind":"field","field":"organization.name","fontSizePt":16,"bold":true,"maxLines":2},{"id":"label-title","kind":"text","text":"ПАЛЕТА","fontSizePt":8}]}]},{"id":"separator","kind":"line","thicknessMm":0.3},{"id":"main","gapMm":12,"kind":"row","children":[{"id":"product-column","gapMm":4,"kind":"stack","children":[{"id":"product","kind":"field","field":"product.printName","fontSizePt":22,"bold":true,"maxLines":4,"reservedLines":4},{"id":"identifiers","gapMm":4,"kind":"row","children":[{"id":"gtin","kind":"field_row","label":"GTIN","field":"product.gtin","fontSizePt":12,"labelFontSizePt":7,"gapMm":0.6},{"id":"shift","when":{"field":"shiftNumber","op":"present"},"kind":"field_row","label":"СМЕНА","field":"shiftNumber","fontSizePt":12,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"egais","when":{"field":"product.egais","op":"present"},"kind":"field_row","label":"КОД ЕГАИС","field":"product.egais","fontSizePt":12,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"quantity-column","gapMm":4,"kind":"stack","children":[{"id":"quantities","gapMm":4,"kind":"row","children":[{"id":"boxes","kind":"field_row","label":"КОРОБОВ","field":"boxCount","fontSizePt":36,"labelFontSizePt":7,"gapMm":0.6},{"id":"units","kind":"field_row","label":"ЕДИНИЦ","field":"itemCount","fontSizePt":36,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"dates","gapMm":4,"kind":"row","children":[{"id":"production","when":{"field":"productionDate","op":"present"},"kind":"field_row","label":"ПРОИЗВЕДЕНО","field":"productionDate","fontSizePt":14,"labelFontSizePt":7,"gapMm":0.6},{"id":"expiry","when":{"field":"expiryDate","op":"present"},"kind":"field_row","label":"ГОДЕН ДО","field":"expiryDate","fontSizePt":14,"labelFontSizePt":7,"gapMm":0.6}]}]}]}]}],"footer":{"id":"sscc","kind":"sscc","source":"sscc","barHeightMm":45,"moduleDots":11,"align":"center"}}'::jsonb),
('pallet-a4-two-a5','Палета А4 · две одинаковые А5','{"schemaVersion":2,"kind":"pallet_sheet","dpi":300,"page":{"size":"A4","orientation":"landscape","copies":2,"cutLine":true,"marginsMm":{"top":10,"right":7,"bottom":10,"left":7}},"body":[{"id":"content","gapMm":1,"kind":"stack","children":[{"id":"header","gapMm":2,"kind":"row","children":[{"id":"logo","kind":"organization_logo","source":"organization","fallback":"markiro","maxHeightMm":12},{"id":"organization","gapMm":1,"kind":"stack","children":[{"id":"org-name","kind":"field","field":"organization.name","fontSizePt":11,"bold":true,"maxLines":2},{"id":"label-title","kind":"text","text":"ПАЛЕТА","fontSizePt":8}]}]},{"id":"separator","kind":"line","thicknessMm":0.3},{"id":"product","kind":"field","field":"product.printName","fontSizePt":16,"bold":true,"maxLines":5,"reservedLines":5},{"id":"quantities","gapMm":4,"kind":"row","children":[{"id":"boxes","kind":"field_row","label":"КОРОБОВ","field":"boxCount","fontSizePt":28,"labelFontSizePt":7,"gapMm":0.6},{"id":"units","kind":"field_row","label":"ЕДИНИЦ","field":"itemCount","fontSizePt":28,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"dates","gapMm":4,"kind":"row","children":[{"id":"production","when":{"field":"productionDate","op":"present"},"kind":"field_row","label":"ПРОИЗВЕДЕНО","field":"productionDate","fontSizePt":10,"labelFontSizePt":7,"gapMm":0.6},{"id":"expiry","when":{"field":"expiryDate","op":"present"},"kind":"field_row","label":"ГОДЕН ДО","field":"expiryDate","fontSizePt":10,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"identifiers","gapMm":4,"kind":"row","children":[{"id":"gtin","kind":"field_row","label":"GTIN","field":"product.gtin","fontSizePt":10,"labelFontSizePt":7,"gapMm":0.6},{"id":"shift","when":{"field":"shiftNumber","op":"present"},"kind":"field_row","label":"СМЕНА","field":"shiftNumber","fontSizePt":10,"labelFontSizePt":7,"gapMm":0.6}]},{"id":"egais","when":{"field":"product.egais","op":"present"},"kind":"field_row","label":"КОД ЕГАИС","field":"product.egais","fontSizePt":10,"labelFontSizePt":7,"gapMm":0.6}]}],"footer":{"id":"sscc","kind":"sscc","source":"sscc","barHeightMm":45,"moduleDots":9,"fallbackModuleDots":8,"align":"center"}}'::jsonb)
) AS p(seed_key,name,spec)
ON CONFLICT (tenant_id,seed_key) DO NOTHING;
