export const searchCopy = {
  "en-US": {
    title: "Search",
    intro: "Look up an exact TLC, lot ID, document number or SSCC.",
    reset: "Reset",
    q: "Exact lookup",
    tlc: "Exact TLC",
    tlcList: "TLC JSON list",
    tlcFrom: "TLC range from",
    tlcTo: "TLC range to",
    lotId: "Lot ID",
    productId: "Product",
    productText: "Current product name",
    sourceLocationId: "TLC source location",
    sourceReferenceValue: "TLC source reference URL",
    eventType: "CTE type",
    eventDateFrom: "Event date from",
    eventDateTo: "Event date to",
    locationId: "Event location",
    documentType: "Frozen document type",
    documentNumber: "Frozen document number",
    sscc: "SSCC",
    status: "Lot status",
    rangeHelp:
      "TLC ranges use lexical byte order, not numeric or date order. TLC JSON lists must contain 1–50 distinct codes.",
    dateHelp:
      "Event dates use YYYY-MM-DD. Product names are current catalog data; document filters match frozen event documents.",
    idle: "Enter a TLC, lot ID, document number or SSCC, or choose filters, then select Search.",
    invalid:
      "Check your filters: valid dates, ordered ranges and 1–50 distinct TLC codes are required.",
    loading: "Loading search results…",
    stale: "Filters have changed. Apply Search to update results.",
    failed: "Search could not be loaded. Your filters were kept.",
    empty: "No lots match these filters.",
    applied: "Server applied filters",
    pages: "Search pages",
    next: "Next",
    previous: "Previous",
    open: "Open lot {{number}} · {{source}} · {{id}}",
    source: "TLC source",
    currentProduct: "Current catalog data",
    productUnavailable: "Current product name unavailable",
    ctes: "Current CTE total",
    dates: "Current event date span",
    matched: "Matching reasons",
    caseEvidence: "Case evidence",
    moreCases: "More Case history is available in the lot card.",
    current: "Current",
    historical: "Historical",
    synthetic_demo: "Synthetic demo",
    existing_record: "Existing record",
    linked: "Linked",
    unlinked: "Unlinked",
    caseId: "Case ID",
    linkId: "Link ID",
    tlcMatch: "TLC",
    lot_id: "Lot ID",
    product_id: "Product ID",
    product_text_current: "Current product name",
    source_location: "Source location",
    source_reference: "Source reference",
    event_type: "CTE type",
    event_date: "Event date",
    location: "Location",
    document_type: "Frozen document type",
    document_number: "Frozen document number",
    sscc_current: "Current SSCC",
    sscc_historical: "Historical SSCC",
    receiving: "Receiving",
    transformation: "Transformation",
    shipping: "Shipping",
    active: "Active",
    on_hold: "On hold",
    recalled: "Recalled",
    closed: "Closed",
  },
  "es-US": {
    title: "Buscar",
    intro: "Busque un TLC, ID de lote, número de documento o SSCC exacto.",
    reset: "Restablecer",
    q: "Búsqueda exacta",
    tlc: "TLC exacto",
    tlcList: "Lista JSON de TLC",
    tlcFrom: "Rango de TLC desde",
    tlcTo: "Rango de TLC hasta",
    lotId: "ID de lote",
    productId: "Producto",
    productText: "Nombre actual del producto",
    sourceLocationId: "Ubicación de origen del TLC",
    sourceReferenceValue: "URL de referencia de origen del TLC",
    eventType: "Tipo de CTE",
    eventDateFrom: "Fecha de evento desde",
    eventDateTo: "Fecha de evento hasta",
    locationId: "Ubicación del evento",
    documentType: "Tipo de documento congelado",
    documentNumber: "Número de documento congelado",
    sscc: "SSCC",
    status: "Estado del lote",
    rangeHelp:
      "Los rangos de TLC usan orden léxico de bytes, no numérico ni cronológico. Las listas JSON deben contener entre 1 y 50 códigos distintos.",
    dateHelp:
      "Use AAAA-MM-DD para las fechas. Los nombres de productos son datos actuales del catálogo; los documentos son los congelados en el evento.",
    idle: "Introduzca un TLC, ID de lote, número de documento o SSCC, o elija filtros y seleccione Buscar.",
    invalid:
      "Revise los filtros: se requieren fechas válidas, rangos ordenados y entre 1 y 50 TLC distintos.",
    loading: "Cargando resultados…",
    stale: "Los filtros cambiaron. Aplique Buscar para actualizar los resultados.",
    failed: "No se pudo cargar la búsqueda. Se conservaron los filtros.",
    empty: "Ningún lote coincide con los filtros.",
    applied: "Filtros aplicados por el servidor",
    pages: "Páginas de búsqueda",
    next: "Siguiente",
    previous: "Anterior",
    open: "Abrir lote {{number}} · {{source}} · {{id}}",
    source: "Origen del TLC",
    currentProduct: "Datos actuales del catálogo",
    productUnavailable: "Nombre actual del producto no disponible",
    ctes: "Total de CTE actuales",
    dates: "Intervalo de fechas de eventos actuales",
    matched: "Motivos de coincidencia",
    caseEvidence: "Evidencia de cajas",
    moreCases: "Hay más historial de cajas en la ficha del lote.",
    current: "Actual",
    historical: "Histórico",
    synthetic_demo: "Demostración sintética",
    existing_record: "Registro existente",
    linked: "Vinculado",
    unlinked: "Desvinculado",
    caseId: "ID de caja",
    linkId: "ID de vínculo",
    tlcMatch: "TLC",
    lot_id: "ID de lote",
    product_id: "ID de producto",
    product_text_current: "Nombre actual del producto",
    source_location: "Ubicación de origen",
    source_reference: "Referencia de origen",
    event_type: "Tipo de CTE",
    event_date: "Fecha de evento",
    location: "Ubicación",
    document_type: "Tipo de documento congelado",
    document_number: "Número de documento congelado",
    sscc_current: "SSCC actual",
    sscc_historical: "SSCC histórico",
    receiving: "Recepción",
    transformation: "Transformación",
    shipping: "Envío",
    active: "Activo",
    on_hold: "Retenido",
    recalled: "Retirado",
    closed: "Cerrado",
  },
} as const;
