export const receivingCopy = {
  "en-US": {
    revisionNavigation: "Receipt revisions",
    revisionHistory: "Revision history",
    showHistory: "Show revision history",
    hideHistory: "Hide revision history",
    historySelection: "History selection",
    currentSelection: "Current receipts and drafts",
    allHistory: "All revisions",
    openRevision: "Open revision {{revision}}",
    viewingRevision: "Viewing this revision",
    openCurrentReceipt: "Open current receipt",
    openPendingCorrection: "Open pending correction",
    openPreviousRevision: "Open previous revision",
    correctionReason: "Correction reason",
    historyEmptyPage: "No revisions on this page.",
    historyFailed: "Revision history could not be verified. Retry the read.",
    openingRevision: "Loading selected revision…",
    revisionOpenFailed:
      "The selected revision could not be loaded. Your current view is unchanged.",
    retryRevision: "Retry selected revision",
    correctionDraft: "Correction draft",
    previousRevision: "Previous revision",
    comparison: "Revision comparison",
    comparisonHint:
      "Frozen original. Removing a line from the correction does not erase this history.",
    correctionHint:
      "Correcting revision {{revision}}. The previous receipt remains effective until this correction is finalized.",
    amendmentWorkflow:
      "Save changes, check the saved draft, then confirm finalization with QA access.",
    confirmAmendmentCounts:
      "Lines: {{lines}} · Retained lots: {{retained}} · New lots: {{created}} · Linked lots: {{linked}}",
    confirmAmendmentScope:
      "This correction will replace the current receiving basis. Retained lot identities and the frozen previous revision will not change.",
    retainedIdentityHint: "Lot identity is retained from the previous revision.",
    removedFromCorrection: "Removed from correction",
    addedLine: "Added line",
    moveUp: "Move line up",
    moveDown: "Move line down",
    sourceDescription: "Frozen source description",
    ordinaryBasis: "Ordinary receipt",
    freshExemptionReview: "This line will require a new QA review before finalization.",
    predecessorUnavailable:
      "The previous revision could not be verified. Editing remains unavailable.",
    loadingPredecessor: "Loading the correction and previous revision…",
    correctReceipt: "Correct receipt",
    startCorrection: "Start correction",
    voidReceipt: "Void receipt",
    confirmVoid: "Confirm void",
    retryOperation: "Retry same operation",
    amendConsequence:
      "Create a separate correction draft. This receipt remains effective until the correction is finalized; its frozen content is preserved.",
    voidConsequence:
      "This receipt will no longer provide receiving basis. Lot identities, statuses and source locks will not change. Frozen history is preserved.",
    voidDraftConsequence:
      "Cancel this saved draft. Any current finalized receipt remains effective. Lot identities, statuses and source locks will not change.",
    checkingBasis: "Checking current receiving basis…",
    losingBasis: "Lots losing their last receiving basis",
    noLostBasis: "No lots lose their last receiving basis in this preview.",
    basisPreviewHint: "Preview only. The server checks current state again when you confirm.",
    basisPreviewFailed: "Receiving basis could not be checked. Retry before confirming.",
    retryBasisPreview: "Retry basis check",
    operationUnknown:
      "The outcome is not confirmed. Keep this dialog open and retry the same operation; do not create a new request.",
    operationRejected:
      "The operation was rejected or the record changed. Reload current state before starting another operation.",
    void: "Void",
    amended: "Amended",
    lifecycle: "Current receipt status",
    revision: "Revision",
    reason: "Reason",
    changedBy: "Status changed by",
    changedAt: "Status changed at",
    voidHint:
      "This receipt is void and provides no current receiving basis. Lot identities, statuses and source locks are unchanged.",
    amendedHint:
      "This revision has been replaced. The frozen content below is historical, not the current receiving basis.",
    currentUnavailable:
      "The operation was acknowledged, but the current receipt could not be loaded. Editing remains paused. Retry the read; do not repeat the operation.",
    retryCurrent: "Retry current state",
    finalize: "Finalize",
    finalized: "Finalized",
    allStatuses: "All statuses",
    confirmTitle: "Finalize this receipt?",
    cancel: "Cancel",
    confirmFinalize: "Confirm finalization",
    finalizing: "Finalizing…",
    retryFinalize: "Retry same finalization",
    reloadCurrent: "Reload current record",
    confirmCounts: "Lines: {{lines}} · New lots: {{created}} · Linked lots: {{linked}}",
    totals: "Totals by unit",
    noDocuments: "No reference documents",
    confirmWarnings: "Warnings — non-blocking",
    confirmDocumentsFailed: "Reference documents could not be loaded. Reload and check again.",
    confirmScope:
      "This confirmation freezes the saved receipt and creates or links its lots. It does not establish export eligibility or a regulatory conclusion. Nothing is submitted to a third party.",
    finalizeUncertain:
      "The finalization result is unknown. Editing is paused. Retry the same confirmation, or reload the current record before making a new attempt.",
    finalizeConflict:
      "Saved data or references have changed, or confirmation was rejected. Your context is kept. Reload the current record or check the saved draft again before confirming.",
    frozenHint: "Historical receipt. Labels and identifiers below are frozen at finalization.",
    finalizedBy: "Finalized by",
    finalizedAt: "Finalized at",
    openLot: "Open current lot",
    createdLot: "Created at finalization",
    linkedLot: "Linked existing lot",
    retainedLot: "Retained from previous revision",
    currentUnconfirmed: "Current state not confirmed",
    loadedDraftHint: "Previously loaded draft. Refresh the current state before continuing.",
    title: "Receiving",
    intro: "Start a receipt, save what you know, and return when the remaining details arrive.",
    new: "New receiving",
    search: "Search event number",
    refresh: "Refresh",
    empty: "No receiving records match this search.",
    draft: "Draft",
    number: "Event",
    date: "Date received",
    lines: "Lines",
    documents: "Reference documents",
    version: "Saved version",
    created: "Created",
    updated: "Last saved",
    openError: "This draft could not be opened. Try again.",
    back: "Back to receiving",
    header: "Receiving details",
    location: "Receiving location",
    previousSource: "Immediate previous source",
    receivedAtNote: "Dock / note",
    notes: "Receiving notes",
    zone: "Time zone: {{zone}}",
    scope: "Draft only. Saving does not create lots, change inventory or finalize a receipt.",
    addLine: "Add line",
    removeLine: "Remove line",
    line: "Line {{number}}",
    noLines: "No lines yet. You can save this draft and add them later.",
    product: "Product",
    tlc: "Lot code (TLC)",
    quantity: "Quantity",
    unit: "Unit",
    choose: "Not entered",
    linkMode: "Lot link",
    createOnFinalize: "Create lot on finalization",
    linkExisting: "Link existing lot",
    lot: "Existing lot",
    sourceKind: "TLC source type",
    replaceSourceConfirm: "Change the TLC source type? The current source details will be cleared.",
    sourceLocation: "TLC source location",
    sourceReference: "Source reference URL",
    resolvedLocation: "Resolved source location",
    absent: "Not entered",
    locationKind: "Source location",
    referenceKind: "Source reference",
    exempt: "Exempt supplier",
    exemptReason: "Exemption reason",
    evidenceUrl: "Supporting evidence URL",
    tlcHandling: "TLC handling",
    preserveExisting: "Existing TLC",
    assignIfMissing: "No TLC assigned",
    proposedTlc: "Proposed TLC for own assignment",
    previouslyAssignedTlc: "Previously assigned TLC",
    receivedTlc: "Received TLC",
    ownSource: "Physical TLC source at finalization",
    ownSourceMismatch:
      "The current TLC source does not match the receiving location. Correct it explicitly before finalization.",
    useReceivingSource: "Use receiving location as TLC source",
    reviewTitle: "QA exemption review",
    reviewIntro:
      "Review every exempt line in this saved receipt. This review does not apply to other receipts from the supplier.",
    reviewLine: "Review exemption for line {{number}}",
    reviewMetadataMismatch:
      "The saved exempt lines do not match the server review requirement. Reload and check the saved draft again.",
    reviewLabelsLoading: "Loading saved-line reference labels…",
    reviewLabelsFailed: "Reference labels could not be loaded. Reload and check again.",
    receiptBasis: "Receipt basis",
    existingBasis: "Exempt receipt — existing TLC preserved",
    assignedBasis: "Exempt receipt — TLC assigned at finalization",
    reviewedBy: "Exemption reviewed by",
    reviewedAt: "Exemption reviewed at",
    supplierLot: "Supplier lot reference",
    lineNotes: "Line notes",
    identityHint:
      "Keep a received TLC and its source unchanged. If none was assigned, enter a separate proposal for assignment at finalization.",
    lineLimit: "Up to 100 lines per draft.",
    save: "Save draft",
    saved: "Draft saved.",
    unsaved: "Unsaved changes",
    saving: "Saving…",
    invalid: "Check the format of these fields:",
    readOnly: "Your current access is read-only for receiving.",
    uncertain:
      "The save result is unknown. Your input is kept and editing is paused. Retry the same save to recover its result without creating a duplicate.",
    retrySave: "Retry same save",
    conflict:
      "A newer saved version exists. Your input is kept here. Reload only when you are ready to replace it with the saved version.",
    operationConflict:
      "This save key conflicts with another request. Your input is kept. Reload the saved draft, or return to the list to locate the receipt before creating another.",
    reload: "Reload saved draft",
    reloadConfirm:
      "Replace your current input with the latest saved draft? Your unsaved changes will be discarded.",
    reloadError: "The saved draft could not be loaded. Your input has not been replaced.",
    referenceInactive:
      "A selected reference is no longer active. Choose an active record and save again.",
    referenceMissing:
      "A selected reference is unavailable in this organization. Check your selections.",
    notFound:
      "This draft is unavailable in the current organization. Your input is kept; return to the list to check access.",
    denied: "Receiving write access is unavailable. Your input is kept while access is checked.",
    failed: "The request was rejected. Your input is kept. Check your selections and try again.",
    documentPending: "Finish or cancel the new reference document before saving the receipt.",
    leaveUncertain:
      "The server may already have saved this receipt. Leave this editor? Check the receiving list before creating another receipt.",
  },
  "es-US": {
    revisionNavigation: "Revisiones de la recepción",
    revisionHistory: "Historial de revisiones",
    showHistory: "Mostrar historial de revisiones",
    hideHistory: "Ocultar historial de revisiones",
    historySelection: "Selección del historial",
    currentSelection: "Recepciones vigentes y borradores",
    allHistory: "Todas las revisiones",
    openRevision: "Abrir revisión {{revision}}",
    viewingRevision: "Revisión abierta",
    openCurrentReceipt: "Abrir recepción vigente",
    openPendingCorrection: "Abrir corrección pendiente",
    openPreviousRevision: "Abrir revisión anterior",
    correctionReason: "Motivo de la corrección",
    historyEmptyPage: "No hay revisiones en esta página.",
    historyFailed:
      "No se pudo verificar el historial de revisiones. Vuelve a intentar la consulta.",
    openingRevision: "Cargando la revisión seleccionada…",
    revisionOpenFailed:
      "No se pudo cargar la revisión seleccionada. La vista actual no ha cambiado.",
    retryRevision: "Reintentar revisión seleccionada",
    correctionDraft: "Borrador de corrección",
    previousRevision: "Revisión anterior",
    comparison: "Comparación de revisiones",
    comparisonHint:
      "Original conservado. Quitar una línea de la corrección no borra este historial.",
    correctionHint:
      "Corrigiendo la revisión {{revision}}. La recepción anterior sigue vigente hasta finalizar esta corrección.",
    amendmentWorkflow:
      "Guarda los cambios, revisa el borrador guardado y confirma la finalización con acceso de QA.",
    confirmAmendmentCounts:
      "Líneas: {{lines}} · Lotes conservados: {{retained}} · Lotes nuevos: {{created}} · Lotes vinculados: {{linked}}",
    confirmAmendmentScope:
      "Esta corrección reemplazará el respaldo de recepción vigente. No cambiarán las identidades de los lotes conservados ni la revisión anterior preservada.",
    retainedIdentityHint: "Se conserva la identidad del lote de la revisión anterior.",
    removedFromCorrection: "Eliminada de la corrección",
    addedLine: "Línea añadida",
    moveUp: "Subir línea",
    moveDown: "Bajar línea",
    sourceDescription: "Descripción histórica del origen",
    ordinaryBasis: "Recepción ordinaria",
    freshExemptionReview: "Esta línea requerirá una nueva revisión de QA antes de finalizar.",
    predecessorUnavailable:
      "No se pudo verificar la revisión anterior. La edición sigue deshabilitada.",
    loadingPredecessor: "Cargando la corrección y la revisión anterior…",
    correctReceipt: "Corregir recepción",
    startCorrection: "Iniciar corrección",
    voidReceipt: "Anular recepción",
    confirmVoid: "Confirmar anulación",
    retryOperation: "Reintentar la misma operación",
    amendConsequence:
      "Crear un borrador de corrección independiente. Esta recepción sigue vigente hasta finalizar la corrección; su contenido histórico se conserva.",
    voidConsequence:
      "Esta recepción dejará de aportar respaldo de recepción. No cambiarán las identidades, los estados ni los bloqueos de origen de los lotes. El historial se conserva.",
    voidDraftConsequence:
      "Cancelar este borrador guardado. Cualquier recepción finalizada vigente permanece activa. No cambiarán las identidades, los estados ni los bloqueos de origen de los lotes.",
    checkingBasis: "Comprobando el respaldo de recepción vigente…",
    losingBasis: "Lotes que pierden su último respaldo de recepción",
    noLostBasis: "Ningún lote pierde su último respaldo de recepción en esta vista previa.",
    basisPreviewHint: "Solo vista previa. El servidor vuelve a comprobar el estado al confirmar.",
    basisPreviewFailed:
      "No se pudo comprobar el respaldo de recepción. Reintenta antes de confirmar.",
    retryBasisPreview: "Reintentar comprobación",
    operationUnknown:
      "El resultado no está confirmado. Mantén abierto este diálogo y reintenta la misma operación; no crees una solicitud nueva.",
    operationRejected:
      "La operación fue rechazada o el registro cambió. Recarga el estado actual antes de iniciar otra operación.",
    void: "Anulada",
    amended: "Sustituida",
    lifecycle: "Estado actual de la recepción",
    revision: "Revisión",
    reason: "Motivo",
    changedBy: "Estado modificado por",
    changedAt: "Fecha del cambio de estado",
    voidHint:
      "Esta recepción está anulada y ya no aporta una base de recepción vigente. Las identidades, los estados y los bloqueos de origen de los lotes no han cambiado.",
    amendedHint:
      "Esta revisión fue sustituida. El contenido fijado que aparece a continuación es histórico, no la base de recepción vigente.",
    currentUnavailable:
      "Se confirmó la operación, pero no se pudo cargar la recepción actual. La edición sigue en pausa. Repita la consulta, no la operación.",
    retryCurrent: "Reintentar consulta del estado actual",
    finalize: "Finalizar",
    finalized: "Finalizado",
    allStatuses: "Todos los estados",
    confirmTitle: "¿Finalizar esta recepción?",
    cancel: "Cancelar",
    confirmFinalize: "Confirmar finalización",
    finalizing: "Finalizando…",
    retryFinalize: "Repetir la misma finalización",
    reloadCurrent: "Recargar registro actual",
    confirmCounts: "Líneas: {{lines}} · Lotes nuevos: {{created}} · Lotes vinculados: {{linked}}",
    totals: "Totales por unidad",
    noDocuments: "Sin documentos de referencia",
    confirmWarnings: "Advertencias — no bloquean",
    confirmDocumentsFailed:
      "No se pudieron cargar los documentos de referencia. Recargue y vuelva a revisar.",
    confirmScope:
      "Esta confirmación congela la recepción guardada y crea o vincula sus lotes. No establece elegibilidad de exportación ni una conclusión regulatoria. No se envía nada a terceros.",
    finalizeUncertain:
      "Se desconoce el resultado de la finalización. La edición está en pausa. Repita la misma confirmación o recargue el registro actual antes de un nuevo intento.",
    finalizeConflict:
      "Los datos guardados o las referencias han cambiado, o se rechazó la confirmación. Se conserva el contexto. Recargue el registro actual o vuelva a revisar el borrador antes de confirmar.",
    frozenHint: "Recepción histórica. Las etiquetas e identificadores se congelaron al finalizar.",
    finalizedBy: "Finalizado por",
    finalizedAt: "Finalizado el",
    openLot: "Abrir lote actual",
    createdLot: "Creado al finalizar",
    linkedLot: "Lote existente vinculado",
    retainedLot: "Conservado de la revisión anterior",
    currentUnconfirmed: "Estado actual sin confirmar",
    loadedDraftHint:
      "Borrador cargado anteriormente. Consulta el estado actual antes de continuar.",
    title: "Recepción",
    intro:
      "Inicie una recepción, guarde los datos disponibles y vuelva cuando lleguen los detalles restantes.",
    new: "Nueva recepción",
    search: "Buscar número de evento",
    refresh: "Actualizar",
    empty: "No hay registros de recepción que coincidan con esta búsqueda.",
    draft: "Borrador",
    number: "Evento",
    date: "Fecha de recepción",
    lines: "Líneas",
    documents: "Documentos de referencia",
    version: "Versión guardada",
    created: "Creado",
    updated: "Último guardado",
    openError: "No se pudo abrir este borrador. Inténtelo de nuevo.",
    back: "Volver a recepción",
    header: "Datos de recepción",
    location: "Ubicación de recepción",
    previousSource: "Origen anterior inmediato",
    receivedAtNote: "Muelle / nota",
    notes: "Notas de recepción",
    zone: "Zona horaria: {{zone}}",
    scope: "Solo borrador. Guardar no crea lotes, modifica inventario ni finaliza una recepción.",
    addLine: "Agregar línea",
    removeLine: "Quitar línea",
    line: "Línea {{number}}",
    noLines: "Aún no hay líneas. Puede guardar este borrador y agregarlas después.",
    product: "Producto",
    tlc: "Código de lote (TLC)",
    quantity: "Cantidad",
    unit: "Unidad",
    choose: "Sin ingresar",
    linkMode: "Vínculo del lote",
    createOnFinalize: "Crear lote al finalizar",
    linkExisting: "Vincular lote existente",
    lot: "Lote existente",
    sourceKind: "Tipo de origen del TLC",
    replaceSourceConfirm:
      "¿Cambiar el tipo de origen del TLC? Se borrarán los datos del origen actual.",
    sourceLocation: "Ubicación de origen del TLC",
    sourceReference: "URL de referencia del origen",
    resolvedLocation: "Ubicación del origen resuelta",
    absent: "Sin ingresar",
    locationKind: "Ubicación del origen",
    referenceKind: "Referencia del origen",
    exempt: "Proveedor exento",
    exemptReason: "Motivo de exención",
    evidenceUrl: "URL de evidencia justificativa",
    tlcHandling: "Tratamiento del TLC",
    preserveExisting: "TLC existente",
    assignIfMissing: "No se asignó un TLC",
    proposedTlc: "TLC propuesto para asignación propia",
    previouslyAssignedTlc: "TLC asignado anteriormente",
    receivedTlc: "TLC recibido",
    ownSource: "Origen físico del TLC al finalizar",
    ownSourceMismatch:
      "El origen actual del TLC no coincide con la ubicación de recepción. Corríjalo explícitamente antes de finalizar.",
    useReceivingSource: "Usar la ubicación de recepción como origen del TLC",
    reviewTitle: "Revisión de exención por Calidad",
    reviewIntro:
      "Revise cada línea exenta de esta recepción guardada. Esta revisión no se aplica a otras recepciones del proveedor.",
    reviewLine: "Revisar exención de la línea {{number}}",
    reviewMetadataMismatch:
      "Las líneas exentas guardadas no coinciden con la revisión requerida por el servidor. Recargue y vuelva a revisar el borrador guardado.",
    reviewLabelsLoading: "Cargando las etiquetas de referencia de las líneas guardadas…",
    reviewLabelsFailed:
      "No se pudieron cargar las etiquetas de referencia. Recargue y vuelva a revisar.",
    receiptBasis: "Base de la recepción",
    existingBasis: "Recepción exenta: se conservó el TLC existente",
    assignedBasis: "Recepción exenta: TLC asignado al finalizar",
    reviewedBy: "Exención revisada por",
    reviewedAt: "Exención revisada el",
    supplierLot: "Referencia del lote del proveedor",
    lineNotes: "Notas de la línea",
    identityHint:
      "Conserve sin cambios el TLC recibido y su origen. Si no se asignó ninguno, introduzca una propuesta separada para asignarla al finalizar.",
    lineLimit: "Hasta 100 líneas por borrador.",
    save: "Guardar borrador",
    saved: "Borrador guardado.",
    unsaved: "Cambios sin guardar",
    saving: "Guardando…",
    invalid: "Revise el formato de estos campos:",
    readOnly: "Su acceso actual a recepción es de solo lectura.",
    uncertain:
      "Se desconoce el resultado del guardado. Sus datos se conservan y la edición está en pausa. Repita el mismo guardado para recuperar el resultado sin crear un duplicado.",
    retrySave: "Repetir el mismo guardado",
    conflict:
      "Existe una versión guardada más reciente. Sus datos se conservan aquí. Recargue solo cuando desee reemplazarlos por la versión guardada.",
    operationConflict:
      "Esta clave de guardado entra en conflicto con otra solicitud. Sus datos se conservan. Recargue el borrador o vuelva a la lista para buscar la recepción antes de crear otra.",
    reload: "Recargar borrador guardado",
    reloadConfirm:
      "¿Reemplazar los datos actuales por el último borrador guardado? Se descartarán los cambios sin guardar.",
    reloadError: "No se pudo cargar el borrador guardado. Sus datos no se han reemplazado.",
    referenceInactive:
      "Una referencia seleccionada ya no está activa. Elija un registro activo y vuelva a guardar.",
    referenceMissing:
      "Una referencia seleccionada no está disponible en esta organización. Revise sus selecciones.",
    notFound:
      "Este borrador no está disponible en la organización actual. Sus datos se conservan; vuelva a la lista para verificar el acceso.",
    denied:
      "El acceso de escritura a recepción no está disponible. Sus datos se conservan mientras se verifica el acceso.",
    failed:
      "La solicitud fue rechazada. Sus datos se conservan. Revise las selecciones e inténtelo de nuevo.",
    documentPending:
      "Termine o cancele el nuevo documento de referencia antes de guardar la recepción.",
    leaveUncertain:
      "Es posible que el servidor ya haya guardado esta recepción. ¿Salir del editor? Revise la lista antes de crear otra recepción.",
  },
} as const;
