export const receivingCsvCopy = {
  "en-US": {
    exportSection: "Saved receiving CSV export",
    exportAction: "Export CSV",
    exportPending: "Preparing CSV…",
    exportDirty: "Save or discard changes before exporting the saved record.",
    exportHint: "Exports this saved revision, not the supplier upload template or unsaved edits.",
    exportReady: "Download ready.",
    exportStale: "The saved record changed. Reload it before exporting again.",
    exportTooLarge: "This saved record is too large for the CSV export. No file was downloaded.",
    exportAccess: "Export access is no longer available. Sign in or ask an administrator.",
    exportUnavailable: "The export could not be reached. Try again explicitly.",
    exportInvalid:
      "The export could not be verified. No file was downloaded. Try again explicitly.",
    exportReload: "Reload record",
    selectedFile: "Selected file: {{name}}",
    limitedCells:
      "Showing the first {{shown}} of {{total}} cells. Correct the column count in the original file.",
    title: "Import CSV",
    intro: "One file, one receiving draft. Review the data before creating anything.",
    steps: "Import steps",
    input: "File & receiving data",
    review: "Review rows",
    confirm: "Confirm draft",
    file: "CSV file",
    limit: "UTF-8 · comma-separated · up to 100 rows · 256 KiB maximum.",
    template: "Download blank template",
    preview: "Preview file",
    next: "Continue to confirmation",
    back: "Back to file",
    backReview: "Back to review",
    create: "Create receiving draft",
    check: "I reviewed the file and common receiving data.",
    draftOnly:
      "This creates an incomplete draft only. It does not finalize the receipt, approve exemptions or assign lots.",
    correct:
      "Rows are read-only. Correct the CSV file and preview it again to change imported values.",
    ready: "Ready to create a draft",
    blocked: "Fix the reported errors before continuing.",
    count_one: "{{count}} row",
    count_other: "{{count}} rows",
    row: "Row {{row}} · file line {{line}}",
    raw: "Original cells",
    normalizations: "Value changes",
    empty: "Empty",
    normalized: "Proposed receiving data",
    docs: "Document IDs",
    unknown:
      "The result is unknown. Do not start another import for this delivery. Retry the same operation to recover its result.",
    retry: "Retry same operation",
    read: "Load current record",
    acknowledged:
      "The operation succeeded, but the current record could not be loaded. Retry the read, not creation.",
    pending: "Working…",
    forbidden: "Import access is no longer available. File and operation data have been cleared.",
    fileError: "Select a readable CSV file no larger than 256 KiB.",
    inputError: "Check the file and receiving fields, then preview again.",
    previewError:
      "The preview could not be verified. No receiving draft was requested. Try previewing again.",
    expired: "This preview expired. Return to the file and create a new preview.",
    stale: "Referenced data changed. Return to the file and create a new preview.",
    conflict:
      "The operation or preview does not match. Return to Receiving and check existing records before starting again.",
    columns:
      "Keep the template's English column keys unchanged. Supply product_id or product_gtin, an explicit lot_link_mode, and true/false for exempt_supplier.",
    problem: "{{column}}: {{reason}}",
    changed: "{{before}} → {{after}}",
    none: "No field errors",
    errors: {
      version: "Unsupported template version",
      byte_limit: "File exceeds 256 KiB",
      invalid_utf8: "File is not valid UTF-8",
      nul: "File contains a NUL character",
      syntax: "Invalid CSV quoting or line ending",
      header: "Column names or order do not match the template",
      no_rows: "Add at least one data row",
      row_limit: "More than 100 data rows",
      column_count: "Wrong number of columns",
      value: "Invalid field value",
      product_selector: "Supply exactly one product ID or GTIN",
      boolean: "Use literal true or false",
      lot_link: "Check the lot link mode and lot ID",
      source: "Check the TLC source fields",
      not_found: "Reference not found",
      inactive: "Reference is inactive",
    },
  },
  "es-US": {
    exportSection: "Exportación CSV de recepción guardada",
    exportAction: "Exportar CSV",
    exportPending: "Preparando CSV…",
    exportDirty: "Guarde o descarte los cambios antes de exportar el registro guardado.",
    exportHint:
      "Exporta esta revisión guardada, no la plantilla de carga ni los cambios sin guardar.",
    exportReady: "Descarga lista.",
    exportStale: "El registro guardado cambió. Vuelva a cargarlo antes de exportar.",
    exportTooLarge:
      "Este registro es demasiado grande para exportarlo como CSV. No se descargó ningún archivo.",
    exportAccess:
      "El acceso a la exportación ya no está disponible. Inicie sesión o consulte a un administrador.",
    exportUnavailable: "No se pudo acceder a la exportación. Inténtelo de nuevo explícitamente.",
    exportInvalid:
      "No se pudo verificar la exportación. No se descargó ningún archivo. Inténtelo de nuevo explícitamente.",
    exportReload: "Volver a cargar el registro",
    selectedFile: "Archivo seleccionado: {{name}}",
    limitedCells:
      "Se muestran las primeras {{shown}} de {{total}} celdas. Corrija el número de columnas en el archivo original.",
    title: "Importar CSV",
    intro: "Un archivo, un borrador de recepción. Revise los datos antes de crearlo.",
    steps: "Pasos de importación",
    input: "Archivo y recepción",
    review: "Revisar filas",
    confirm: "Confirmar borrador",
    file: "Archivo CSV",
    limit: "UTF-8 · separado por comas · hasta 100 filas · máximo 256 KiB.",
    template: "Descargar plantilla vacía",
    preview: "Previsualizar archivo",
    next: "Continuar a la confirmación",
    back: "Volver al archivo",
    backReview: "Volver a la revisión",
    create: "Crear borrador de recepción",
    check: "He revisado el archivo y los datos comunes de recepción.",
    draftOnly:
      "Solo se crea un borrador incompleto. No finaliza la recepción, aprueba exenciones ni asigna lotes.",
    correct:
      "Las filas son de solo lectura. Corrija el archivo CSV y vuelva a previsualizarlo para cambiar los valores importados.",
    ready: "Listo para crear un borrador",
    blocked: "Corrija los errores indicados antes de continuar.",
    count_one: "{{count}} fila",
    count_other: "{{count}} filas",
    row: "Fila {{row}} · línea del archivo {{line}}",
    raw: "Celdas originales",
    normalizations: "Cambios de valores",
    empty: "Vacío",
    normalized: "Datos de recepción propuestos",
    docs: "ID de documentos",
    unknown:
      "El resultado es desconocido. No inicie otra importación para esta entrega. Reintente la misma operación para recuperar el resultado.",
    retry: "Reintentar la misma operación",
    read: "Cargar registro actual",
    acknowledged:
      "La operación se completó, pero no se pudo cargar el registro actual. Reintente la lectura, no la creación.",
    pending: "Procesando…",
    forbidden:
      "El acceso a la importación ya no está disponible. Se han borrado los datos del archivo y de la operación.",
    fileError: "Seleccione un archivo CSV legible de hasta 256 KiB.",
    inputError: "Revise el archivo y los campos de recepción y vuelva a previsualizar.",
    previewError:
      "No se pudo verificar la vista previa. No se solicitó ningún borrador de recepción. Intente previsualizar de nuevo.",
    expired: "Esta vista previa ha caducado. Vuelva al archivo y genere otra.",
    stale: "Los datos de referencia han cambiado. Vuelva al archivo y genere otra vista previa.",
    conflict:
      "La operación o la vista previa no coincide. Vuelva a Recepciones y revise los registros existentes antes de empezar de nuevo.",
    columns:
      "Mantenga las claves de columna en inglés de la plantilla. Indique product_id o product_gtin, un lot_link_mode explícito y true/false para exempt_supplier.",
    problem: "{{column}}: {{reason}}",
    changed: "{{before}} → {{after}}",
    none: "Sin errores de campo",
    errors: {
      version: "Versión de plantilla no compatible",
      byte_limit: "El archivo supera 256 KiB",
      invalid_utf8: "El archivo no es UTF-8 válido",
      nul: "El archivo contiene un carácter NUL",
      syntax: "Comillas o saltos de línea CSV no válidos",
      header: "Los nombres o el orden de las columnas no coinciden con la plantilla",
      no_rows: "Añada al menos una fila de datos",
      row_limit: "Más de 100 filas de datos",
      column_count: "Número incorrecto de columnas",
      value: "Valor de campo no válido",
      product_selector: "Indique un solo ID de producto o GTIN",
      boolean: "Use true o false literalmente",
      lot_link: "Revise el modo de vinculación y el ID del lote",
      source: "Revise los campos de origen del TLC",
      not_found: "Referencia no encontrada",
      inactive: "Referencia inactiva",
    },
  },
};
