export const readinessCopy = {
  "en-US": {
    title: "Saved-draft data check",
    intro:
      "Check saved fields and current reference records. This does not save or finalize the event.",
    check: "Check saved draft",
    checking: "Checking saved draft…",
    saveFirst: "Save this draft before checking its data.",
    saveChanges: "Save your changes before checking. Unsaved values are not included.",
    unavailableWhileSaving: "Finish the current save or reload before checking.",
    complete: "Complete — no blockers in this saved-data check.",
    blocked_one: "{{count}} required element needs attention.",
    blocked_other: "{{count}} required elements need attention.",
    warnings_one: "{{count}} warning",
    warnings_other: "{{count}} warnings",
    scope:
      "This result does not mean the event is finalized, export-ready, or compliant. Reference records can change after this check.",
    stale: "Previous check is out of date. Check the saved draft again.",
    staleIssues: "Previous findings — check again for current results",
    checked: "Saved version {{version}} · Checked {{date}}",
    pendingQa: "Pending QA review for saved exempt lines: {{lines}}.",
    conflict: "The saved draft changed. Reload the saved event before checking again.",
    reload: "Reload saved event",
    failed: "The check could not be completed. Your draft was not changed. Try checking again.",
    denied: "Your access changed. The previous check is no longer shown.",
    header: "Header",
    lines: "Lines",
    documents: "Reference documents",
    error: "Required",
    warning: "Warning",
    documentRequired: "Link at least one reference document.",
    documentRecommended: "Consider linking at least one reference document.",
    fields: {
      dateReceived: "Date received",
      location: "Receiving location",
      previousSource: "Previous source",
      items: "Receiving lines",
      product: "Product",
      coverage: "Product coverage",
      tlc: "Lot code (TLC)",
      source: "TLC source",
      quantity: "Quantity",
      unitOfMeasure: "Unit",
      lot: "Existing lot",
      exemption: "Exempt supplier",
      documents: "Reference documents",
    },
    codes: {
      required: "Add the required value.",
      format: "Review the value's format.",
      unavailable: "This reference is unavailable. Select an available record.",
      inactive: "This record is inactive. Review it before using it.",
      incomplete_description: "Complete the referenced record's description.",
      wrong_role: "This location does not have the required role.",
      coverage_unresolved:
        "The product's coverage review is incomplete. Ask QA to review the product.",
      not_assessed: "FTR applicability is not assessed in this profile.",
      lot_product_mismatch: "The selected lot belongs to a different product.",
      lot_tlc_mismatch: "The entered TLC does not match the selected lot.",
      lot_source_mismatch: "The entered source does not match the selected lot.",
      lot_link_inconsistent: "Review the existing-lot selection and linking mode.",
      duplicate_identity:
        "This TLC and source already exist in another line or lot. Review the linking mode.",
      exemption_review_required: "QA must review this exempt receipt line before finalization.",
      tlc_assignment_required:
        "Enter the existing TLC or a separate proposed TLC for assignment during finalization.",
    },
    details: {
      businessName: "Business name",
      phoneNumber: "Phone",
      addressKind: "Address type",
      streetAddress: "Street address",
      latitude: "Latitude",
      longitude: "Longitude",
      city: "City",
      stateOrRegion: "State or region",
      zipOrPostalCode: "ZIP or postal code",
      countryCode: "Country",
      productName: "Product name",
      brandName: "Brand",
      commodity: "Commodity",
      variety: "Variety",
      packagingSizeValue: "Package size",
      packagingSizeUom: "Package-size unit",
      packagingStyle: "Packaging style",
      defaultQuantityUom: "Default quantity unit",
      gtin: "GTIN",
      coverageStatus: "Coverage status",
      coverageRationale: "Coverage rationale",
      ftlCategory: "FTL category",
      ftlSourceUrl: "FTL source URL",
      ftlSourceVersion: "FTL source version",
      reviewedBy: "Reviewer",
      reviewedAt: "Review date",
      exemptReason: "Exemption reason",
      evidenceUrl: "Evidence URL",
      tlcHandling: "TLC handling",
      proposedTlc: "Proposed TLC",
    },
  },
  "es-US": {
    title: "Revisión de datos del borrador guardado",
    intro:
      "Revise los campos guardados y los registros de referencia actuales. Esta acción no guarda ni finaliza el evento.",
    check: "Revisar borrador guardado",
    checking: "Revisando borrador guardado…",
    saveFirst: "Guarde este borrador antes de revisar sus datos.",
    saveChanges: "Guarde los cambios antes de revisar. Los valores sin guardar no se incluyen.",
    unavailableWhileSaving: "Termine de guardar o recargar antes de revisar.",
    complete: "Completo: esta revisión de los datos guardados no encontró bloqueos.",
    blocked_one: "{{count}} dato obligatorio requiere atención.",
    blocked_other: "{{count}} datos obligatorios requieren atención.",
    warnings_one: "{{count}} advertencia",
    warnings_other: "{{count}} advertencias",
    scope:
      "Este resultado no significa que el evento esté finalizado, listo para exportar o conforme a la normativa. Los registros de referencia pueden cambiar después de esta revisión.",
    stale: "La revisión anterior está desactualizada. Revise de nuevo el borrador guardado.",
    staleIssues: "Hallazgos anteriores: vuelva a revisar para obtener resultados actuales",
    checked: "Versión guardada {{version}} · Revisado {{date}}",
    pendingQa: "Revisión de Calidad pendiente para las líneas exentas guardadas: {{lines}}.",
    conflict:
      "El borrador guardado cambió. Recargue el evento guardado antes de revisarlo de nuevo.",
    reload: "Recargar evento guardado",
    failed: "No se pudo completar la revisión. Su borrador no cambió. Intente revisar de nuevo.",
    denied: "Su acceso cambió. La revisión anterior ya no se muestra.",
    header: "Cabecera",
    lines: "Líneas",
    documents: "Documentos de referencia",
    error: "Obligatorio",
    warning: "Advertencia",
    documentRequired: "Vincule al menos un documento de referencia.",
    documentRecommended: "Considere vincular al menos un documento de referencia.",
    fields: {
      dateReceived: "Fecha de recepción",
      location: "Ubicación de recepción",
      previousSource: "Fuente anterior",
      items: "Líneas de recepción",
      product: "Producto",
      coverage: "Cobertura del producto",
      tlc: "Código de lote (TLC)",
      source: "Fuente de TLC",
      quantity: "Cantidad",
      unitOfMeasure: "Unidad",
      lot: "Lote existente",
      exemption: "Proveedor exento",
      documents: "Documentos de referencia",
    },
    codes: {
      required: "Añada el valor obligatorio.",
      format: "Revise el formato del valor.",
      unavailable: "Esta referencia no está disponible. Seleccione un registro disponible.",
      inactive: "Este registro está inactivo. Revíselo antes de utilizarlo.",
      incomplete_description: "Complete la descripción del registro de referencia.",
      wrong_role: "Esta ubicación no tiene el rol requerido.",
      coverage_unresolved:
        "La revisión de cobertura del producto está incompleta. Solicite su revisión a Calidad.",
      not_assessed: "La aplicabilidad de FTR no se evalúa en este perfil.",
      lot_product_mismatch: "El lote seleccionado pertenece a otro producto.",
      lot_tlc_mismatch: "El TLC introducido no coincide con el lote seleccionado.",
      lot_source_mismatch: "La fuente introducida no coincide con el lote seleccionado.",
      lot_link_inconsistent: "Revise el lote seleccionado y el modo de vinculación.",
      duplicate_identity:
        "Este TLC y esta fuente ya existen en otra línea o lote. Revise el modo de vinculación.",
      exemption_review_required:
        "Calidad debe revisar esta línea de recepción exenta antes de finalizar.",
      tlc_assignment_required:
        "Introduzca el TLC existente o un TLC propuesto por separado para asignarlo al finalizar.",
    },
    details: {
      businessName: "Nombre comercial",
      phoneNumber: "Teléfono",
      addressKind: "Tipo de dirección",
      streetAddress: "Dirección postal",
      latitude: "Latitud",
      longitude: "Longitud",
      city: "Ciudad",
      stateOrRegion: "Estado o región",
      zipOrPostalCode: "Código postal",
      countryCode: "País",
      productName: "Nombre del producto",
      brandName: "Marca",
      commodity: "Materia prima",
      variety: "Variedad",
      packagingSizeValue: "Tamaño del envase",
      packagingSizeUom: "Unidad del tamaño del envase",
      packagingStyle: "Tipo de envase",
      defaultQuantityUom: "Unidad de cantidad predeterminada",
      gtin: "GTIN",
      coverageStatus: "Estado de cobertura",
      coverageRationale: "Justificación de cobertura",
      ftlCategory: "Categoría FTL",
      ftlSourceUrl: "URL de fuente FTL",
      ftlSourceVersion: "Versión de fuente FTL",
      reviewedBy: "Revisor",
      reviewedAt: "Fecha de revisión",
      exemptReason: "Motivo de exención",
      evidenceUrl: "URL de evidencia",
      tlcHandling: "Tratamiento del TLC",
      proposedTlc: "TLC propuesto",
    },
  },
} as const;
