export const referenceCopy = {
  "en-US": {
    choose: "Select…",
    search: "Search",
    searchProduct: "Search active products",
    searchLocation: "Search active locations",
    searchLot: "Search active lots",
    searchDocument: "Search active reference documents",
    searchParty: "Search active parties",
    noChoices: "No active references match this search.",
    selectedId: "Selected reference · {{id}}",
    loadError: "Reference data could not be loaded. The selected identity was kept.",
    retry: "Try again",
    previousPage: "Previous page",
    nextPage: "Next page",
    page: "Page {{page}}",
    documentsTitle: "Reference documents",
    documentsIntro: "Attach existing document metadata or create a new reference.",
    document: "Reference document",
    attach: "Attach document",
    detach: "Detach document",
    attached: "Document attached.",
    detached: "Document detached from this draft.",
    duplicateAttachment: "This document is already attached.",
    chooseDocument: "Select a document to attach.",
    attachmentLimit: "A receiving draft can have up to 100 documents.",
    noDocuments: "No reference documents are attached.",
    attachedLoadError: "Some attached document labels could not be loaded.",
    createTitle: "Create document metadata",
    createIntro: "This creates a reusable metadata record and attaches it to this draft.",
    documentType: "Document type",
    typeOtherLabel: "Custom document type",
    documentNumber: "Document number",
    issuingParty: "Issuing party",
    issuedOn: "Issued on",
    notes: "Notes",
    createAndAttach: "Create and attach",
    clearCreate: "Clear document metadata",
    retrySameCreate: "Retry same creation",
    invalidDocument: "Check the document metadata.",
    created: "Document created and attached.",
    duplicateDocument: "A document with this identity already exists. Search for and attach it.",
    uncertainCreate:
      "The create result could not be confirmed. This document may already exist. Retry only with the same metadata.",
    sessionLost: "Your session ended. The document metadata was kept.",
    forbidden: "Your receiving write access changed. The document metadata was kept.",
    types: {
      bol: "Bill of lading (BOL)",
      po: "Purchase order (PO)",
      asn: "Advance ship notice (ASN)",
      work_order: "Work order",
      invoice: "Invoice",
      database_record: "Database record",
      batch_log: "Batch log",
      production_log: "Production log",
      other: "Other",
    },
  },
  "es-US": {
    choose: "Seleccionar…",
    search: "Buscar",
    searchProduct: "Buscar productos activos",
    searchLocation: "Buscar ubicaciones activas",
    searchLot: "Buscar lotes activos",
    searchDocument: "Buscar documentos de referencia activos",
    searchParty: "Buscar partes activas",
    noChoices: "Ninguna referencia activa coincide con esta búsqueda.",
    selectedId: "Referencia seleccionada · {{id}}",
    loadError:
      "No se pudieron cargar los datos de referencia. Se conservó la identidad seleccionada.",
    retry: "Intentar de nuevo",
    previousPage: "Página anterior",
    nextPage: "Página siguiente",
    page: "Página {{page}}",
    documentsTitle: "Documentos de referencia",
    documentsIntro: "Adjunte metadatos existentes o cree una referencia nueva.",
    document: "Documento de referencia",
    attach: "Adjuntar documento",
    detach: "Desvincular documento",
    attached: "Documento adjuntado.",
    detached: "Documento desvinculado de este borrador.",
    duplicateAttachment: "Este documento ya está adjuntado.",
    chooseDocument: "Seleccione un documento para adjuntar.",
    attachmentLimit: "Un borrador de recepción puede tener hasta 100 documentos.",
    noDocuments: "No hay documentos de referencia adjuntos.",
    attachedLoadError: "No se pudieron cargar algunas etiquetas de documentos adjuntos.",
    createTitle: "Crear metadatos del documento",
    createIntro: "Esto crea un registro de metadatos reutilizable y lo adjunta al borrador.",
    documentType: "Tipo de documento",
    typeOtherLabel: "Tipo de documento personalizado",
    documentNumber: "Número del documento",
    issuingParty: "Parte emisora",
    issuedOn: "Fecha de emisión",
    notes: "Notas",
    createAndAttach: "Crear y adjuntar",
    clearCreate: "Borrar metadatos del documento",
    retrySameCreate: "Reintentar la misma creación",
    invalidDocument: "Revise los metadatos del documento.",
    created: "Documento creado y adjuntado.",
    duplicateDocument: "Ya existe un documento con esta identidad. Búsquelo y adjúntelo.",
    uncertainCreate:
      "No se pudo confirmar el resultado de la creación. Es posible que el documento ya exista. Reintente solo con los mismos metadatos.",
    sessionLost: "Su sesión terminó. Se conservaron los metadatos del documento.",
    forbidden:
      "Su acceso de escritura de recepción cambió. Se conservaron los metadatos del documento.",
    types: {
      bol: "Conocimiento de embarque (BOL)",
      po: "Orden de compra (PO)",
      asn: "Aviso anticipado de envío (ASN)",
      work_order: "Orden de trabajo",
      invoice: "Factura",
      database_record: "Registro de base de datos",
      batch_log: "Registro de lote",
      production_log: "Registro de producción",
      other: "Otro",
    },
  },
} as const;
