import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router";
import { Alert, Button, EmptyState, PageHeader, Select, Spinner, StatusChip, Table } from "@markiro/ui";
import type { TableColumn } from "@markiro/ui";
import { CABINET_CAPABILITY } from "@markiro/domain";
import { useCan } from "../../access/context.js";
import { DeviceDrawer } from "./DeviceDrawer.js";
import { DevicePager } from "./DevicePager.js";
import { useDevices, type DeviceDto, type DeviceStatus, type DeviceType } from "./api.js";

export function DevicesPage() { const { t } = useTranslation(); const [type, setType] = useState<DeviceType | undefined>(); const [status, setStatus] = useState<DeviceStatus | undefined>(); const [page, setPage] = useState(1); const [open, setOpen] = useState(false); const canWriteOperations = useCan(CABINET_CAPABILITY.OPERATIONS_WRITE); const canManageCredentials = useCan(CABINET_CAPABILITY.CREDENTIALS_MANAGE); const canWrite = canWriteOperations || canManageCredentials; const result = useDevices({ ...(type ? { type } : {}), ...(status ? { status } : {}), page, pageSize: 8 }); const columns = useMemo<TableColumn<DeviceDto>[]>(() => [{ key: "name", title: t("pages.devices.table.name") }, { key: "type", title: t("pages.devices.table.type"), render: (row) => t(`pages.devices.type.${row.type}`) }, { key: "place", title: t("pages.devices.table.place"), render: (row) => row.place.name ?? "—" }, { key: "status", title: t("pages.devices.table.status"), render: (row) => <StatusChip status={row.status === "online" ? "ok" : row.status === "revoked" ? "error" : row.status === "offline" ? "neutral" : "info"} label={t(`pages.devices.status.${row.status}`)} /> }], [t]); const changeType = (value: string) => { setType(value ? value as DeviceType : undefined); setPage(1); }; const changeStatus = (value: string) => { setStatus(value ? value as DeviceStatus : undefined); setPage(1); };
 return <div style={{ padding: "28px 32px", display: "flex", flexDirection: "column", gap: 20 }}><PageHeader title={t("pages.devices.title")} actions={canWrite ? <Button onClick={() => setOpen(true)}>{t("pages.devices.add")}</Button> : undefined} /><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}><Select label={t("pages.devices.typeLabel")} value={type ?? ""} onChange={changeType} options={[{ value: "", label: t("pages.devices.allTypes") }, { value: "station", label: t("pages.devices.type.station") }, { value: "kiosk", label: t("pages.devices.type.kiosk") }]} /><Select label={t("pages.devices.statusLabel")} value={status ?? ""} onChange={changeStatus} options={[{ value: "", label: t("pages.devices.allStatuses") }, ...(["awaiting_pairing", "online", "offline", "revoked"] as const).map((item) => ({ value: item, label: t(`pages.devices.status.${item}`) }))]} /></div>{result.isPending ? <Spinner label={t("common.loading")} /> : result.isError ? <Alert tone="error">{t("common.loadError")}</Alert> : result.data?.items.length ? <><Table columns={[...columns, { key: "actions", title: t("pages.devices.table.actions"), render: (row: DeviceDto) => row.type === "kiosk" ? <Link to={`/kiosks/${row.id}`} aria-label={t("pages.devices.kioskSettings")}>{t("pages.devices.kioskSettings")}</Link> : null }]} rows={result.data.items} /><DevicePager page={result.data.page} pageSize={result.data.pageSize} total={result.data.total} onPage={setPage} label={t("pages.devices.pager.label")} previousLabel={t("pages.devices.pager.previous")} nextLabel={t("pages.devices.pager.next")} /></> : <EmptyState title={t("pages.devices.emptyTitle")} hint={t("pages.devices.emptyHint")} />}{open ? <DeviceDrawer open onClose={() => setOpen(false)} /> : null}</div>; }
