export const eventsCopy = {
  "en-US": {
    title: "Events",
    intro: "Receiving, Transformation, and Shipping records in one ordered ledger.",
    type: "Event type",
    allTypes: "All types",
    receiving: "Receiving",
    transformation: "Transformation",
    shipping: "Shipping",
    numberRevision: "Event / revision",
    date: "Event date",
    location: "Location",
    timeZone: "Time zone",
    summary: "Lines / documents",
    receivingSummary: "{{lines}} lines · {{documents}} documents",
    transformationSummary: "{{inputs}} inputs · {{outputs}} outputs · {{documents}} documents",
    shippingSummary: "{{lines}} lines · {{documents}} documents",
    search: "Search event number",
    allStatuses: "All statuses",
    current: "Current events and drafts",
    allHistory: "All revisions",
    history: "History selection",
    refresh: "Refresh events",
    empty: "No events match these filters.",
    loadError: "The Events list could not be loaded.",
    openError: "This event could not be opened. Retry from the ledger.",
    back: "Back to events",
    newReceiving: "New receiving",
    importCsv: "Import CSV",
    readOnlySummary: "Transformation summary",
    summaryHint: "Read-only event registry summary.",
    draft: "Draft",
    finalized: "Finalized",
    amended: "Amended",
    void: "Void",
  },
  "es-US": {
    title: "Eventos",
    intro: "Registros de recepción, transformación y envío en una sola lista ordenada.",
    type: "Tipo de evento",
    allTypes: "Todos los tipos",
    receiving: "Recepción",
    transformation: "Transformación",
    shipping: "Envío",
    numberRevision: "Evento / revisión",
    date: "Fecha del evento",
    location: "Ubicación",
    timeZone: "Zona horaria",
    summary: "Líneas / documentos",
    receivingSummary: "{{lines}} líneas · {{documents}} documentos",
    transformationSummary: "{{inputs}} entradas · {{outputs}} salidas · {{documents}} documentos",
    shippingSummary: "{{lines}} líneas · {{documents}} documentos",
    search: "Buscar número de evento",
    allStatuses: "Todos los estados",
    current: "Eventos y borradores vigentes",
    allHistory: "Todas las revisiones",
    history: "Selección del historial",
    refresh: "Actualizar eventos",
    empty: "Ningún evento coincide con estos filtros.",
    loadError: "No se pudo cargar la lista de eventos.",
    openError: "No se pudo abrir este evento. Inténtelo de nuevo desde la lista.",
    back: "Volver a eventos",
    newReceiving: "Nueva recepción",
    importCsv: "Importar CSV",
    readOnlySummary: "Resumen de transformación",
    summaryHint: "Resumen de solo lectura del registro de eventos.",
    draft: "Borrador",
    finalized: "Finalizado",
    amended: "Modificado",
    void: "Anulado",
  },
} as const;
