import {
  platformAuditContracts,
  platformAuthContracts,
  platformCatalogContracts,
  platformCatalogV2Contracts,
  platformCatalogV3Contracts,
  platformTenantV3Contracts,
  entitlementSourceListSchema,
  entitlementImpactSchema,
  entitlementSourcePreviewRequestSchema,
  entitlementSourcePreviewSchema,
  entitlementSourceConfirmSchema,
  entitlementSourceConfirmationSchema,
  platformTenantV2Contracts,
  platformCommercialContracts,
  platformOfferDraftContracts,
  platformCommercialV2Contracts,
  platformOperationsContracts,
  platformAgreementContracts,
  platformOfferWorkspaceContracts,
  platformOfferWorkspaceV2Contracts,
  platformNationalCatalogContracts,
  platformTeamContracts,
  platformTenantContracts,
  platformReportContracts,
  platformErrorSchema,
  platformDeviceLicensingContracts,
  platformDeviceReplacementContracts,
  platformDeviceRetentionContracts,
} from "@markiro/platform-contracts";
import type { ZodType } from "zod";

export type PlatformHttpMethod = "delete" | "get" | "post" | "patch";
export type PlatformSuccessStatus = "200" | "201";

export interface PlatformRouteContract {
  method: PlatformHttpMethod;
  path: string;
  status: PlatformSuccessStatus;
  response: ZodType;
  commercialV2?: { response: ZodType; body?: ZodType };
  commercialV3?: { response: ZodType; body?: ZodType };
  body?: ZodType;
  query?: ZodType;
  errors?: ReadonlyArray<{ status: string; schema: ZodType }>;
  multipart?: true;
  public?: true;
}

const route = (
  method: PlatformHttpMethod,
  path: string,
  status: PlatformSuccessStatus,
  response: ZodType,
  options: Pick<
    PlatformRouteContract,
    "body" | "query" | "errors" | "multipart" | "public" | "commercialV2" | "commercialV3"
  > = {},
): PlatformRouteContract => ({ method, path, status, response, ...options });

export const CURRENT_SAAS_ROUTES = [
  route(
    "get",
    "/platform/tenants/{tenantId}/device-licensing/retention",
    "200",
    platformDeviceRetentionContracts.inspect.response,
  ),
  route(
    "post",
    "/platform/tenants/{tenantId}/device-licensing/retention/preview",
    "200",
    platformDeviceRetentionContracts.preview.response,
    { body: platformDeviceRetentionContracts.preview.body },
  ),
  route(
    "post",
    "/platform/tenants/{tenantId}/device-licensing/retention/confirm",
    "200",
    platformDeviceRetentionContracts.confirm.response,
    { body: platformDeviceRetentionContracts.confirm.body },
  ),
  route(
    "get",
    "/platform/tenants/{tenantId}/device-licensing/replacements",
    "200",
    platformDeviceReplacementContracts.list.response,
  ),
  route(
    "post",
    "/platform/tenants/{tenantId}/device-licensing/{deviceId}/replacements/preview",
    "200",
    platformDeviceReplacementContracts.preview.response,
    { body: platformDeviceReplacementContracts.preview.body },
  ),
  route(
    "post",
    "/platform/tenants/{tenantId}/device-licensing/{deviceId}/replacements/confirm",
    "200",
    platformDeviceReplacementContracts.confirm.response,
    { body: platformDeviceReplacementContracts.confirm.body },
  ),
  route(
    "post",
    "/platform/tenants/{tenantId}/device-licensing/replacements/{preparationId}/cancel",
    "200",
    platformDeviceReplacementContracts.cancel.response,
    { body: platformDeviceReplacementContracts.cancel.body },
  ),
  route(
    "get",
    "/platform/tenants/{tenantId}/device-licensing",
    "200",
    platformDeviceLicensingContracts.inspect.response,
  ),
  route(
    "post",
    "/platform/tenants/{tenantId}/device-licensing/{deviceId}/cancel-reservation",
    "200",
    platformDeviceLicensingContracts.cancelReservation.response,
    { body: platformDeviceLicensingContracts.cancelReservation.body },
  ),
  route("post", "/platform/reports", "201", platformReportContracts.create.response, {
    body: platformReportContracts.create.body,
  }),
  route("get", "/platform/reports", "200", platformReportContracts.list.response, {
    query: platformReportContracts.list.query,
  }),
  route("get", "/platform/reports/options", "200", platformReportContracts.options.response, {
    query: platformReportContracts.options.query,
  }),
  route(
    "post",
    "/platform/reports/{id}/download",
    "200",
    platformReportContracts.download.response,
    { errors: [{ status: "410", schema: platformErrorSchema }] },
  ),
  route("get", "/platform/me", "200", platformAuthContracts.me.response),
  route(
    "post",
    "/platform/activation/complete",
    "201",
    platformAuthContracts.activationComplete.response,
    { body: platformAuthContracts.activationComplete.body, public: true },
  ),
  route("get", "/platform/team", "200", platformTeamContracts.list.response),
  route("post", "/platform/team", "201", platformTeamContracts.invite.response, {
    body: platformTeamContracts.invite.body,
  }),
  route("patch", "/platform/team/{id}/role", "200", platformTeamContracts.changeRole.response, {
    body: platformTeamContracts.changeRole.body,
  }),
  route("post", "/platform/team/{id}/suspend", "201", platformTeamContracts.suspend.response),
  route(
    "post",
    "/platform/team/{id}/activation/renew",
    "201",
    platformTeamContracts.renewActivation.response,
  ),
  route(
    "post",
    "/platform/team/{id}/2fa/recover",
    "201",
    platformTeamContracts.recoverTwoFactor.response,
  ),
  route("get", "/platform/audit", "200", platformAuditContracts.list.response),
  route(
    "get",
    "/platform/operations/overview",
    "200",
    platformOperationsContracts.overview.response,
  ),
  route(
    "get",
    "/platform/operations/monitoring",
    "200",
    platformOperationsContracts.monitoring.response,
  ),
  route(
    "post",
    "/platform/operations/national-catalog/schema-refresh",
    "200",
    platformNationalCatalogContracts.refresh.response,
    { body: platformNationalCatalogContracts.refresh.body },
  ),
  route(
    "post",
    "/platform/operations/national-catalog/schema-versions/{id}/activate",
    "200",
    platformNationalCatalogContracts.activate.response,
  ),
  route(
    "post",
    "/platform/operations/national-catalog/schema-versions/{id}/attribute-mappings/review",
    "200",
    platformNationalCatalogContracts.reviewAttributeMappings.response,
    { body: platformNationalCatalogContracts.reviewAttributeMappings.body },
  ),
  route(
    "post",
    "/platform/operations/national-catalog/group-mappings/{code}/review",
    "200",
    platformNationalCatalogContracts.reviewGroupMapping.response,
    { body: platformNationalCatalogContracts.reviewGroupMapping.body },
  ),
  route("get", "/platform/tenants/{id}/entitlements", "200", entitlementSourceListSchema),
  route("get", "/platform/tenants/{id}/entitlements/sources", "200", entitlementSourceListSchema),
  route("get", "/platform/tenants/{id}/entitlements/impact", "200", entitlementImpactSchema),
  route(
    "post",
    "/platform/tenants/{id}/entitlements/preview",
    "200",
    entitlementSourcePreviewSchema,
    { body: entitlementSourcePreviewRequestSchema },
  ),
  route(
    "post",
    "/platform/tenants/{id}/entitlements/confirm",
    "200",
    entitlementSourceConfirmationSchema,
    { body: entitlementSourceConfirmSchema },
  ),
  route("get", "/platform/tenants", "200", platformTenantContracts.list.response),
  route("post", "/platform/tenants", "201", platformTenantContracts.create.response, {
    body: platformTenantContracts.create.body,
  }),
  route("get", "/platform/tenants/{id}", "200", platformTenantContracts.detail.response, {
    commercialV2: platformTenantV2Contracts.detail,
    commercialV3: platformTenantV3Contracts.detail,
  }),
  route(
    "post",
    "/platform/tenants/{id}/owner-activation/renew",
    "200",
    platformTenantContracts.renewActivation.response,
  ),
  route(
    "post",
    "/platform/tenants/{id}/subscription/plan",
    "201",
    platformTenantContracts.assignPlan.response,
    {
      body: platformTenantContracts.assignPlan.body,
      commercialV2: platformTenantV2Contracts.assignPlan,
    },
  ),
  route(
    "post",
    "/platform/tenants/{id}/subscription/addons",
    "201",
    platformTenantContracts.assignAddon.response,
    {
      body: platformTenantContracts.assignAddon.body,
      commercialV2: platformTenantV2Contracts.assignAddon,
      commercialV3: platformTenantV3Contracts.assignAddon,
    },
  ),
  route(
    "get",
    "/platform/catalog/editor-context",
    "200",
    platformCatalogV2Contracts.editorContext.response,
    {
      commercialV2: platformCatalogV2Contracts.editorContext,
      commercialV3: platformCatalogV3Contracts.editorContext,
    },
  ),
  route(
    "post",
    "/platform/catalog/items/{id}/versions/{versionId}/review",
    "200",
    platformCatalogV2Contracts.reviewVersion.response,
    {
      commercialV2: platformCatalogV2Contracts.reviewVersion,
      commercialV3: platformCatalogV3Contracts.reviewVersion,
    },
  ),
  route("get", "/platform/catalog/items", "200", platformCatalogContracts.list.response, {
    commercialV2: platformCatalogV2Contracts.list,
    commercialV3: platformCatalogV3Contracts.list,
  }),
  route(
    "get",
    "/platform/catalog/items/{id}/versions",
    "200",
    platformCatalogContracts.listVersions.response,
    {
      commercialV2: platformCatalogV2Contracts.listVersions,
      commercialV3: platformCatalogV3Contracts.listVersions,
    },
  ),
  route(
    "get",
    "/platform/catalog/items/{id}/versions/{versionId}",
    "200",
    platformCatalogContracts.getVersion.response,
    {
      commercialV2: platformCatalogV2Contracts.getVersion,
      commercialV3: platformCatalogV3Contracts.getVersion,
    },
  ),
  route(
    "post",
    "/platform/catalog/items/{id}/versions",
    "201",
    platformCatalogContracts.createVersion.response,
    {
      commercialV2: platformCatalogV2Contracts.createVersion,
      commercialV3: platformCatalogV3Contracts.createVersion,
      body: platformCatalogContracts.createVersion.body,
    },
  ),
  route(
    "patch",
    "/platform/catalog/items/{id}/versions/{versionId}",
    "200",
    platformCatalogContracts.updateVersion.response,
    {
      commercialV2: platformCatalogV2Contracts.updateVersion,
      commercialV3: platformCatalogV3Contracts.updateVersion,
      body: platformCatalogContracts.updateVersion.body,
    },
  ),
  route(
    "post",
    "/platform/catalog/items/{id}/versions/{versionId}/publish",
    "200",
    platformCatalogContracts.publishVersion.response,
    {
      commercialV2: platformCatalogV2Contracts.publishVersion,
      commercialV3: platformCatalogV3Contracts.publishVersion,
    },
  ),
  route(
    "post",
    "/platform/catalog/items/{id}/versions/{versionId}/retire",
    "200",
    platformCatalogContracts.retireVersion.response,
    {
      commercialV2: platformCatalogV2Contracts.retireVersion,
      commercialV3: platformCatalogV3Contracts.retireVersion,
    },
  ),
  route(
    "post",
    "/platform/catalog/items/{id}/archive",
    "200",
    platformCatalogContracts.archiveItem.response,
  ),
  route(
    "get",
    "/platform/settings/demo-plan",
    "200",
    platformCatalogContracts.getDefaultDemo.response,
  ),
  route(
    "patch",
    "/platform/settings/demo-plan",
    "200",
    platformCatalogContracts.setDefaultDemo.response,
    {
      body: platformCatalogContracts.setDefaultDemo.body,
      commercialV2: platformCatalogV2Contracts.setDefaultDemo,
      commercialV3: platformCatalogV3Contracts.setDefaultDemo,
    },
  ),
  route("get", "/platform/agreements", "200", platformAgreementContracts.list.response, {
    query: platformAgreementContracts.list.query,
  }),
  route("get", "/platform/agreements/{id}", "200", platformAgreementContracts.detail.response),
  route(
    "get",
    "/platform/agreements/{id}/tenant-candidates",
    "200",
    platformAgreementContracts.tenantCandidates.response,
  ),
  route("post", "/platform/agreements", "201", platformAgreementContracts.create.response, {
    body: platformAgreementContracts.create.body,
  }),
  route("post", "/platform/agreements/{id}", "200", platformAgreementContracts.update.response, {
    body: platformAgreementContracts.update.body,
  }),
  route(
    "post",
    "/platform/agreements/{id}/transition",
    "200",
    platformAgreementContracts.transition.response,
    { body: platformAgreementContracts.transition.body },
  ),
  route(
    "post",
    "/platform/agreements/{id}/tenant",
    "200",
    platformAgreementContracts.linkTenant.response,
    { body: platformAgreementContracts.linkTenant.body },
  ),
  route(
    "delete",
    "/platform/agreements/{id}/tenant",
    "200",
    platformAgreementContracts.unlinkTenant.response,
  ),
  route(
    "post",
    "/platform/agreements/{id}/documents/draft",
    "200",
    platformAgreementContracts.documents.render.response,
  ),
  route(
    "post",
    "/platform/agreements/{id}/documents/{documentId}/download",
    "200",
    platformAgreementContracts.documents.download.response,
  ),
  route(
    "post",
    "/platform/agreements/{id}/attachments",
    "201",
    platformAgreementContracts.attachments.upload.response,
    { multipart: true },
  ),
  route(
    "delete",
    "/platform/agreements/{id}/attachments/{documentId}",
    "200",
    platformAgreementContracts.attachments.delete.response,
  ),
  route("get", "/platform/offers", "200", platformCommercialContracts.offers.list.response),
  route(
    "get",
    "/platform/offers/registry",
    "200",
    platformOfferWorkspaceContracts.registry.response,
    { query: platformOfferWorkspaceContracts.registry.query },
  ),
  route(
    "get",
    "/platform/offers/{id}/workspace",
    "200",
    platformOfferWorkspaceContracts.workspace.response,
    { commercialV2: platformOfferWorkspaceV2Contracts.workspace },
  ),
  route("get", "/platform/offers/{id}", "200", platformCommercialContracts.offers.detail.response, {
    commercialV2: platformCommercialV2Contracts.offers.detail,
  }),
  route(
    "get",
    "/platform/offers/{id}/preview",
    "200",
    platformOfferWorkspaceContracts.preview.response,
  ),
  route(
    "patch",
    "/platform/offers/{id}/draft",
    "200",
    platformOfferDraftContracts.update.response,
    {
      body: platformOfferDraftContracts.update.body,
    },
  ),
  route("post", "/platform/offers", "201", platformCommercialContracts.offers.create.response, {
    body: platformCommercialContracts.offers.create.body,
    commercialV2: platformCommercialV2Contracts.offers.create,
  }),
  route(
    "post",
    "/platform/offers/{id}/revise",
    "201",
    platformCommercialContracts.offers.revise.response,
    {
      body: platformCommercialContracts.offers.revise.body,
      commercialV2: platformCommercialV2Contracts.offers.revise,
    },
  ),
  route(
    "post",
    "/platform/offers/{id}/publish",
    "200",
    platformCommercialContracts.offers.publish.response,
    {
      body: platformCommercialContracts.offers.publish.body,
      commercialV2: platformCommercialV2Contracts.offers.publish,
    },
  ),
  route(
    "get",
    "/platform/offers/{id}/documents",
    "200",
    platformCommercialContracts.offers.documents.list.response,
  ),
  route(
    "post",
    "/platform/offers/{id}/documents",
    "201",
    platformCommercialContracts.offers.documents.render.response,
    { body: platformCommercialContracts.offers.documents.render.body },
  ),
  route(
    "get",
    "/platform/offers/{id}/documents/{documentId}/download",
    "200",
    platformCommercialContracts.offers.documents.download.response,
  ),
  route(
    "post",
    "/platform/offers/{id}/cancel",
    "200",
    platformCommercialContracts.offers.cancel.response,
    { commercialV2: platformCommercialV2Contracts.offers.cancel },
  ),
  route(
    "post",
    "/platform/offers/{id}/payment",
    "201",
    platformCommercialContracts.offers.payment.response,
    { body: platformCommercialContracts.offers.payment.body },
  ),
  route("get", "/platform/invoices", "200", platformCommercialContracts.invoices.list.response),
  route(
    "get",
    "/platform/invoices/{id}",
    "200",
    platformCommercialContracts.invoices.detail.response,
    { commercialV2: platformCommercialV2Contracts.invoices.detail },
  ),
  route("post", "/platform/invoices", "201", platformCommercialContracts.invoices.create.response, {
    body: platformCommercialContracts.invoices.create.body,
    commercialV2: platformCommercialV2Contracts.invoices.create,
  }),
  route(
    "post",
    "/platform/invoices/{id}/issue",
    "201",
    platformCommercialContracts.invoices.issue.response,
    { body: platformCommercialContracts.invoices.issue.body },
  ),
  route(
    "post",
    "/platform/invoices/{id}/document",
    "201",
    platformCommercialContracts.invoices.document.response,
    { body: platformCommercialContracts.invoices.document.body },
  ),
  route(
    "get",
    "/platform/invoices/{id}/documents",
    "200",
    platformCommercialContracts.invoices.documents.list.response,
  ),
  route(
    "post",
    "/platform/invoices/{id}/documents",
    "201",
    platformCommercialContracts.invoices.documents.render.response,
    { body: platformCommercialContracts.invoices.documents.render.body },
  ),
  route(
    "get",
    "/platform/invoices/{id}/document",
    "200",
    platformCommercialContracts.invoices.documentUrl.response,
  ),
  route(
    "get",
    "/platform/invoices/{id}/documents/{documentId}/download",
    "200",
    platformCommercialContracts.invoices.documents.download.response,
  ),
  route(
    "post",
    "/platform/invoices/{id}/apply",
    "201",
    platformCommercialContracts.invoices.apply.response,
    { body: platformCommercialContracts.invoices.apply.body },
  ),
  route(
    "post",
    "/platform/invoices/{id}/cancel",
    "201",
    platformCommercialContracts.invoices.cancel.response,
  ),
  route(
    "delete",
    "/platform/invoices/{id}",
    "200",
    platformCommercialContracts.invoices.delete.response,
  ),
  route(
    "get",
    "/platform/billing/requests",
    "200",
    platformCommercialContracts.billingRequests.list.response,
    { query: platformCommercialContracts.billingRequests.list.query },
  ),
  route(
    "get",
    "/platform/billing/requests/{id}",
    "200",
    platformCommercialContracts.billingRequests.detail.response,
  ),
  route(
    "get",
    "/platform/billing/requests/{id}/link-targets",
    "200",
    platformCommercialContracts.billingRequests.linkTargets.response,
    { query: platformCommercialContracts.billingRequests.linkTargets.query },
  ),
  route(
    "post",
    "/platform/billing/requests/{id}/offer",
    "201",
    platformCommercialContracts.billingRequests.createOffer.response,
    {
      body: platformCommercialContracts.billingRequests.createOffer.body,
      commercialV2: platformCommercialV2Contracts.billingRequests.createOffer,
    },
  ),
  route(
    "post",
    "/platform/billing/requests/{id}/comments",
    "201",
    platformCommercialContracts.billingRequests.comment.response,
    { body: platformCommercialContracts.billingRequests.comment.body },
  ),
  route(
    "post",
    "/platform/billing/requests/{id}/status",
    "201",
    platformCommercialContracts.billingRequests.status.response,
    { body: platformCommercialContracts.billingRequests.status.body },
  ),
  route(
    "post",
    "/platform/billing/requests/{id}/links",
    "201",
    platformCommercialContracts.billingRequests.link.response,
    { body: platformCommercialContracts.billingRequests.link.body },
  ),
  route(
    "get",
    "/platform/billing/acts",
    "200",
    platformCommercialContracts.billingActs.list.response,
    { query: platformCommercialContracts.billingActs.list.query },
  ),
  route(
    "get",
    "/platform/billing/acts/{id}",
    "200",
    platformCommercialContracts.billingActs.detail.response,
  ),
  route(
    "post",
    "/platform/billing/acts",
    "201",
    platformCommercialContracts.billingActs.create.response,
    {
      body: platformCommercialContracts.billingActs.create.body,
    },
  ),
  route(
    "post",
    "/platform/billing/acts/{id}/issue",
    "201",
    platformCommercialContracts.billingActs.issue.response,
    {
      body: platformCommercialContracts.billingActs.issue.body,
    },
  ),
  route(
    "post",
    "/platform/billing/acts/{id}/cancel",
    "201",
    platformCommercialContracts.billingActs.cancel.response,
    { body: platformCommercialContracts.billingActs.cancel.body },
  ),
  route(
    "get",
    "/platform/billing/acts/{id}/documents/{documentId}/download",
    "200",
    platformCommercialContracts.billingActs.documents.download.response,
  ),
  route("get", "/platform/payments", "200", platformCommercialContracts.payments.list.response),
  route(
    "get",
    "/platform/payments/matches",
    "200",
    platformCommercialContracts.payments.matches.list.response,
  ),
  route(
    "patch",
    "/platform/payments/matches/{matchId}",
    "200",
    platformCommercialContracts.payments.matches.resolve.response,
    { body: platformCommercialContracts.payments.matches.resolve.body },
  ),
  route(
    "post",
    "/platform/payments/invoices/{invoiceId}",
    "201",
    platformCommercialContracts.payments.manual.response,
    { body: platformCommercialContracts.payments.manual.body },
  ),
  route(
    "post",
    "/platform/payments/imports",
    "201",
    platformCommercialContracts.payments.import.response,
    { body: platformCommercialContracts.payments.import.body },
  ),
  route(
    "get",
    "/platform/billing/operator/accounts",
    "200",
    platformCommercialContracts.billingAccounts.operator.list.response,
  ),
  route(
    "post",
    "/platform/billing/operator/accounts",
    "201",
    platformCommercialContracts.billingAccounts.operator.create.response,
    { body: platformCommercialContracts.billingAccounts.operator.create.body },
  ),
  route(
    "patch",
    "/platform/billing/operator/accounts/{accountId}/default",
    "200",
    platformCommercialContracts.billingAccounts.operator.setDefault.response,
  ),
  route(
    "post",
    "/platform/billing/operator/accounts/{accountId}/archive",
    "200",
    platformCommercialContracts.billingAccounts.operator.archive.response,
    { body: platformCommercialContracts.billingAccounts.operator.archive.body },
  ),
  route(
    "get",
    "/platform/billing/tenants/{tenantId}/accounts",
    "200",
    platformCommercialContracts.billingAccounts.tenant.list.response,
  ),
  route(
    "post",
    "/platform/billing/tenants/{tenantId}/accounts",
    "201",
    platformCommercialContracts.billingAccounts.tenant.create.response,
    { body: platformCommercialContracts.billingAccounts.tenant.create.body },
  ),
  route(
    "patch",
    "/platform/billing/tenants/{tenantId}/accounts/{accountId}/default",
    "200",
    platformCommercialContracts.billingAccounts.tenant.setDefault.response,
  ),
  route(
    "post",
    "/platform/billing/tenants/{tenantId}/accounts/{accountId}/archive",
    "200",
    platformCommercialContracts.billingAccounts.tenant.archive.response,
    { body: platformCommercialContracts.billingAccounts.tenant.archive.body },
  ),
  route(
    "get",
    "/platform/suggestions/organizations",
    "200",
    platformCommercialContracts.dadata.organizations.response,
  ),
  route(
    "get",
    "/platform/suggestions/addresses",
    "200",
    platformCommercialContracts.dadata.addresses.response,
  ),
  route(
    "get",
    "/platform/suggestions/banks",
    "200",
    platformCommercialContracts.dadata.banks.response,
  ),
  route(
    "get",
    "/platform/suggestions/status",
    "200",
    platformCommercialContracts.dadata.status.response,
  ),
] as const satisfies readonly PlatformRouteContract[];

export const CURRENT_SAAS_ROUTE_KEYS = CURRENT_SAAS_ROUTES.map(
  ({ method, path }) => `${method.toUpperCase()} ${path}`,
).sort();
