export const lotCopy = {
  "en-US": {
    title: "Lots",
    intro: "Lot identity, source and controlled status changes.",
    add: "Add imported lot",
    save: "Save lot",
    back: "Back to lots",
    search: "TLC or source reference",
    tlc: "Lot code (TLC)",
    product: "Product",
    source: "TLC source",
    status: "Status",
    basis: "Assignment basis",
    imported: "Imported",
    assigned: "Assigned",
    inherited: "Inherited",
    sourceKind: "Source type",
    absent: "Not provided",
    location: "Location",
    reference: "Web reference",
    referenceValue: "Source reference URL",
    resolvedLocation: "Resolved source location",
    referenceHint:
      "Enter an HTTP(S) reference and its resolved location. Markiro does not open or fetch this URL.",
    choose: "Select…",
    productSearch: "Search active products",
    locationSearch: "Search active locations",
    noChoices: "No active records match this search.",
    selectedId: "Selected record · {{id}}",
    correct: "Correct source",
    saveSource: "Save source correction",
    changeStatus: "Change status",
    saveStatus: "Save status change",
    sourceIntro:
      "The lot ID, TLC and product stay unchanged. A reason and the current record version are required.",
    statusIntro:
      "Only allowed transitions are offered; every change needs a reason. A manual status change does not recalculate balances.",
    reason: "Reason",
    newStatus: "New status",
    currentStatus: "Current status",
    revision: "Record version",
    auditNote:
      "The actor, time, reason, and previous and new values are recorded in the audit log.",
    id: "Lot ID",
    createdAt: "Created",
    updatedAt: "Updated",
    createdBy: "Created by · actor ID",
    updatedBy: "Updated by · actor ID",
    timezone: "Dates are shown in {{zone}}.",
    currentNames:
      "Product and location names are current reference data, not a historical event snapshot.",
    generic: "General lot traceability only. FTR applicability is not assessed in this profile.",
    unavailableFeatures: "Full event history, genealogy and balances are not connected yet.",
    receivingBasis: "Current receiving basis",
    receivingMissing: "No current receiving basis",
    receivingCount: "Supporting revisions: {{count}}",
    receivingLines: "Lines: {{lines}}",
    receivingHint:
      "Current finalized receipts linked to this lot. This does not change its status or source lock, or confirm inventory or export readiness.",
    receivingLoading: "Loading receiving basis…",
    receivingError: "The receiving basis could not be loaded.",
    receivingRefresh: "Refresh receiving basis",
    receivingEmptyPage:
      "No entries on this page. Return to the previous page or refresh the basis.",
    receivingOpening: "Opening receiving revision…",
    receivingOpenError:
      "This receiving revision could not be opened. Retry the revision or refresh its current basis.",
    backToLot: "Back to lot",
    sourceLocked: "The source is locked after finalized use and cannot be corrected.",
    sourceUnlocked: "The source may be corrected until its first use in a finalized event.",
    loading: "Loading lots…",
    loadingDetail: "Loading lot…",
    empty: "No lots match these filters.",
    loadError: "The lots could not be loaded.",
    reloadError: "The lot could not be reloaded. Your draft was kept.",
    reload: "Reload lot",
    invalid: "Check the product, TLC, source, status and required reason before saving.",
    failed:
      "The result could not be confirmed. Your input was kept. Reload the lot or check the registry before trying again.",
    conflict: "This lot changed while you were editing. Reload the lot before saving again.",
    locked: "The source was locked by finalized use. Reload the lot before continuing.",
    archivedReference:
      "The selected product or source location is archived. Select an active record or restore it in reference data.",
    duplicate: "This source and TLC already exist.",
    openExisting: "Open existing lot",
    saved: "Lot saved.",
    corrected: "Source correction saved.",
    statusSaved: "Lot status changed.",
    permission: "This action is no longer available with your current access. Your draft was kept.",
    referenceLoadError:
      "Reference data could not be loaded. You can retry; the selected identity was kept.",
    states: {
      active: "Active",
      consumed: "Consumed",
      shipped: "Shipped",
      quarantined: "Quarantined",
      recalled: "Recalled",
      archived: "Archived",
    },
  },
  "es-US": {
    title: "Lotes",
    intro: "Identidad, fuente y cambios controlados de estado de los lotes.",
    add: "Añadir lote importado",
    save: "Guardar lote",
    back: "Volver a los lotes",
    search: "TLC o referencia de fuente",
    tlc: "Código de lote (TLC)",
    product: "Producto",
    source: "Fuente del TLC",
    status: "Estado",
    basis: "Base de asignación",
    imported: "Importado",
    assigned: "Asignado",
    inherited: "Heredado",
    sourceKind: "Tipo de fuente",
    absent: "No proporcionada",
    location: "Ubicación",
    reference: "Referencia web",
    referenceValue: "URL de referencia de la fuente",
    resolvedLocation: "Ubicación resuelta de la fuente",
    referenceHint:
      "Introduzca una referencia HTTP(S) y su ubicación resuelta. Markiro no abre ni consulta esta URL.",
    choose: "Seleccionar…",
    productSearch: "Buscar productos activos",
    locationSearch: "Buscar ubicaciones activas",
    noChoices: "Ningún registro activo coincide con la búsqueda.",
    selectedId: "Registro seleccionado · {{id}}",
    correct: "Corregir fuente",
    saveSource: "Guardar corrección de fuente",
    changeStatus: "Cambiar estado",
    saveStatus: "Guardar cambio de estado",
    sourceIntro:
      "El ID, el TLC y el producto del lote no cambian. Se requieren un motivo y la versión actual del registro.",
    statusIntro:
      "Solo se ofrecen transiciones permitidas; cada cambio requiere un motivo. Un cambio manual de estado no recalcula los saldos.",
    reason: "Motivo",
    newStatus: "Nuevo estado",
    currentStatus: "Estado actual",
    revision: "Versión del registro",
    auditNote:
      "El actor, la fecha, el motivo y los valores anteriores y nuevos se registran en el historial de auditoría.",
    id: "ID del lote",
    createdAt: "Creado",
    updatedAt: "Actualizado",
    createdBy: "Creado por · ID del actor",
    updatedBy: "Actualizado por · ID del actor",
    timezone: "Las fechas se muestran en {{zone}}.",
    currentNames:
      "Los nombres de productos y ubicaciones son datos de referencia actuales, no una copia histórica de un evento.",
    generic:
      "Solo trazabilidad general de lotes. La aplicabilidad de FTR no se evalúa en este perfil.",
    unavailableFeatures:
      "El historial completo de eventos, la genealogía y los saldos aún no están conectados.",
    receivingBasis: "Base de recepción vigente",
    receivingMissing: "Sin base de recepción vigente",
    receivingCount: "Revisiones de respaldo: {{count}}",
    receivingLines: "Líneas: {{lines}}",
    receivingHint:
      "Recepciones finalizadas vigentes vinculadas a este lote. Esto no cambia su estado ni el bloqueo de su fuente, ni confirma el inventario o la preparación para exportar.",
    receivingLoading: "Cargando la base de recepción…",
    receivingError: "No se pudo cargar la base de recepción.",
    receivingRefresh: "Actualizar la base de recepción",
    receivingEmptyPage:
      "No hay entradas en esta página. Vuelva a la página anterior o actualice la base.",
    receivingOpening: "Abriendo la revisión de recepción…",
    receivingOpenError:
      "No se pudo abrir esta revisión de recepción. Reintente la revisión o actualice su base vigente.",
    backToLot: "Volver al lote",
    sourceLocked:
      "La fuente está bloqueada tras su uso en un evento finalizado y no se puede corregir.",
    sourceUnlocked: "La fuente se puede corregir hasta su primer uso en un evento finalizado.",
    loading: "Cargando lotes…",
    loadingDetail: "Cargando lote…",
    empty: "Ningún lote coincide con estos filtros.",
    loadError: "No se pudieron cargar los lotes.",
    reloadError: "No se pudo volver a cargar el lote. Se conservó el borrador.",
    reload: "Volver a cargar el lote",
    invalid:
      "Revise el producto, el TLC, la fuente, el estado y el motivo obligatorio antes de guardar.",
    failed:
      "No se pudo confirmar el resultado. Se conservó lo introducido. Vuelva a cargar el lote o consulte el registro antes de reintentar.",
    conflict: "Este lote cambió durante la edición. Vuelva a cargarlo antes de guardar de nuevo.",
    locked:
      "La fuente se bloqueó por su uso en un evento finalizado. Vuelva a cargar el lote para continuar.",
    archivedReference:
      "El producto o la ubicación de origen seleccionados están archivados. Seleccione un registro activo o restáurelo en los datos de referencia.",
    duplicate: "Esta fuente y este TLC ya existen.",
    openExisting: "Abrir lote existente",
    saved: "Lote guardado.",
    corrected: "Corrección de fuente guardada.",
    statusSaved: "Estado del lote cambiado.",
    permission: "Su acceso actual ya no permite esta acción. Se conservó el borrador.",
    referenceLoadError:
      "No se pudieron cargar los datos de referencia. Puede reintentar; se conservó la identidad seleccionada.",
    states: {
      active: "Activo",
      consumed: "Consumido",
      shipped: "Enviado",
      quarantined: "En cuarentena",
      recalled: "Retirado",
      archived: "Archivado",
    },
  },
} as const;
