export const planCopy = {
  "en-US": {
    title: "Plan",
    intro: "Versioned traceability procedures and their frozen evidence.",
    newDraft: "New draft",
    draftUnavailable: "A draft is not effective until approved.",
    editDraft: "Edit draft",
    createHint: "Start with the effective plan's statements, or an empty first draft.",
    createError: "The draft could not be created. Refresh the versions before trying again.",
    creating: "Creating draft…",
    saveDraft: "Save draft",
    saving: "Saving draft…",
    unsaved: "Unsaved changes",
    savedRevision: "Saved revision {{revision}}",
    summaryRequired: "A change summary is required from version 2 onward.",
    currentContext:
      "Current settings only. Approval captures a new frozen snapshot; source links open current locations and product coverage.",
    operatorHelp:
      "Plain-text statements supplied by an operator; not verified procedures or evidence of successful backup or recovery. Maximum 4096 characters per field and 50 entries per list.",
    farmHelp:
      "Declare the actual activity of this operation. The processor profile does not determine this answer.",
    farmBlocks: "Yes or unknown blocks P0 approval. You can still save this draft.",
    addRow: "Add {{field}}",
    removeRow: "Remove {{field}} {{index}}",
    saveError: "The draft was not saved. Your local text is retained; reconnect and try again.",
    staleDraft:
      "This draft changed on the server or is no longer editable. Your local text is retained. Reload only when ready to discard local edits.",
    writeForbidden: "Your access changed. Editing is disabled and local text is retained.",
    reloadDiscard: "Reload and discard local edits",
    draftOpen: "v{{version}} is open",
    loading: "Loading plan versions…",
    detailLoading: "Loading version…",
    listError: "Plan versions could not be loaded. Try again when connected.",
    detailError: "This version could not be loaded. Try again when connected.",
    forbidden: "Your current access does not allow this Plan view.",
    unavailable: "Plan is available only for the processor profile.",
    session: "Your session has ended. Sign in again.",
    missing: "This version is no longer available.",
    retry: "Try again",
    empty: "No plan yet",
    emptyHelp:
      "A traceability plan records procedures designed to support applicable FSMA 204 recordkeeping requirements. A QA manager can prepare a draft.",
    noEffective: "No effective plan. A draft is not an approved record.",
    versions: "Plan versions",
    version: "Version",
    status: "Status",
    effectiveDate: "Effective date",
    provenance: "Provenance",
    retention: "Retain through",
    actions: "Actions",
    view: "View v{{version}}",
    close: "Close version",
    back: "Back to Plan",
    draft: "Draft",
    effective: "Effective",
    superseded: "Superseded",
    draftMark: "DRAFT — not effective",
    synthetic: "Synthetic demo — not an operational record",
    operational: "Operational record",
    notEffective: "Not effective",
    noExpiry: "No expiry while effective",
    indefinite: "Retained indefinitely",
    hold: "Retention hold",
    dateRange: "Retention date exceeds supported range",
    retentionNote:
      "Prior versions are retained for at least {{years}} calendar years (tenant setting; minimum 2).",
    retentionLimit: "This policy does not verify storage retention, backups or recovery.",
    publicationAvailable:
      "Publication service available. Draft approval still requires server validation.",
    publicationUnavailable:
      "Publication unavailable: artifact storage is not configured. Drafts are not publishable until it is ready.",
    configurationChanged: "Configuration changed since the effective plan was approved.",
    versionConfigurationChanged:
      "Current configuration differs from this version's frozen snapshot.",
    currentImpact: "Current impact for v{{version}}",
    effectiveImpact: "Current impact on the effective plan",
    impactHelp:
      "Current configuration is compared with the saved snapshot. Historical facts remain unchanged.",
    noChanges: "No configuration changes reported.",
    changedLocations: "Changed location IDs",
    changedProducts: "Changed product IDs",
    frozen: "Frozen snapshot",
    frozenHelp:
      "These facts were saved at approval. Source links open current configuration, not the historical record.",
    approval: "Approval record",
    approvedBy: "Approver user ID",
    approvedAt: "Approval time",
    sha256: "PDF SHA-256",
    renderer: "PDF renderer version",
    byteSize: "PDF size (bytes)",
    supersededAt: "Superseded at",
    changeSummary: "Change summary",
    notRecorded: "Not recorded",
    confirmations: "Recorded confirmations",
    confirmationHelp:
      "Attributed statements are not independent verification or compliance certification.",
    configured: "Derived from configuration",
    statements: "Plan statements",
    workflow: "FTL classification workflow",
    sources: "Fact source",
    sourceMissing: "Source not recorded",
    operator_confirmed: "Operator confirmed",
    synthetic_fixture: "Synthetic fixture",
    application_policy: "Application policy",
    operator_pending: "Operator statement — not confirmed",
    confirmedAt: "Confirmed at",
    actor: "Actor user ID",
    policyVersion: "Policy version",
    openProfile: "Open current profile",
    openLocations: "Open current locations",
    openProducts: "Open current products",
    fields: {
      tenantName: "Tenant name",
      profileCode: "Profile",
      baselineVersion: "Baseline version",
      timeZone: "Time zone",
      retentionYears: "Retention years",
      tlcSourceLocations: "TLC source locations",
      productProfiles: "Product classifications",
      tenant: "Tenant",
      profile: "Profile",
      id: "Location ID",
      partyId: "Party ID",
      businessName: "Business name",
      phoneNumber: "Phone",
      addressKind: "Address format",
      streetAddress: "Street address",
      latitude: "Latitude",
      longitude: "Longitude",
      city: "City",
      stateOrRegion: "State or region",
      zipOrPostalCode: "Postal code",
      countryCode: "Country",
      productId: "Product ID",
      revision: "Revision",
      coverageStatus: "Coverage status",
      description: "Location description",
      recordMaintenance: "Record maintenance",
      systemOfRecord: "System of record",
      formats: "Record formats",
      recordLocations: "Record locations",
      responsibleRoles: "Responsible roles",
      backupAndRecovery: "Backup and recovery statement",
      narrative: "Procedures",
      ftlIdentification: "FTL identification",
      procedure: "Procedure",
      reviewCadence: "Review cadence (operator statement)",
      tlcAssignment: "TLC assignment",
      pointOfContact: "Point of contact",
      name: "Contact name",
      title: "Contact title",
      phone: "Contact phone",
      email: "Contact email",
      farmActivity: "Farm activity",
      status: "Farm activity status",
      explanation: "Explanation",
      reviewAndUpdate: "Review and update",
      version: "Workflow version",
      reviewMode: "Review method",
      coverageStatuses: "Supported coverage statuses",
      positiveCoverageStatuses: "Positive coverage statuses",
      positiveCoverageEvidenceFields: "Required positive coverage evidence",
      coverageChangeAuthority: "Coverage change authority",
      reviewerAttribution: "Reviewer attribution",
      reviewTimeAttribution: "Review time attribution",
      reviewCadenceSource: "Review cadence source",
      automaticLegalDetermination: "Automatic legal determination",
      coverageRationale: "Coverage rationale",
      ftlCategory: "FTL category",
      ftlSourceUrl: "FTL source URL",
      ftlSourceVersion: "FTL source version",
      reviewedBy: "Reviewer",
      reviewedAt: "Review time",
      procedures: "Procedures",
      contact: "Contact",
      nonFarmScope: "Non-farm scope",
    },
    values: {
      no: "No",
      yes: "Yes",
      unknown: "Unknown",
      street: "Street address",
      coordinates: "Coordinates",
      manual: "Manual review",
      covered: "Covered",
      contains_ftl_same_form: "Contains FTL food in the same form",
      not_covered: "Not covered",
      exemption_review_required: "Exemption review required",
      "traceability.qa.manage": "QA managers",
      server_actor_on_coverage_change: "Server records the actor when coverage changes",
      server_time_on_coverage_change: "Server records the time when coverage changes",
      operator_narrative: "Operator statement",
      US_FSMA204_PROCESSOR: "US FSMA 204 processor",
    },
  },
  "es-US": {
    title: "Plan",
    intro: "Procedimientos de trazabilidad versionados y sus pruebas conservadas.",
    newDraft: "Nuevo borrador",
    draftUnavailable: "Un borrador no entra en vigor hasta su aprobación.",
    editDraft: "Editar borrador",
    createHint: "Empiece con las declaraciones del plan vigente o con un primer borrador vacío.",
    createError: "No se pudo crear el borrador. Actualice las versiones antes de reintentar.",
    creating: "Creando borrador…",
    saveDraft: "Guardar borrador",
    saving: "Guardando borrador…",
    unsaved: "Cambios sin guardar",
    savedRevision: "Revisión guardada {{revision}}",
    summaryRequired: "Se requiere un resumen de cambios desde la versión 2.",
    currentContext:
      "Solo configuración actual. La aprobación conserva una nueva instantánea; los enlaces abren las ubicaciones y la cobertura de productos actuales.",
    operatorHelp:
      "Declaraciones de texto del operador; no son procedimientos verificados ni pruebas de copias de seguridad o recuperación exitosas. Máximo 4096 caracteres por campo y 50 entradas por lista.",
    farmHelp:
      "Declare la actividad real de esta operación. El perfil de procesador no determina esta respuesta.",
    farmBlocks: "Sí o desconocido bloquea la aprobación P0. Aún puede guardar este borrador.",
    addRow: "Añadir {{field}}",
    removeRow: "Quitar {{field}} {{index}}",
    saveError:
      "No se guardó el borrador. Se conserva el texto local; vuelva a conectarse y reintente.",
    staleDraft:
      "El borrador cambió en el servidor o ya no se puede editar. Se conserva el texto local. Recargue solo cuando esté listo para descartar los cambios locales.",
    writeForbidden: "Su acceso cambió. La edición está desactivada y se conserva el texto local.",
    reloadDiscard: "Recargar y descartar cambios locales",
    draftOpen: "v{{version}} está abierto",
    loading: "Cargando versiones del plan…",
    detailLoading: "Cargando versión…",
    listError: "No se pudieron cargar las versiones. Reintente cuando tenga conexión.",
    detailError: "No se pudo cargar esta versión. Reintente cuando tenga conexión.",
    forbidden: "Su acceso actual no permite ver este plan.",
    unavailable: "El plan solo está disponible para el perfil de procesador.",
    session: "Su sesión ha finalizado. Inicie sesión de nuevo.",
    missing: "Esta versión ya no está disponible.",
    retry: "Reintentar",
    empty: "Aún no hay un plan",
    emptyHelp:
      "Un plan de trazabilidad documenta procedimientos diseñados para apoyar los requisitos de registros aplicables de FSMA 204. Un responsable de calidad puede preparar un borrador.",
    noEffective: "No hay un plan vigente. Un borrador no es un registro aprobado.",
    versions: "Versiones del plan",
    version: "Versión",
    status: "Estado",
    effectiveDate: "Fecha de vigencia",
    provenance: "Procedencia",
    retention: "Conservar hasta",
    actions: "Acciones",
    view: "Ver v{{version}}",
    close: "Cerrar versión",
    back: "Volver al plan",
    draft: "Borrador",
    effective: "Vigente",
    superseded: "Sustituido",
    draftMark: "BORRADOR — no vigente",
    synthetic: "Demostración sintética — no es un registro operativo",
    operational: "Registro operativo",
    notEffective: "No vigente",
    noExpiry: "Sin vencimiento mientras esté vigente",
    indefinite: "Conservación indefinida",
    hold: "Retención de conservación",
    dateRange: "La fecha de conservación excede el rango admitido",
    retentionNote:
      "Las versiones anteriores se conservan al menos {{years}} años calendario (configuración de la organización; mínimo 2).",
    retentionLimit:
      "Esta política no verifica la conservación en almacenamiento, las copias de seguridad ni la recuperación.",
    publicationAvailable:
      "Servicio de publicación disponible. La aprobación del borrador aún requiere validación del servidor.",
    publicationUnavailable:
      "Publicación no disponible: no se ha configurado el almacenamiento de documentos. Los borradores no se pueden publicar hasta que esté listo.",
    configurationChanged: "La configuración cambió desde la aprobación del plan vigente.",
    versionConfigurationChanged:
      "La configuración actual difiere de la instantánea conservada de esta versión.",
    currentImpact: "Impacto actual para v{{version}}",
    effectiveImpact: "Impacto actual en el plan vigente",
    impactHelp:
      "Se compara la configuración actual con la instantánea guardada. Los hechos históricos no cambian.",
    noChanges: "No se informaron cambios de configuración.",
    changedLocations: "ID de ubicaciones modificadas",
    changedProducts: "ID de productos modificados",
    frozen: "Instantánea conservada",
    frozenHelp:
      "Estos hechos se guardaron al aprobar. Los enlaces abren la configuración actual, no el registro histórico.",
    approval: "Registro de aprobación",
    approvedBy: "ID de usuario aprobador",
    approvedAt: "Hora de aprobación",
    sha256: "SHA-256 del PDF",
    renderer: "Versión del generador de PDF",
    byteSize: "Tamaño del PDF (bytes)",
    supersededAt: "Sustituido el",
    changeSummary: "Resumen de cambios",
    notRecorded: "No registrado",
    confirmations: "Confirmaciones registradas",
    confirmationHelp:
      "Las declaraciones atribuidas no son verificación independiente ni certificación de cumplimiento.",
    configured: "Derivado de la configuración",
    statements: "Declaraciones del plan",
    workflow: "Flujo de clasificación FTL",
    sources: "Fuente del dato",
    sourceMissing: "Fuente no registrada",
    operator_confirmed: "Confirmado por el operador",
    synthetic_fixture: "Datos sintéticos",
    application_policy: "Política de la aplicación",
    operator_pending: "Declaración del operador — sin confirmar",
    confirmedAt: "Confirmado el",
    actor: "ID de usuario responsable",
    policyVersion: "Versión de política",
    openProfile: "Abrir perfil actual",
    openLocations: "Abrir ubicaciones actuales",
    openProducts: "Abrir productos actuales",
    fields: {
      tenantName: "Nombre de la organización",
      profileCode: "Perfil",
      baselineVersion: "Versión de referencia",
      timeZone: "Zona horaria",
      retentionYears: "Años de conservación",
      tlcSourceLocations: "Ubicaciones de origen TLC",
      productProfiles: "Clasificaciones de productos",
      tenant: "Organización",
      profile: "Perfil",
      id: "ID de ubicación",
      partyId: "ID de parte",
      businessName: "Nombre comercial",
      phoneNumber: "Teléfono",
      addressKind: "Formato de dirección",
      streetAddress: "Dirección",
      latitude: "Latitud",
      longitude: "Longitud",
      city: "Ciudad",
      stateOrRegion: "Estado o región",
      zipOrPostalCode: "Código postal",
      countryCode: "País",
      productId: "ID de producto",
      revision: "Revisión",
      coverageStatus: "Estado de cobertura",
      description: "Descripción de ubicación",
      recordMaintenance: "Mantenimiento de registros",
      systemOfRecord: "Sistema de registro",
      formats: "Formatos de registro",
      recordLocations: "Ubicaciones de registros",
      responsibleRoles: "Roles responsables",
      backupAndRecovery: "Declaración de copias y recuperación",
      narrative: "Procedimientos",
      ftlIdentification: "Identificación FTL",
      procedure: "Procedimiento",
      reviewCadence: "Frecuencia de revisión (declaración del operador)",
      tlcAssignment: "Asignación de TLC",
      pointOfContact: "Punto de contacto",
      name: "Nombre del contacto",
      title: "Cargo del contacto",
      phone: "Teléfono del contacto",
      email: "Correo del contacto",
      farmActivity: "Actividad agrícola",
      status: "Estado de actividad agrícola",
      explanation: "Explicación",
      reviewAndUpdate: "Revisión y actualización",
      version: "Versión del flujo",
      reviewMode: "Método de revisión",
      coverageStatuses: "Estados de cobertura admitidos",
      positiveCoverageStatuses: "Estados de cobertura positiva",
      positiveCoverageEvidenceFields: "Pruebas requeridas de cobertura positiva",
      coverageChangeAuthority: "Autoridad para cambiar cobertura",
      reviewerAttribution: "Atribución del revisor",
      reviewTimeAttribution: "Atribución de la hora de revisión",
      reviewCadenceSource: "Fuente de frecuencia de revisión",
      automaticLegalDetermination: "Determinación legal automática",
      coverageRationale: "Justificación de cobertura",
      ftlCategory: "Categoría FTL",
      ftlSourceUrl: "URL de fuente FTL",
      ftlSourceVersion: "Versión de fuente FTL",
      reviewedBy: "Revisor",
      reviewedAt: "Hora de revisión",
      procedures: "Procedimientos",
      contact: "Contacto",
      nonFarmScope: "Alcance no agrícola",
    },
    values: {
      no: "No",
      yes: "Sí",
      unknown: "Desconocido",
      street: "Dirección postal",
      coordinates: "Coordenadas",
      manual: "Revisión manual",
      covered: "Cubierto",
      contains_ftl_same_form: "Contiene alimentos FTL en la misma forma",
      not_covered: "No cubierto",
      exemption_review_required: "Requiere revisión de exención",
      "traceability.qa.manage": "Responsables de calidad",
      server_actor_on_coverage_change:
        "El servidor registra al responsable al cambiar la cobertura",
      server_time_on_coverage_change: "El servidor registra la hora al cambiar la cobertura",
      operator_narrative: "Declaración del operador",
      US_FSMA204_PROCESSOR: "Procesador US FSMA 204",
    },
  },
};
