export const shippingCopy = {
  "en-US": {
    new: "New shipment",
    title: "Shipping draft",
    detail: "Shipping detail",
    audit: "Record audit",
    date: "Date shipped",
    shipFrom: "Ship-from",
    recipient: "Immediate subsequent recipient",
    recipientHint: "Select the recipient that receives the food, not the transporter.",
    carrier: "Carrier reference (optional)",
    notes: "Notes",
    lines: "Lots and quantities",
    line: "Line {{number}}",
    lot: "Existing lot",
    addLot: "Add lot",
    removeLine: "Remove line",
    quantity: "Quantity",
    unit: "Unit",
    lotIdentity: "TLC and product come from the selected lot.",
    documents: "Reference documents",
    document: "Reference document",
    addDocument: "Attach document",
    detach: "Detach",
    readiness: "Completeness",
    check: "Check readiness",
    saveFirst: "Save the draft before checking readiness.",
    saveChanges: "Save changes before checking readiness.",
    complete: "Complete — ready to finalize",
    incomplete: "Incomplete — finalization is blocked",
    blockers: "Shipping blockers",
    issueField: {
      record: "Shipping record",
      date: "Date shipped",
      timeZone: "Time zone",
      shipFrom: "Ship-from location",
      recipient: "Immediate recipient",
      documents: "Reference documents",
      items: "Lots and quantities",
      lot: "Existing lot",
      quantity: "Quantity",
      unit: "Unit",
      tlc: "Traceability lot code",
      source: "Lot source",
      product: "Product description",
      coverage: "Product coverage",
      origin: "Lot origin",
    },
    issueFix: {
      required: "Enter or select this required value, then check readiness again.",
      format: "Correct the value or unit format, then check readiness again.",
      unavailable: "Select an available record that belongs to this tenant.",
      inactive: "Select an active record, or reactivate the intended record before checking again.",
      incompleteShipFrom:
        "Complete the ship-from location description in Locations, then check readiness again.",
      incompleteRecipient:
        "Complete the recipient location description in Locations, then check readiness again.",
      incompleteDocument:
        "Complete the attached document type and number, then check readiness again.",
      incompleteProduct:
        "Complete the selected product description in Products, then check readiness again.",
      wrongRole: "Choose a location with the required shipping or recipient role.",
      sameLocation: "Choose a recipient different from the ship-from location.",
      duplicate: "Remove the repeated lot or document from this shipment.",
      statusBlocked: "Choose an active lot that is eligible for shipment.",
      sourceUnresolved: "Resolve the lot source to a complete location description.",
      coverageUnresolved: "Review and resolve the product coverage classification.",
      originMissing: "Record the lot origin before shipping it.",
      balanceUnknown: "Confirm the lot's available balance before finalizing.",
      balanceExhausted: "Choose a lot with remaining balance or remove this line.",
      uomMismatch: "Select the lot's balance unit of measure.",
      overShipment: "Reduce the shipped quantity to the available balance.",
      fallback:
        "Check and correct this field, then run readiness again. Contact support if it persists.",
    },
    save: "Save draft",
    saving: "Saving…",
    invalid: "Check the draft fields and existing-lot selection.",
    loadError: "The Shipping record could not be loaded.",
    saveFailed: "The draft could not be saved. Your input was kept.",
    checkFailed: "Readiness could not be checked. Try again.",
    stale: "The saved record changed. Reload it before another command.",
    uncertain: "The command outcome is unknown. Retry the same operation or reload the record.",
    retrySame: "Retry same operation",
    reload: "Reload record",
    reloadConfirm: "Reload and discard local changes?",
    leaveUncertain: "This command may have succeeded. Leave and abandon local recovery?",
    unavailable: "This Shipping record is unavailable for the current access or profile.",
    downstreamBlocked: "A downstream event blocks this correction. Review the listed records.",
    downstreamItem: "Lot {{lotId}} · Event {{eventId}} · revision {{revision}}",
    downstreamMore: "More downstream blockers exist; this list is limited.",
    finalize: "Finalize shipment",
    finalizeConfirm: "Finalize this saved Shipping record and freeze its KDEs?",
    finalizeQuantity: "Recorded quantity: {{quantity}}",
    noCaseClaim: "This record does not identify shipped cases or prove physical dispatch.",
    confirmFinalization: "Confirm finalization",
    amendment: "Start amendment",
    void: "Void shipment",
    cancelAmendment: "Cancel amendment",
    actionReason: "QA reason",
    confirmAmendment: "Confirm amendment",
    confirmVoid: "Confirm void",
    confirmCancellation: "Confirm cancellation",
    amendmentHint:
      "Create a new draft revision. The current finalized revision remains effective until the amendment is finalized.",
    voidHint: "Exclude this record from current trace. Its frozen history remains readable.",
    cancelAmendmentHint:
      "Void only this pending amendment draft. The predecessor remains the current finalized shipment.",
    cancel: "Cancel",
    revision: "Revision {{number}}",
    current: "Current revision",
    pending: "Pending draft",
    previous: "Previous revision",
    successor: "Superseded by",
    finalizedBy: "Finalized by",
    voidReason: "Void reason",
    amendedReason: "Amendment reason",
    excluded: "This record is excluded from current trace. Its history remains readable.",
    quantityNote:
      "Recorded quantity is separate from case links; no case IDs are selected by Shipping.",
    balanceAwaiting: "Frozen recorded quantity; current lot balance is shown separately.",
    balanceLoading: "Reading current recorded lot balance…",
    balanceReadFailed: "Current recorded lot balance is unavailable. Refresh to try again.",
    currentRecordedBalance: "Current recorded lot balance: {{quantity}} {{unit}}",
    balanceBeforeReplacement: "Balance before replacement: {{quantity}} {{unit}}",
    proposedQuantity: "Proposed shipment quantity: {{quantity}} {{unit}}",
    balanceUnknownReason: {
      no_current_origin:
        "Current recorded lot balance is unknown: no current origin event. Record the origin before finalizing.",
      mixed_uom:
        "Current recorded lot balance is unknown: event units differ. Correct the source records before finalizing.",
      invalid_quantity:
        "Current recorded lot balance is unknown: a recorded quantity is invalid. Review the event history.",
      overflow:
        "Current recorded lot balance is unknown: recorded quantities exceed the supported range. Review the event history.",
    },
    projectedRemaining: "Projected after this draft: {{quantity}} {{unit}}",
    forecastOver:
      "Projected after this draft: {{quantity}} {{unit}}. Reduce the quantity before finalizing.",
    forecastExhausted:
      "No recorded balance remains. Choose another lot or correct its source events.",
    forecastUomMismatch:
      "Unit differs from the lot origin. Select {{unit}} or correct the source records.",
    forecastUnknown:
      "A remaining quantity cannot be projected while the recorded balance is unknown.",
    forecastInvalidQuantity: "Enter a positive quantity with up to three decimal places.",
    forecastInputNeeded: "Enter a quantity and unit to see the draft projection.",
    forecastCaveat: "Draft preview only; finalization rechecks the recorded balance.",
    refreshBalance: "Refresh balance",
    shipFromDescription: "Ship-from description",
    recipientDescription: "Recipient description",
    sourceDescription: "Source description",
    resolvedLocation: "Resolved location",
    productDescription: "Product description",
    businessName: "Business name",
    phoneNumber: "Phone",
    streetAddress: "Street address",
    coordinates: "Coordinates",
    city: "City",
    stateOrRegion: "State or region",
    zipOrPostalCode: "ZIP or postal code",
    country: "Country",
    countryCode: "Country code",
    locationId: "Location ID",
    partyId: "Party ID",
    productId: "Product ID",
    brand: "Brand",
    commodity: "Commodity",
    variety: "Variety",
    packagingSize: "Packaging size",
    packagingStyle: "Packaging style",
    gtin: "GTIN",
    sourceKind: "Source kind",
    sourceReference: "Source reference",
    sourceLocation: "Location",
    sourceWebUrl: "Web URL",
    issuer: "Issuer",
    issuerLegalName: "Issuer legal name",
    history: "Revision history",
    historyFailed: "Revision history could not be loaded. The displayed record is unchanged.",
    historyReadFailed: "That revision could not be opened. The displayed record is unchanged.",
    selected: "Selected",
    previousPage: "Previous page",
    nextPage: "Next page",
  },
  "es-US": {
    new: "Nuevo envío",
    title: "Borrador de envío",
    detail: "Detalle de envío",
    audit: "Auditoría del registro",
    date: "Fecha de envío",
    shipFrom: "Origen del envío",
    recipient: "Destinatario inmediato posterior",
    recipientHint: "Seleccione al destinatario que recibe el alimento, no al transportista.",
    carrier: "Referencia del transportista (opcional)",
    notes: "Notas",
    lines: "Lotes y cantidades",
    line: "Línea {{number}}",
    lot: "Lote existente",
    addLot: "Añadir lote",
    removeLine: "Quitar línea",
    quantity: "Cantidad",
    unit: "Unidad",
    lotIdentity: "El TLC y el producto proceden del lote seleccionado.",
    documents: "Documentos de referencia",
    document: "Documento de referencia",
    addDocument: "Adjuntar documento",
    detach: "Desvincular",
    readiness: "Integridad",
    check: "Comprobar preparación",
    saveFirst: "Guarde el borrador antes de comprobar la preparación.",
    saveChanges: "Guarde los cambios antes de comprobar la preparación.",
    complete: "Completo — listo para finalizar",
    incomplete: "Incompleto — no se puede finalizar",
    blockers: "Bloqueos del envío",
    issueField: {
      record: "Registro de envío",
      date: "Fecha de envío",
      timeZone: "Zona horaria",
      shipFrom: "Ubicación de origen",
      recipient: "Destinatario inmediato",
      documents: "Documentos de referencia",
      items: "Lotes y cantidades",
      lot: "Lote existente",
      quantity: "Cantidad",
      unit: "Unidad",
      tlc: "Código de lote de trazabilidad",
      source: "Fuente del lote",
      product: "Descripción del producto",
      coverage: "Cobertura del producto",
      origin: "Origen del lote",
    },
    issueFix: {
      required:
        "Introduzca o seleccione este dato obligatorio y vuelva a comprobar la preparación.",
      format: "Corrija el formato del dato o de la unidad y vuelva a comprobar la preparación.",
      unavailable: "Seleccione un registro disponible que pertenezca a este cliente.",
      inactive: "Seleccione un registro activo o reactive el previsto antes de volver a comprobar.",
      incompleteShipFrom:
        "Complete la descripción de la ubicación de origen en Ubicaciones y vuelva a comprobar la preparación.",
      incompleteRecipient:
        "Complete la descripción de la ubicación del destinatario en Ubicaciones y vuelva a comprobar la preparación.",
      incompleteDocument:
        "Complete el tipo y número del documento adjunto y vuelva a comprobar la preparación.",
      incompleteProduct:
        "Complete la descripción del producto seleccionado en Productos y vuelva a comprobar la preparación.",
      wrongRole: "Elija una ubicación con la función de origen o destinatario requerida.",
      sameLocation: "Elija un destinatario distinto de la ubicación de origen.",
      duplicate: "Quite el lote o documento repetido de este envío.",
      statusBlocked: "Elija un lote activo apto para el envío.",
      sourceUnresolved: "Resuelva la fuente del lote con una descripción completa de la ubicación.",
      coverageUnresolved: "Revise y resuelva la clasificación de cobertura del producto.",
      originMissing: "Registre el origen del lote antes de enviarlo.",
      balanceUnknown: "Confirme el saldo disponible del lote antes de finalizar.",
      balanceExhausted: "Elija un lote con saldo restante o quite esta línea.",
      uomMismatch: "Seleccione la unidad de medida del saldo del lote.",
      overShipment: "Reduzca la cantidad enviada al saldo disponible.",
      fallback:
        "Revise y corrija este campo; luego vuelva a comprobar la preparación. Contacte con soporte si persiste.",
    },
    save: "Guardar borrador",
    saving: "Guardando…",
    invalid: "Revise los campos del borrador y la selección del lote existente.",
    loadError: "No se pudo cargar el registro de envío.",
    saveFailed: "No se pudo guardar el borrador. Se conservó su entrada.",
    checkFailed: "No se pudo comprobar la preparación. Inténtelo de nuevo.",
    stale: "El registro guardado cambió. Vuelva a cargarlo antes de otra operación.",
    uncertain:
      "Se desconoce el resultado de la operación. Reintente la misma operación o vuelva a cargar el registro.",
    retrySame: "Reintentar la misma operación",
    reload: "Volver a cargar el registro",
    reloadConfirm: "¿Volver a cargar y descartar los cambios locales?",
    leaveUncertain:
      "Es posible que esta operación se haya completado. ¿Salir y abandonar la recuperación local?",
    unavailable: "Este registro de envío no está disponible con el acceso o perfil actual.",
    downstreamBlocked:
      "Un evento posterior bloquea esta corrección. Revise los registros indicados.",
    downstreamItem: "Lote {{lotId}} · Evento {{eventId}} · revisión {{revision}}",
    downstreamMore: "Existen más bloqueos posteriores; esta lista es limitada.",
    finalize: "Finalizar envío",
    finalizeConfirm: "¿Finalizar este registro de envío guardado y fijar sus KDE?",
    finalizeQuantity: "Cantidad registrada: {{quantity}}",
    noCaseClaim: "Este registro no identifica cajas enviadas ni acredita el despacho físico.",
    confirmFinalization: "Confirmar finalización",
    amendment: "Iniciar modificación",
    void: "Anular envío",
    cancelAmendment: "Cancelar modificación",
    actionReason: "Motivo de calidad",
    confirmAmendment: "Confirmar modificación",
    confirmVoid: "Confirmar anulación",
    confirmCancellation: "Confirmar cancelación",
    amendmentHint:
      "Cree una nueva revisión en borrador. La revisión finalizada actual sigue vigente hasta finalizar la modificación.",
    voidHint:
      "Excluya este registro de la trazabilidad vigente. Su historial fijado permanece legible.",
    cancelAmendmentHint:
      "Anule solo este borrador de modificación pendiente. La revisión anterior permanece como envío finalizado vigente.",
    cancel: "Cancelar",
    revision: "Revisión {{number}}",
    current: "Revisión vigente",
    pending: "Borrador pendiente",
    previous: "Revisión anterior",
    successor: "Sustituida por",
    finalizedBy: "Finalizado por",
    voidReason: "Motivo de anulación",
    amendedReason: "Motivo de modificación",
    excluded:
      "Este registro está excluido de la trazabilidad vigente. Su historial permanece legible.",
    quantityNote:
      "La cantidad registrada es independiente de los vínculos de cajas; Envío no selecciona ID de cajas.",
    balanceAwaiting:
      "Cantidad registrada congelada; el saldo actual del lote se muestra por separado.",
    balanceLoading: "Consultando el saldo registrado actual del lote…",
    balanceReadFailed:
      "El saldo registrado actual del lote no está disponible. Actualícelo para reintentar.",
    currentRecordedBalance: "Saldo registrado actual del lote: {{quantity}} {{unit}}",
    balanceBeforeReplacement: "Saldo antes del reemplazo: {{quantity}} {{unit}}",
    proposedQuantity: "Cantidad propuesta para el envío: {{quantity}} {{unit}}",
    balanceUnknownReason: {
      no_current_origin:
        "Se desconoce el saldo registrado actual: no hay un evento de origen vigente. Registre el origen antes de finalizar.",
      mixed_uom:
        "Se desconoce el saldo registrado actual: las unidades de los eventos difieren. Corrija los registros de origen antes de finalizar.",
      invalid_quantity:
        "Se desconoce el saldo registrado actual: una cantidad registrada no es válida. Revise el historial de eventos.",
      overflow:
        "Se desconoce el saldo registrado actual: las cantidades exceden el rango admitido. Revise el historial de eventos.",
    },
    projectedRemaining: "Proyección después de este borrador: {{quantity}} {{unit}}",
    forecastOver:
      "Proyección después de este borrador: {{quantity}} {{unit}}. Reduzca la cantidad antes de finalizar.",
    forecastExhausted:
      "No queda saldo registrado. Elija otro lote o corrija sus eventos de origen.",
    forecastUomMismatch:
      "La unidad difiere de la del origen del lote. Seleccione {{unit}} o corrija los registros de origen.",
    forecastUnknown:
      "No se puede proyectar la cantidad restante mientras se desconozca el saldo registrado.",
    forecastInvalidQuantity: "Introduzca una cantidad positiva con hasta tres decimales.",
    forecastInputNeeded:
      "Introduzca una cantidad y una unidad para ver la proyección del borrador.",
    forecastCaveat:
      "Solo es una vista previa; la finalización vuelve a comprobar el saldo registrado.",
    refreshBalance: "Actualizar saldo",
    shipFromDescription: "Descripción del origen",
    recipientDescription: "Descripción del destinatario",
    sourceDescription: "Descripción de la fuente",
    resolvedLocation: "Ubicación resuelta",
    productDescription: "Descripción del producto",
    businessName: "Nombre comercial",
    phoneNumber: "Teléfono",
    streetAddress: "Dirección",
    coordinates: "Coordenadas",
    city: "Ciudad",
    stateOrRegion: "Estado o región",
    zipOrPostalCode: "Código postal",
    country: "País",
    countryCode: "Código de país",
    locationId: "ID de ubicación",
    partyId: "ID de entidad",
    productId: "ID de producto",
    brand: "Marca",
    commodity: "Producto básico",
    variety: "Variedad",
    packagingSize: "Tamaño del envase",
    packagingStyle: "Tipo de envase",
    gtin: "GTIN",
    sourceKind: "Tipo de fuente",
    sourceReference: "Referencia de origen",
    sourceLocation: "Ubicación",
    sourceWebUrl: "URL web",
    issuer: "Emisor",
    issuerLegalName: "Razón social del emisor",
    history: "Historial de revisiones",
    historyFailed: "No se pudo cargar el historial de revisiones. El registro mostrado no cambió.",
    historyReadFailed: "No se pudo abrir esa revisión. El registro mostrado no cambió.",
    selected: "Seleccionada",
    previousPage: "Página anterior",
    nextPage: "Página siguiente",
  },
} as const;
